### ISSUE TITLE
Virtual cam doen't appear in zoom, but works in other programs

### ISSUE THREAD

**Issue by Mafraysse** [johnboiles/obs-mac-virtualcam#100]
Hi.
I can't use OBS virtual cam in zoom. I don't know why.
What works with QuickTime... skype...
Any idea to solve this issue ?

Thanks.

**Comment by gxalpha** [comment]
you need additional steps to get zoom to work. 
See https://github.com/johnboiles/obs-mac-virtualcam/wiki/Compatibility and #4
