### ISSUE TITLE
[BUG] Computer needs to be restarted after updating the plugin

### ISSUE THREAD

**Issue by johnboiles** [johnboiles/obs-mac-virtualcam#109]
**Describe the bug**
After updating the plugin, it seems you need to restart your computer for some apps to work. I see this in Console.app which is probably the culprit. Maybe there's something in the kernel that doesn't allow a different binary to access the same mach port until you restart.

    Sandbox: QuickTime Player(15578) deny(1) mach-lookup com.johnboiles.obs-mac-virtualcam.server

**To Reproduce**
1. Install plugin 1.0.0
2. Try out streaming to QuickTime
3. Install plugin 1.1.0
4. Try out streaming to QuickTime

**Expected behavior**
It should work with the new version.

**Desktop (please complete the following information):**
 - OS version: macOS Catalina 10.15.4
 - Viewer: QuickTime Player 10.5 (1015.2.1)

**Comment by johnboiles** [comment]
I wonder if we simply attached the version number of that would help the upgrade process `com.johnboiles.obs-mac-virtualcam.server-110` Or something like that

**Comment by johnboiles** [comment]
Actually I realize I never changed the version number in the Info.plist (fixed in https://github.com/johnboiles/obs-mac-virtualcam/commit/17565e1a15fdecdba57244757aba953f9e717b0d). Maybe macOS is smart enough to see the version change 🤞

**Comment by gxalpha** [comment]
Ok so we have to change it before each release?

**Comment by johnboiles** [comment]
Yeah. We should probably do that anyways for all builds regardless of whether it solves this issue. We could probably automate it also -- perhaps there's a thing that when you push a special branch or something like that it sets the version number, creates a tag, builds, and submits a release.

Ok so I just tried the latest build and didn't need to restart so who knows maybe it just will work. I'm going to change history a bit and retag master as v1.1.0 and change the release to maaayyybe save some people from needing to restart.

**Comment by johnboiles** [comment]
Ok I sneakily rewrote history and replaced the 1.1.0 build with this new one. Maybe we'll get fewer reports of needing a restart.

**Comment by moonpost** [comment]
just tried it by deleted the old 1.0 build and installing the 1.1.0 build and it worked without a reboot.

**Comment by johnboiles** [comment]
I think we can call this closed.
