### ISSUE TITLE
Regular View instead of Mirror

### ISSUE THREAD

**Issue by kam2108** [johnboiles/obs-mac-virtualcam#111]
i think putting a regular view instead of mirror because you see exactly what is being output-ed in the correct manner in the preview in OBS instead of having to flip everything horizontally and make illegible on OBS but okay on the webcam stream which is Kinda weird.

**Comment by rjmunro** [comment]
OBS and this plugin are not normally doing the mirrored views. The mirroring is happening in whatever software you are passing the stream into. You can usually turn this off in the settings. Which software are you using?

Note that even though what you see is mirrored, what the person at the other end of your call, chat or stream will see will normally not be.

**Comment by gxalpha** [comment]
> i think putting a regular view instead of mirror because you see exactly what is being output-ed in the correct manner in the preview in OBS

I don't get want you want to say, the OBS preview *does* show the regular view. The preview of some VC apps doesn't, but your partner *will always see what you see in the OBS preview.*

Feel free to reopen this if I didn't solve your problem.
