### ISSUE TITLE
[BUG] Only sporadically works with Jitsi.org

### ISSUE THREAD

**Issue by chrismarquardt** [johnboiles/obs-mac-virtualcam#113]
I often use the open-source Jitsi videoconferencing system. To make the virtual camera work, 

**To Reproduce**
1. Go to meet.jit.si with Chrome and create a random meeting room
2. Click the 3 dots at the right bottom and select the OBS virtual camera

**Expected behavior**
Virtual camera shows up.

**Actual behavior**
I had to turn on/off the virtual camera in OBS several times and change my virtual camera selection in the Jitsi session several times until the selection didn't thrown an error in Jitsi

**Desktop (please complete the following information):**
 - OS version: macOS Catalina 10.15.4
 - Browser: Chrome
 - OBS 25.0.8

**Comment by johnboiles** [comment]
Thanks for the report! Did Jitsi give you a specific error? Could you also check the Chrome Inspector console (cmd-option-i) for errors?

**Comment by johnboiles** [comment]
Also, what FPS, color space, and resolution are you using from OBS?

**Comment by chrismarquardt** [comment]
No specific error message. 30 FPS, yuv, 1080p. 

Odd thing is that I couldn’t reproduce the issue since. After it began to work, it now works consistently. Strange. Guess you can close this for now, I’ll reopen and provide some more debug info if it comes back.

**Comment by johnboiles** [comment]
Strange! Def reopen if you start having issues again.
