### ISSUE TITLE
[Support] Can't see "Start virtual camera" button

### ISSUE THREAD

**Issue by alexsester** [johnboiles/obs-mac-virtualcam#115]
_Please read the "Discussion / Support" section of the Readme first. Only open an issue if you don't get an answer on the OBS or someone tells you to._

**Describe the issue**
can't see tools>start virtual camera
**To Reproduce**
1. add video capture device
2. Click on OBS virtual camera device
3. i can see the image like the shot uploaded

**Behavior**
the plug in in fully installed in the two library folders and i can see the virtual camera options inside Skype, Zoom and others applications
**Screenshots**
see attached file
<img width="1792" alt="Schermata 2020-05-15 alle 23 07 01" src="https://user-images.githubusercontent.com/65424133/82096395-2f25f680-9701-11ea-9251-82823a1d4c84.png">

**Desktop (please complete the following information):**
 - OS version: [e.g. macOS Catalina 10.15.4]
 - OBS
 - Virtualcam version: [e.g. 1.1.0]
 - OBS version: [e.g. 24.0.6]

**Additional context**
nothing

**Comment by johnboiles** [comment]
Please try the most recent version of OBS and report back. As mentioned in the README I don't officially support a anything except the most recent version (currently 25.0.8)

**Comment by djtideBR** [comment]
I have the same problem, but the OBS 25.0.8 dont run in OS 10.12 (sierra) :(

**Comment by johnboiles** [comment]
We're not going to support 10.12 Sierra since OBS project doesn't support it. I think there was some reason with QT compatibility where OBS had to drop support for it -- meaning that we'd need to distribute a separate version of this plugin just to support 10.12. You're welcome to try to build the plugin from source though! Or update your OS :)

**Comment by alexsester** [comment]
Thanks for the note. I upgrading OBS and the plugin works
Alex

Il giorno sab 16 mag 2020 alle 08:46 John Boiles <notifications@github.com>
ha scritto:

**Comment by alexsester** [comment]
Hi John, after the Zoom's last release i can't see the Virtualcam option.
I have this setting:
Zoom Version: 5.1.0 (27838.0614)
Obs OBS 25.0.8
OS Catalina 10.15.5 
Virtualcam 1.2

thank you

**Comment by gxalpha** [comment]
you need to do the resigning again.
https://github.com/johnboiles/obs-mac-virtualcam/wiki/Compatibility#apps-dont-allow-dal-plugins

**Comment by alexsester** [comment]
Hi @gxalpha thanks for the note, i read about this on Zoom

Release notes of 5.0.4 (25694.0524)
Changes to existing features
-Re-enable virtual camera support
Resolved Issues
-Minor Bug Fixes

But actually virtual cam doesn't work anymore

**Comment by gxalpha** [comment]
Yes, that is not true. You still need to resign zoom for this virtual camera to work until it is merged into the OBS project which still is some time off.

**Comment by alexsester** [comment]
thanks for the note @gxalpha in order to resign zoom app do you have a tutorial that i can follow? I'm sorry but i'm not used to this. Alex

**Comment by alexsester** [comment]
@gxalpha i found i tutorial on youtube, thanks for the note! I hope it will works
