### ISSUE TITLE
[BUG] Does not work with 4k video source

### ISSUE THREAD

**Issue by mike-leber** [johnboiles/obs-mac-virtualcam#116]
**Describe the bug**
Picture gets frozen (eg on Quicktime or Zoom)

**To Reproduce**
Added a 4k camera via Elgato camlink

**Expected behavior**
Video should be transmitted (just like with manycam, which I tried in parallel)

**Desktop (please complete the following information):**
 - OS version: macOS Catalina 10.15.5
 - Application: Quicktime
 - Virtualcam version: 1.1.0 RC1
 - OBS version: [e.g. 25.0.8

**Comment by johnboiles** [comment]
Interesting! To my knowledge you're the first one to try 4k! What are your system specs? What FPS are you sending? There's a few more memory copies in the plugin than I'd like and it's possible that Mach IPC just can't keep up with sending uncompressed 4k streams across processes (4k @ 30 FPS is ~0.5GB/s).

Do you get anything in Console.app logs (search for `obs-mac-virtualcam`)? What about OBS logs?

Also are you on one of the Catalina 10.15.5 betas? I don't think 10.15.5 has been released yet.

**Comment by mike-leber** [comment]
First, really thanks a lot for your effort on this project!

Well trying, because I wanna record in parallel for later upload and avoid double work.
My fault btw, typo: I'm on Catalina 10.15.4 not 10.15.5
I was streaming 4k 25fps

Need to check logs. But I was trying the free demo from manycam.com

With this app you might compare too.
1) their stream works

2) CPU is less stressed in general (eg fan of my 2018 macbook pro 13, (2,7GHz Quad i7, 16GB Ram, Intel Iris Plus Graphics 655 1536 MB) does hardly work with manycam live. But its super busy with OBS and this virtual cam

3) Needed to to blind testing. But with OBS / virtual pic looks slightly more blurry, streaming HD via Logitech 930e, than via manycam, which looks exactly the same as the original video coming through Logitech's Camera Settings app

**Comment by mike-leber** [comment]
Could not find anything about obs-mac-virtualcam in system logs other than install.
OBS log attached.
[2020-05-16 22-00-10.txt](https://github.com/johnboiles/obs-mac-virtualcam/files/4639149/2020-05-16.22-00-10.txt)

**Comment by Sydney-o9** [comment]
Same issue here - the image is frozen!

**Comment by mike-leber** [comment]
Actually I recognize, when Live on Zoom, the screen either gets frozen or only changing framewise, while OBS still records fluently (programm window is all fine). Just seems like some buffers get filled up and can't synch anymore between capture and streaming.

**Comment by johnboiles** [comment]
That seems to indicate a performance problem. Some people with old computers are reporting the same at lower resolutions. I think if the system can't keep up it just stops communicating between processes.

**Comment by mike-leber** [comment]
Mine is a macbook 13, late 2018, 16gb ram, best available processor, of course no gpu (see sbove). Waiting for new imacs this year to come out. But constraint testing is always helpful.

**Comment by johnboiles** [comment]
Just as a data point 4k worked for me streaming from OBS to QuickTime

**Comment by johnboiles** [comment]
From my observations there's not an inherent reason this plugin doesn't work at 4k, but it's pretty performance intensive to transfer that much data between processes. Solving any of the open issues labeled with performance could help, as would faster computers.
