### ISSUE TITLE
Virtual Camera not available as a source in Safari

### ISSUE THREAD

**Issue by ellenich** [johnboiles/obs-mac-virtualcam#117]
**Describe the bug**
It appears that you cannot select Virtual Camera as a video source in Safari. I'm able to see and use the Virtual Camera in Chrome just fine.

<img width="1792" alt="Screenshot 2020-05-16 08 44 56" src="https://user-images.githubusercontent.com/6808795/82124275-d3845900-9752-11ea-87ae-1996198b0f27.png">
<img width="1792" alt="Screenshot 2020-05-16 08 52 32" src="https://user-images.githubusercontent.com/6808795/82124282-dbdc9400-9752-11ea-9f63-be52732f60cd.png">

**To Reproduce**
Open Safari
Start a new Google Meet meeting
Try to switch video source to Virtual Camera (it's not available)
Expected behavior
Virtual Camera should be a selectable source in Safari.

OS version: macOS Mojave 10.14.6
Application: Safari 13.1
Virtualcam version: 1.1.0 RC1
OBS version: 25.0.8

**Comment by gxalpha** [comment]
Safari doesn't work, unfortunately.
https://github.com/johnboiles/obs-mac-virtualcam/wiki/Compatibility
