### ISSUE TITLE
Garbled output in QuickTime

### ISSUE THREAD

**Issue by badprogramshere** [johnboiles/obs-mac-virtualcam#118]
On Mojave 10.14.6, when I view the output from the virtual camera in QuickTime, I instead get a garbled mess. 

Here's what I see in Quicktime:
<img width="952" alt="Screen Shot 2020-05-17 at 1 56 16 AN" src="https://user-images.githubusercontent.com/46780907/82137026-99947f00-9846-11ea-96c8-45708ab1dc89.png">

And here's what I have in OBS:
<img width="1191" alt="Screen Shot 2020-05-17 at 1 57 00 AN" src="https://user-images.githubusercontent.com/46780907/82137036-c9dc1d80-9846-11ea-97d3-64cec7695bd3.png">

I'm using OBS 25.0.8, on a MacBook Pro 13-inch from early 2015.

**Comment by johnboiles** [comment]
What resolution, frame rate, and color space (eg 601) are you using?

**Comment by badprogramshere** [comment]
Looks like using a resolution of 1680*1050 doesn't work. I changed it to 1920*1080 and now it works. Thank you anyway!

**Comment by johnboiles** [comment]
If you had a moment, could you try your original resolution in a few other apps? I'm curious if QuickTime doesn't like that resolution or if my plugin is sending the wrong thing.

**Comment by badprogramshere** [comment]
I tried using the original resolution in Google Meet and Screenflick (using the virtual camera as a face cam.) It also gave garbled output

**Comment by johnboiles** [comment]
Interesting! Well thanks for the info!
