### ISSUE TITLE
Works on Skype but not Zoom

### ISSUE THREAD

**Issue by Sydney-o9** [johnboiles/obs-mac-virtualcam#119]
Hi Team,

What a fantastic plugin. Currently, this works really well on Skype but not on Zoom, i.e OBS Virtual Camera does not show in Zoom, any ideas why?

Thank you!

**Comment by Sydney-o9** [comment]
This is due to Zoom removing the ability to have Virtual Cameras

https://medium.com/@dkiesow/how-to-fix-the-virtual-camera-function-in-zoom-mac-only-9872a6d9ea5

**Comment by gxalpha** [comment]
@Sydney-o9 you are correct, but you can work around that issue. 
See https://github.com/johnboiles/obs-mac-virtualcam/wiki/Compatibility#apps-dont-allow-dal-plugins
