### ISSUE TITLE
feature request: make two instances at once possible

### ISSUE THREAD

**Issue by gxalpha** [johnboiles/obs-mac-virtualcam#12]
From a comment over [here](https://github.com/obsproject/rfcs/pull/15#issuecomment-609057392). 
Starting the camera on the second instance causes the first one to crash. It'd be cool if you could have multiple instances of the camera. (Personally I don't know why you would start two cameras at once, but it would be good to avoid unnecessary crashes. Although imo this doesn't have priority)

**Comment by johnboiles** [comment]
This would be awesome. But I don't think you can have two copies of the DAL plugin running at the same time, so this would probably require the DAL plugin to advertise two devices. I'm pretty sure this is possible, but will probably be a fairly large project.

**Comment by signalwerk** [comment]
@gxalpha @johnboiles I suggested the simplified logic of the discussion to the RFC: https://github.com/jebjeb/rfcs/pull/3

**Comment by dodgepong** [comment]
I don't think this is necessary for a MVP.

**Comment by gxalpha** [comment]
You're probably right. 
I'll still leave it open, maybe some day...

**Comment by gxalpha** [comment]
I made up my mind and will close it now, since the RFC only wants one instance.
