### ISSUE TITLE
[Support] Virtual camera not available in zoom

### ISSUE THREAD

**Issue by thedug** [johnboiles/obs-mac-virtualcam#120]
_Please read the "Discussion / Support" section of the Readme first. Only open an issue if you don't get an answer on the OBS or someone tells you to._

**Describe the issue**
A clear and concise description of what the problem is.

I just switched to using the official pkg with the official OBS. For the past 2 weeks I've been using a locally compiled version.

After installing the pkg version zoom no longer sees the OBS Virtual Camera. 

**To Reproduce**
1. Open OBS
2. Click on Start Virtual Web Cam
3. Start Zoom
4. Click on Video Sources - Notice Obs is not present. 

**Behavior**
Obs Virtual Web Cam is no longer loading in zoom. 

**Screenshots**

**Desktop (please complete the following information):**
 - OS version: Mac OS 10.15.4 
 - Application Zoom 5.0.2
 - Virtualcam version: 1.1.0
 - OBS version: 25.0.8

**Additional context**
I saw on your readme that zoom is not supported, but it was working before I installed the pkg version.

**Comment by gxalpha** [comment]
Try resigning Zoom again. 
https://github.com/johnboiles/obs-mac-virtualcam/wiki/Compatibility#apps-dont-allow-dal-plugins

**Comment by johnboiles** [comment]
Also did you restart? For some reason some people need to restart when installing a new version

**Comment by Spiffy24** [comment]
I downloaded everything fresh last night and I've been having all the same issues as thedug but with Discord.

**Describe the issue**
Discord will not recognize OBS Virtual Web Cam

**To Reproduce**
- Open OBS
- Click on Start Virtual Web Cam
- Open Discord
- Look into Discord Video preferences, 
- Click on Video Sources - Obs is not present.

**Behavior**
OBS virtual web cam is not loading on Discord as if the webcam doesn't exist

**Desktop**

OS version: Mac OS 10.15.4
Application: Discord 0.0.257
Virtualcam version: 1.1.0
OBS version: 25.0.8

**Additional context**

Troubleshooting: Google Meets can detect the Virtual Camera just fine.

I hope this was helpful and I thank you for all the work you're putting into this.

**Comment by gxalpha** [comment]
@Spiffy24 
have you restarted discord?
Also if you did try rebooting

**Comment by Spiffy24** [comment]
Yep and yep.

Just rebooted to be sure. The virtual camera is still undetectable in Discord preferences.

**Comment by thedug** [comment]
I finally got it to appear. But I rebooted numerous times.

And I rand this

APPLICATION=/Applications/zoom.us.app && codesign -d --entitlements :- $APPLICATION | { xml2; echo "/plist/dict/key=com.apple.security.cs.disable-library-validation"; echo "/plist/dict/true"; } | 2xml > entitlements.xml && sudo codesign --sign - $APPLICATION --force --preserve-metadata=identifier,resource-rules,flags --entitlements=entitlements.xml && rm entitlements.xml

**Comment by johnboiles** [comment]
@thedug glad to hear you got it working. Perhaps you updated zoom in between running the old plugin and the new pkg release? There was a Zoom update pretty recently. You'll need to re-codesign every new Zoom release

**Comment by thedug** [comment]
@johnboiles  Yeah.. I had already run into that and had to re-run it. This was different. I ran my entitlements script and rebooted twice before zoom worked.

Note: I think I did find a few recommended deletes to cleanup old plugins. I think I did that between reboots, so that might have helped.
