### ISSUE TITLE
Plugin does not work on 24.0.6

### ISSUE THREAD

**Issue by ocirema** [johnboiles/obs-mac-virtualcam#121]
Hi.

Due to high resources consumption in 25.x I need to revert to OBS 24.0.6 on my Mac.
Unfortuatelly the plug-in doesn't show in in the menu after installed.
Is this something you can fix?

Thanks a lot!

**Comment by ocirema** [comment]
This the reason I need to run 24.0.6: https://github.com/obsproject/obs-studio/issues/2841

**Comment by gxalpha** [comment]
Hey, 
as far as I'm aware this plugin won't work with anything below 25 (which doesn't mean it couldn't, but no-one got around to it).
So no, unfortunately there is nothing you can do (if you're not a developer)

**Comment by ocirema** [comment]
:-(

**Comment by johnboiles** [comment]
Feel free to build it from source, and please report back if it works! See the 'developing' section of the wiki for instructions

**Comment by johnboiles** [comment]
But as mentioned in the README were only supporting the latest OBS build at any given time
