### ISSUE TITLE
Sierra Support?

### ISSUE THREAD

**Issue by Nidocamen** [johnboiles/obs-mac-virtualcam#122]
I need to be able to have a virtual camera in OBS, but due to other app restrictions / compatibility on my system, I am currently stuck on Sierra and OBS 24.0.6.

Perhaps getting v25.0.4 might help, as you guys mention that you only support the latest version, which would be v25. v25.0.4 also appears to be the last version that had support for Sierra. Interestingly enough, the Virtual Camera actually does appear in other apps like Quicktime Player, MS Teams, etc, but of course it says that it is inactive. And, after installing it and even a reboot, there is no "Start Virtual Camera" option under Tools in OBS.

Anyhow, maybe I'm just stuck and it's not going to work, but I thought I'd post anyways. Thanks!

**Comment by dodgepong** [comment]
There was never a build of OBS v25+ for 10.12. The absolute most recent version of OBS that supported 10.12 is 24.0.6.

**Comment by johnboiles** [comment]
Thanks for the historical context @dodgepong! @Nidocamen I'm not going to put time into making this work for Sierra but maybe try to compile from sources based on the notes in the developing section of the wiki
