### ISSUE TITLE
Fails to appear as a source at all on macOS 10.14 Mojave

### ISSUE THREAD

**Issue by timboxyz** [johnboiles/obs-mac-virtualcam#123]
Installed 1.10 over 1.0.0 and started OBS 
Current log shows module loaded OK, so enabled it in Tools.
(It did produce an error about En-US translations not available for the module but this did not stop it loading)
Started Webcamoid/Brave (running Jitsi) but not showing as a source.

Rebooted and reran OBS, started output in Tools then Webcamoid/Brave
Same result.

I would have expected the output to have appeared in the source lists
of both applications. It doesn't even show as a video source in OBS itself

**Desktop
 - OS version: macOS Mojave 10.14.6
 - Application: Webcamoid, Chromium (Brave)
 - Virtualcam version: 1.1.0
 - OBS version: 25.0.8

**Comment by summersw** [comment]
Same issue.  Have uninstalled, reinstalled, and rebooted; but the virtual camera does not appear in the source list of any apps (webcamoid, zoom (4.6.10), jitsi, meet, camtwist, etc...)

No errors (apart from translation) and the menu selection appears to work.  It had been working when built from source (I have not had the opportunity to rebuild from latest but will comment again when I do)

**Desktop

    OS version: macOS Mojave 10.14.6
    Application: webcamoid, zoom (4.6.10), jitsi, meet, camtwist,
    Virtualcam version: 1.1.0
    OBS version: 25.0.8

**Comment by johnboiles** [comment]
Can y'all do two things?

* Open Console.app and watch for any logs about `obs-mac-virtualcam` when you run the host apps (e.g. jitsi/chrome). Paste those logs here
* Run this `ls /Library/CoreMediaIO/Plug-Ins/DAL` and make sure `obs-mac-virtualcam.plugin` is there

**Comment by summersw** [comment]
plugin is there, but there are no logs mentioning obs-mac-virtualcam.

I started the console, opened obs, started the virtualcam (menu indicates it is started), opened various apps (jitsi, zoom, camtwist), and searched the logs for obs-mac-virtualcam.  Nothing.

**Comment by timboxyz** [comment]
> plugin is there, but there are no logs mentioning obs-mac-virtualcam.
> 
> I started the console, opened obs, started the virtualcam (menu indicates it is started), opened various apps (jitsi, zoom, camtwist), and searched the logs for obs-mac-virtualcam. Nothing.

Same for me.

**Comment by johnboiles** [comment]
@timboxyz have you downloaded a recent version of this plugin? Should have been compiled for 10.13 as of about a week ago. Can you run `cat /Library/CoreMediaIO/Plug-Ins/DAL/obs-mac-virtualcam.plugin/Contents/Info.plist | grep -a3 CFBundleShortVersionString` and paste the output?

**Comment by summersw** [comment]
```
	<string>OBS Virtual Camera</string>
	<key>CFBundlePackageType</key>
	<string>BNDL</string>
	<key>CFBundleShortVersionString</key>
	<string>7.0</string>
	<key>CFBundleSignature</key>
	<string>????</string>
```

**Comment by summersw** [comment]
I am using `obs-mac-virtualcam-0e62cec-v1.1.0.pkg` from the releases page.
Output from `Info.plist`
```
	<string>OBS Virtual Camera</string>
	<key>CFBundlePackageType</key>
	<string>BNDL</string>
	<key>CFBundleShortVersionString</key>
	<string>7.0</string>
	<key>CFBundleSignature</key>
	<string>????</string>
```

**Comment by johnboiles** [comment]
I think you ran into #128. I'm still investigating why that is. I think maybe pkg installers don't like to install older versions, and we fixed the version number in 1.1.0 (it was 7.0 as you see above).

Can you try deleting the plugin `sudo rm -rf /Library/CoreMediaIO/Plug-Ins/DAL/obs-mac-virtualcam.plugin` and then reinstalling to see if it works?

**Comment by summersw** [comment]
Yup.  That was it!  The virtualcam is now working in Zoom (5.0.3-latest), jitsi, and Photo Booth.

- I deleted the DAL plugin (not the OBS plugin)
- reinstalled (version 1.1.0) from the release page
- rebooted

Thanks!

**Comment by johnboiles** [comment]
@timboxyz can you try the same and see if it resolves your issue?

**Comment by timboxyz** [comment]
As originally stated I installed 1.1 over 1.0.
```
<string>OBS Virtual Camera</string>
	<key>CFBundlePackageType</key>
	<string>BNDL</string>
	<key>CFBundleShortVersionString</key>
	<string>7.0</string>
	<key>CFBundleVersion</key>
	<string>7</string>
```
Will try the unistall and reinstall

**Comment by timboxyz** [comment]
Hmm, I posted a follow-up reply about uninstalling and reinstalling minutes after the above comment (listing the version no) that is now not showing (at least to me) for some reason.

I can confirm that performing those actions did indeed fix the issue so this can be regarded as a copy of #128.
