### ISSUE TITLE
[Support] Cannot find OBS virtual camera in Tools

### ISSUE THREAD

**Issue by Alixuella** [johnboiles/obs-mac-virtualcam#124]
_Please read the "Discussion / Support" section of the Readme first. Only open an issue if you don't get an answer on the OBS or someone tells you to._

**Describe the issue**

I have installed the .pkg for virtual camera. When testing using Quicktime I am finding the virtual camera but in the Obs software there is nothing under Tools. I have reinstalled the plugin with no success. I have also restarted Obs several times. What am I doing wrong?

**Desktop (please complete the following information):**
- OS version: [mac OS Mojave 10.14.6
 - Application (if applicable): Google Meet
 - Virtualcam version: 1.1.0
 - OBS version: 24.0.6

**Comment by Alixuella** [comment]
I have installed the .pkg for virtual camera. When testing using Quicktime I am finding the virtual camera but in the Obs software there is nothing under Tools. I have reinstalled the plugin with no success. I have also restarted Obs several times. What am I doing wrong?

**Comment by gxalpha** [comment]
Please fill out the information above.

**Comment by Alixuella** [comment]
Describe the issue

I have installed the .pkg for virtual camera. When testing using Quicktime I am finding the virtual camera but in the Obs software there is nothing under Tools. I have reinstalled the plugin with no success. I have also restarted Obs several times. What am I doing wrong?

Desktop information:

OS version: mac OS Mojave 10.14.6
Virtualcam version: 1.1.0
OBS version: 24.0.6

**Comment by Alixuella** [comment]
Is this information OK or do I need to provide more information?

**Comment by gxalpha** [comment]
> I have also restarted Obs several times

Have you tried rebooting your computer? Sometimes it is needed

**Comment by rayrrr** [comment]
@Alixuella it would be helpful if you place the information in the issue description. Right now you are adding issue comments. Please edit the "description" field at the top of this issue page at https://github.com/johnboiles/obs-mac-virtualcam/issues/124 and replace the generic template information with the information you are providing.

**Comment by gxalpha** [comment]
The problem is that you are using an old version of OBS. Update OBS and try installing the plugin again.

Feel free to reopen the issue if the problem persists.

**Comment by Alixuella** [comment]
Thank you for your reply. I have modified the description above as requested. @gxalpha yes I did restart it. Can it be that I need to update the obs software?

**Comment by Alixuella** [comment]
Thanks. Solved.
