### ISSUE TITLE
[Feature Request] Add audio stream as a microphone

### ISSUE THREAD

**Issue by diogoterremoto** [johnboiles/obs-mac-virtualcam#125]
**Is your feature request related to a problem? Please describe.**
Currently the source is not exposed as a audio device.

**Describe the solution you'd like**
Add a audio stream to the source.

**Describe alternatives you've considered (if applicable)**
Currently the only way appears to monitor the source in OBS, capture that, and create a virtual device. Kinda sucks.

**Additional context**
I'm using an iPhone as a webcam and this is great. Thank you all. Really appreciate the effort.

**Comment by rayrrr** [comment]
@diogoterremoto great idea, I second it. Might I suggest one more revision to the title to make your idea more clear: something like "[Feature Request] OBS Program audio stream as a virtual microphone." Thanks!

**Comment by gxalpha** [comment]
https://github.com/obsproject/rfcs/blob/master/accepted/0015-virtual-camera-support.md#Drawbacks
> The most obvious omission from this RFC is the lack of virtual audio output in addition to virtual camera output. However, though the features are logically closely related, they are unfortunately vastly different technically speaking.

**Comment by gxalpha** [comment]
I think that no one is working on that at the moment and it would probably be in a separate plugin.
