### ISSUE TITLE
Camera doesn't come up on discord

### ISSUE THREAD

**Issue by mchety** [johnboiles/obs-mac-virtualcam#126]
I saw on the compatibility list that it worked with discord but on the discord desktop app the camera doesn't come up. Does it only work on the web app?

**Comment by johnboiles** [comment]
Please fill out all the details that come up in the template when you create a new issue.

**Comment by mchety** [comment]
The virtual webcam doesn't show up on the possible cameras for the discord desktop.


Steps to reproduce the behavior:
1. Open OBS
2. Start Virtual Webcam
3. Open discord
4. Camera Doesn't come up

**Expected behavior**
I thought that the Virtual Camera would just show up under possible cameras for discord.


Info:
 - macOS Catalina 10.15.3
 -Discord 0.0.257 
 - Virtualcam version 1.1.0
 - OBS version 25.0.8

It works fine on zoom and google meets.

**Comment by johnboiles** [comment]
And you've restarted Discord? Have you also tried restarting your computer?

**Comment by mchety** [comment]
I tried restarting my computer and discord, and I also updated my computer to the latest version of Catalina.

**Comment by gxalpha** [comment]
> Can y'all do two things?
>
>* Open Console.app and watch for any logs about obs-mac-virtualcam when you run the host apps (e.g. jitsi/chrome). Paste those logs here
>* Run this ls /Library/CoreMediaIO/Plug-Ins/DAL and make sure obs-mac-virtualcam.plugin is there

Please do these and report back

**Comment by mchety** [comment]
default	11:14:19.550971-0600	obs	OBSDAL: Device unhandled hasPropertyWithAddress for kCMIOObjectPropertyOwnedObjects
default	11:14:19.939884-0600	Google Chrome Helper (Plugin)	OBSDAL: Server is not available
default	11:14:20.939882-0600	Google Chrome Helper (Plugin)	OBSDAL: Server is not available
default	11:14:21.940149-0600	Google Chrome Helper (Plugin)	OBSDAL: Server is not available
default	11:14:22.940547-0600	Google Chrome Helper (Plugin)	OBSDAL: Server is not available
default	11:14:23.940551-0600	Google Chrome Helper (Plugin)	OBSDAL: Server is not available
default	11:14:24.940695-0600	Google Chrome Helper (Plugin)	OBSDAL: Attempting connection
default	11:14:24.940783-0600	Google Chrome Helper (Plugin)	OBSDAL: -[MachClient connectToServer]
default	11:14:24.941018-0600	Google Chrome Helper (Plugin)	OBSDAL: Initialized mach port 69635 for receiving
default	11:14:24.952095-0600	Google Chrome Helper (Plugin)	OBSDAL: -[Stream stopServingDefaultFrames]
default	11:15:49.582757-0600	Google Chrome Helper (Plugin)	OBSDAL: Received stop message
default	11:15:49.583031-0600	Google Chrome Helper (Plugin)	OBSDAL: -[PlugIn receivedStop] Restarting connection
default	11:15:49.583251-0600	Google Chrome Helper (Plugin)	OBSDAL: -[PlugIn stopStream]
default	11:15:49.583479-0600	Google Chrome Helper (Plugin)	OBSDAL: -[PlugIn startStream]
default	11:15:49.583765-0600	Google Chrome Helper (Plugin)	OBSDAL: -[Stream startServingDefaultFrames]
default	11:15:49.584522-0600	Google Chrome Helper (Plugin)	OBSDAL: Attempting connection
default	11:15:49.584784-0600	Google Chrome Helper (Plugin)	OBSDAL: -[MachClient connectToServer]
default	11:15:50.942926-0600	Google Chrome Helper (Plugin)	OBSDAL: Attempting connection
default	11:15:50.943320-0600	Google Chrome Helper (Plugin)	OBSDAL: -[MachClient connectToServer]
default	11:15:51.952261-0600	Google Chrome Helper (Plugin)	OBSDAL: Attempting connection
default	11:15:51.952563-0600	Google Chrome Helper (Plugin)	OBSDAL: -[MachClient connectToServer]
default	11:15:52.944976-0600	Google Chrome Helper (Plugin)	OBSDAL: Attempting connection
default	11:15:52.945442-0600	Google Chrome Helper (Plugin)	OBSDAL: -[MachClient connectToServer]
default	11:15:53.943279-0600	Google Chrome Helper (Plugin)	OBSDAL: Attempting connection
default	11:15:53.943569-0600	Google Chrome Helper (Plugin)	OBSDAL: -[MachClient connectToServer]
default	11:15:54.943311-0600	Google Chrome Helper (Plugin)	OBSDAL: Attempting connection
default	11:15:54.943608-0600	Google Chrome Helper (Plugin)	OBSDAL: -[MachClient connectToServer]
default	11:15:56.743216-0600	obs	OBSDAL: HardwarePlugIn_Teardown self=0x2814e590

The plugin was there when I checked at /Library/CoreMediaIO/Plug-Ins/DAL

**Comment by croesike** [comment]
Same for me even after Updating and restart the Mac I get this message
`/Library/CoreMediaIO/Plug-Ins/DAL/obs-mac-virtualcam.plugin/Contents/MacOS/obs-mac-virtualcam: code signature in (/Library/CoreMediaIO/Plug-Ins/DAL/obs-mac-virtualcam.plugin/Contents/MacOS/obs-mac-virtualcam) not valid for use in process using Library Validation: mapping process and mapped file (non-platform) have different Team IDs`

**Comment by willjstevens** [comment]
I am having a similar issue - the virtual camera does not come up in other applications. These include Zoom and AWS Chime. 

I removed the old plugin file, installed the package as instructed, restarted my Mac, started OBS and started the Virtual Camera through the Tools menu, restarted Zoom and Chime. But nothing showing up in the other apps. 

**Environment**
macOS Catalina 10.15.4
-Discord 0.0.257
Virtualcam version 1.1.0
OBS version 25.0.8

**Comment by johnboiles** [comment]
Uh oh, looks like Discord might have also removed support for virtual cameras via CoreMediaIO DAL :/ Can y'all confirm that other virtual cameras (like Snapchat's Snap Camera) also don't show up in Discord.

**Comment by gxalpha** [comment]
Can't confirm that it doesn't work with Discord, works fine for me (OBS 25.0.8, VCam 1.0.0 and Discord 0.0.257 (Stable 60516 (f6ec4b5)).)

**Comment by el-hoshino** [comment]
Neither SnapCamera nor obs show up on my environment 😢 

My environment:

Discord: 0.0.257 (0.0.257)
macOS: 10.15.4（19E287）

**Comment by The19th** [comment]
For reference, my Discord is showing functional virtual cam input from both virtualcam and snap camera.  I haven't come across any code signature issues.

macOS 10.15.4 (19E287)
OBS 25.0.8
obs-mac-virtualcam 1.1.0
Snap 1.7.1
Discord 0.0.257

![Screen Shot 2020-05-22 at 8 51 01 AM](https://user-images.githubusercontent.com/62362114/82685959-e4791280-9c09-11ea-8989-af4dedfde59d.png)

**Comment by bgilmore** [comment]
Library validation performed by the macOS Hardened Runtime is preventing Discord from loading the OBS Virtual Camera (and Snap Camera) libraries. Luckily, we can turn this off by resigning the application with the following entitlement: https://developer.apple.com/documentation/bundleresources/entitlements/com_apple_security_cs_disable-library-validation

The relevant application bundle is `/Applications/Discord.app/Contents/Frameworks/Discord Helper (Renderer).app`

```bash
# Extract the default entitlements
codesign -d --entitlements /tmp/entitlements.xml /Applications/Discord.app/Contents/Frameworks/Discord\ Helper\ \(Renderer\).app

# Editing /tmp/entitlements.xml:
#  - delete the binary garbage from the beginning of the file
#  - add com.apple.security.cs.disable-library-validation to the entitlements

# Resign the helper using the new entitlements and your own key
codesign -f -s "<Developer ID>" --entitlements /tmp/entitlements.xml /Applications/Discord.app/Contents/Frameworks/Discord\ Helper\ \(Renderer\).app
```

This procedure is pretty awful since it's going to break if/when Discord pushes updated helper binaries. Also it assumes you have a developer certificate (or a local self-signed codesigning cert). This is a temporary workaround at best.

**Comment by el-hoshino** [comment]
@bgilmore Worked for me! Thanks very much 🎉 

p.s. For people don't know how to resign the helper, you can check this stackoverflow thread:
https://stackoverflow.com/questions/36888535/how-do-i-resign-app-with-entitlements

**Comment by djkevinadam** [comment]
Hi! I have the same problem,I've been trying to do the workaround but I think I don't really understand how to do it... what should I put to my terminal? also where does the "<Developer ID>" came from? thanks in advice!

**Comment by el-hoshino** [comment]
@djkevinadam If you've already joined the Apple Developer Program and have been developing apps for macOS/iOS/watchOS/tvOS with Xcode, you should be able to find your Developer ID info from keychain:
<img width="996" alt="スクリーンショット 2020-05-31 10 12 02" src="https://user-images.githubusercontent.com/3942121/83342218-9362d000-a327-11ea-9760-fcda2951fce9.png">
(I have multiple developer certificates because I have my personal ADP certificates and my company's certificates)

If not, I haven't tested it yet but hopefully just removing the codesign maybe is also useful:
https://github.com/johnboiles/obs-mac-virtualcam/wiki/Compatibility#apps-dont-allow-dal-plugins

**Comment by timopagana** [comment]
I've fixed this problem by just removing the signature for the "Helper (Renderer).app". In my case, I had to remove it for Discord and Skype. The virtual Cam stopped working for Skype one day without an update or whatever notable happened.

`codesign --remove-signature "/Applications/Discord.app/Contents/Frameworks/Discord Helper (Renderer).app"`

`codesign --remove-signature "/Applications/Skype.app/Contents/Frameworks/Skype Helper (Renderer).app"`

macOS 10.15.4 (19E287)
Discord 0.0.257 (0.0.257)
Skype 8.60.0.76
OBS 25.0.8
obs-mac-virtualcam 1.1

**Comment by djkevinadam** [comment]
> @djkevinadam If you've already joined the Apple Developer Program and have been developing apps for macOS/iOS/watchOS/tvOS with Xcode, you should be able to find your Developer ID info from keychain:
> <img alt="スクリーンショット 2020-05-31 10 20 49" width="996" src="https://user-images.githubusercontent.com/3942121/83342291-a629d480-a328-11ea-8daa-59153543add5.png">
> (I have multiple developer certificates because I have my personal ADP certificates and my company's ADP/ADEP certificates)
> 
> If not, I haven't tested it yet but hopefully just removing the codesign maybe is also useful:
> https://github.com/johnboiles/obs-mac-virtualcam/wiki/Compatibility#apps-dont-allow-dal-plugins

Alright  Thank you!!!

but I found out this works  for me as well!

> I've fixed this problem by just removing the signature for the "Helper (Renderer).app". In my case, I had to remove it for Discord and Skype. The virtual Cam stopped working for Skype one day without an update or whatever notable happened.
> 
> `codesign --remove-signature "/Applications/Discord.app/Contents/Frameworks/Discord Helper (Renderer).app"`
> 
> `codesign --remove-signature "/Applications/Skype.app/Contents/Frameworks/Skype Helper (Renderer).app"`
> 
> macOS 10.15.4 (19E287)
> Discord 0.0.257 (0.0.257)
> Skype 8.60.0.76
> OBS 25.0.8
> obs-mac-virtualcam 1.1

thanks everyone!
