### ISSUE TITLE
[BUG] .pkg installer not overwriting existing plugin

### ISSUE THREAD

**Issue by johnboiles** [johnboiles/obs-mac-virtualcam#128]
**Describe the bug**
I noticed today on my system when I looked at the version number of the plugin on my system it was still the old one.

```
cat /Library/CoreMediaIO/Plug-Ins/DAL/obs-mac-virtualcam.plugin/Contents/Info.plist
```
contained
```
	<key>CFBundleShortVersionString</key>
	<string>7.0</string>
	<key>CFBundleVersion</key>
	<string>7</string>
```
So I ran the 1.1.0 pkg and checked again and saw the same thing. Then I deleted the plugin entirely `sudo rm -rf /Library/CoreMediaIO/Plug-Ins/DAL/obs-mac-virtualcam.plugin` and ran the installer again. And now it shows the correct thing.

```cat /Library/CoreMediaIO/Plug-Ins/DAL/obs-mac-virtualcam.plugin/Contents/Info.plist | grep -a3 CFBundleShortVersionString```
Shows me
```
	<string>OBS Virtual Camera</string>
	<key>CFBundlePackageType</key>
	<string>BNDL</string>
	<key>CFBundleShortVersionString</key>
	<string>1.1.0</string>
	<key>CFBundleVersion</key>
	<string>1.1.0</string>
```

This might be at the root of a lot of the issues we've seen. If people on old OS's haven't been able to properly upgrade by running the new .pkg. Not sure why this would be.

**To Reproduce**
Need to try to reproduce

**Expected behavior**
The .pkg installer should overwrite any existing installations of the plugin.

**Desktop (please complete the following information):**
 - OS version: macOS Catalina 10.15.4
 - Virtualcam version: 1.1.0

**Comment by johnboiles** [comment]
I would love some help verifying / validating this. Maybe just try to install 1.0.0 then installing 1.1.0 running the commands above to see if you can reproduce this.

**Comment by johnboiles** [comment]
I do see this in the Console.app but it's not that descriptive `Sandbox: 5 duplicate reports for installd deny(1) file-read-data /Users/jboiles/Downloads/obs-mac-virtualcam-0e62cec-v1.1.0.pkg`

**Comment by johnboiles** [comment]
I think maybe pkg installers look at the version and don't overwrite bundles if the version in the Info.plist is older. Which is surprising, but kinda makes sense. Seeing `BundleIsVersionChecked` [here](https://www.manpagez.com/man/1/pkgbuild/).

**Comment by johnboiles** [comment]
I just tried to install 1.0.0 again and it installed fine (it erroneously had a version number of 7.0). But then tried to install 1.1.0 again and it didn't overwrite things. So I think it's either:
* pkg installers don't like to overwrite things when newer versions are installed

OR

* the 1.1.0 installer is broken somehow

**Comment by brinsche** [comment]
I think it might be 1.

>Important: For macOS apps, build numbers must monotonically increase even across different versions. In other words, for macOS apps you cannot use the same build numbers again in different release trains. iOS apps have no such restriction and you can re-use the same build numbers again in different release trains.

from: https://developer.apple.com/library/archive/technotes/tn2420/_index.html#//apple_ref/doc/uid/DTS40016603-CH1-HOW_THESE_NUMBERS_WORK_TOGETHER

**Comment by johnboiles** [comment]
Thanks for the info @brinsche that indeed looks like what's happening. For 1.1.0 I set both values to `1.1.0`. So I think probably for future versions it will just work. But I wonder if I should try to set `BundleIsVersionChecked = false` for our next build so that it fixes the issue for anyone who installed `1.0.0`

**Comment by denwald** [comment]
>     1. pkg installers don't like to overwrite things when newer versions are installed

I can confirm this. My info.plist showed the following after installing 1.1 over 1.0 a couple of days ago. It did work by the way. Even though I apparently was running 1.0 DAL plug-in with the newer obs-virtualcam-so.

`
<key>CFBundleShortVersionString</key>
<string>7.0</string>
<key>CFBundleVersion</key>
<string>7</string>
`

After removing the plugin and repeating the install I have now the following:

`<key>CFBundleShortVersionString</key>
<string>1.1.0</string>
<key>CFBundleVersion</key>
<string>1.1.0</string>`

**Comment by johnboiles** [comment]
Thanks for the info @denwald 

It's not totally clear to me how to incorporate the `BundleIsVersionChecked` property into my package build otherwise i would. If anyone wants to take a look at that it would be much appreciated.

**Comment by johnboiles** [comment]
There's no more pkg installer now that everything is in OBS Studio. OBS has a mechanism for installing the plugin after OBS is installed. 🎉
