### ISSUE TITLE
[Feature Request] Put this in Homebrew Cask

### ISSUE THREAD

**Issue by johnboiles** [johnboiles/obs-mac-virtualcam#129]
It would be great to make this into a Homebrew formula, so people could install it using `brew cask install obs-mac-virtualcam`

More details
https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md

**Comment by dodgepong** [comment]
If this gets merged into the OBS master branch, would its presence in homebrew make users more confused? What happens if they install this when they already have it from a master OBS release?

**Comment by johnboiles** [comment]
Yeah that's a good point. I forget where the discussion left off: are we open to merging this in as macOS only for now and the Linux / Windows implementations can come later?

**Comment by dodgepong** [comment]
There's some work being done on the Windows side right now that should set the stage for you better. Keep your eyes peeled for a Windows implementation, which will give you some things that you need in order to fulfill some of the things that are missing in #105.

**Comment by johnboiles** [comment]
Oh that's awesome. Then yeah if the opportunity to bring this all together is on the horizon let's close this
