### ISSUE TITLE
NV12 texture support not available

### ISSUE THREAD

**Issue by tbartel** [johnboiles/obs-mac-virtualcam#13]
Running High Sierra on a mid-2010 iMac with an ATI Radeon HD 5670. Everything compiles correctly, but when using "Tools > Start Virtual Camera", OBS crashes and the following output is logged: 
```
info: video settings reset:
	base resolution:   1280x720
	output resolution: 1280x720
	downscale filter:  Bicubic
	fps:               30/1
	format:            NV12
	YUV mode:          601/Partial
info: NV12 texture support not available
Segmentation fault: 11
```

**Comment by gxalpha** [comment]
Could you give the full log? To me it appears that missing NV12 texture support is not the problem as for me it says that all the time when starting up OBS (After loading OpenGL and before trying to load translation modules), and it isn't an issue for me (For me it doesn't say anything about segmentation fault tho, so maybe that is the issue). 
Did it log something else?
