### ISSUE TITLE
[Feature Request] Multiple test card resolutions

### ISSUE THREAD

**Issue by robinhoodis** [johnboiles/obs-mac-virtualcam#130]
the default resolution is hard coded at 720p.
I would like to output the virtual camera at 1080p as an option.

**Comment by johnboiles** [comment]
720p is only hardcoded for the test card. If you're sending frames from OBS you can send other resolutions.

Not sure how/if we could save state in the DAL plugin but if there's a way we could potentially set the test card to the last resolution that was sent

**Comment by gxalpha** [comment]
@robinhoodis make sure to install the newest version from the [releases](https://github.com/johnboiles/obs-mac-virtualcam/releases) section. The virtual camera will output at your scaled resolution.

**Comment by johnboiles** [comment]
The first step to adding multiple test card resolutions would be to find a way to save local state from the DAL plugin. Some things to try:

* Maybe `NSUserDefaults` can work from the DAL plugin?
* Perhaps there's a way to write a file to disk?

After that we'd need to make sure the test card can render in multiple resolutions. I think it's probably not too far off since it's already drawn from code (thanks PaintCode!), but we might need to do things like hide the text if the test card gets too small.

**Comment by gxalpha** [comment]
I like the idea of writing a file to a disk.
I think we can use `/Users/username/Library/Application Support/obs-studio/plugin_config/obs-mac-virtualcam` as a folder

**Comment by gxalpha** [comment]
While working on this, I noticed that QuickTime Player is sandboxed which results in not getting the user home directory by calling [NSHomeDirectory()](https://developer.apple.com/documentation/foundation/1413045-nshomedirectory?language=objc). Works fine in Chrome which apparently is not sandboxed.
Does someone know how to bypass this?

**Comment by johnboiles** [comment]
Yeah I need to change the drawing code to support scaling. I can do that with PaintCode I think.

I don't think we can escape the sand is (which is kinda the point of the sandbox!). Can you also try NSUserDefaults to see if you can store and retrieve a key across apps?

**Comment by gxalpha** [comment]
https://developer.apple.com/documentation/foundation/nsuserdefaults
<img width="765" alt="Bildschirmfoto 2020-05-27 um 15 51 36" src="https://user-images.githubusercontent.com/59806498/83028634-fdcaf600-a031-11ea-8b42-e9933afce7f5.png">
Seems like that wouldn't change anything, right?
I could try though

**Comment by johnboiles** [comment]
Yeah maybe not, so it might be the same functionality. But I think it'd be at least a bit simpler than writing to disk.

If we automatically set the test card to the most recent resolution sent from OBS, then at least the resolution will be sent automatically to any apps that are using the DAL plugin.

**Comment by gxalpha** [comment]
Done in #149
