### ISSUE TITLE
[Feature Request] Ability to start virtual camera upon OBS start

### ISSUE THREAD

**Issue by TheLocehiliosan** [johnboiles/obs-mac-virtualcam#132]
**Is your feature request related to a problem? Please describe.**
Starting the camera is currently a two step process.

- Start OBS
- Use the mouse to select "Start Virtual Camera" from the OBS menu

This is slow, clunky, and requires touching the mouse.

**Describe the solution you'd like**
Two possibilities could help smooth this out:
- Option to start virtual camera upon OBS start
- Ability to start/stop the virtual camera via a hotkey

**Describe alternatives you've considered (if applicable)**
I guess if there's no way to handle this, I'll probably look into some kind of automation using Hammerspoon.

**Comment by TheLocehiliosan** [comment]
In case anyone else is looking to do the same, here's the Hammerspoon code I was just able to use to trigger this.

```
hs.appfinder.appFromName("OBS"):selectMenuItem("Start Virtual Camera")
```

**Comment by johnboiles** [comment]
An 'autostart' checkbox is definitely something we'll need to have at some point when we want to merge this into OBS, since it's part of the OBS virtual camera RFC. See #105

I wonder what we'd need to do to register a hot key. That seems like something we should be able to do pretty easily.

**Comment by dodgepong** [comment]
A hotkey to start/stop virtual cam output is a good diea, and probably should have been part of the RFC. Fortunately it's pretty easy to add, I believe.

**Comment by WizardCM** [comment]
Now that the virtual camera Windows PR has been merged into OBS, it'd be recommended to "respect" the launch parameter specifying that the virtual camera should launch with OBS.

**Comment by jenniferhuang** [comment]
> hs.appfinder.appFromName("OBS"):selectMenuItem("Start Virtual Camera")

I can execute this command on my Mac, it occurs error:   -bash: syntax error near unexpected token `"OBS"'

**Comment by jenniferhuang** [comment]
is it available now? or do  we have other alternatives ways to start OBS with virtual camera is on

**Comment by gxalpha** [comment]
https://github.com/johnboiles/obs-mac-virtualcam/issues/53#issuecomment-656543761

**Comment by iamkirkbater** [comment]
I just created a basic `Automator Application` with Applescript that will start OBS, start the virtual camera, and then minimize the window.

https://gist.github.com/iamkirkbater/ba6278d0ac6d695cb8c6c5fc309ba210

**Comment by ilya757** [comment]
So interesting bug that I'm trying to figure out - looks like the auto start works, however if you have browser windows that you are capturing and you are starting those via Batch Script previously, for some reason when OBS autostarts as start-process the windows don't capture (In this case, it's a browser window - chrome). 

I have to CLOSE the chrome browser windows, and re-open then manually. That's kind of a problem for me right now as I'm trying to automate OBS to re-start with previous configuration settings if the SERVER/PC crashes.

**Comment by johnboiles** [comment]
If we do this it will be in the core of OBS now. Closing the issue here.
