### ISSUE TITLE
[BUG] MacOS Catalina(10.15.4) can't display distorted images properly

### ISSUE THREAD

**Issue by adachishohei** [johnboiles/obs-mac-virtualcam#134]
**Describe the bug**

When using ZOOM with obs-mac-virtualcam, the image is distorted and displayed.
Other tools have the same symptoms.
For example, Google Meets.

**To Reproduce**

1. Start OBS
2. Click on 'tool' → 'Start Virtual Camera'
3. Start Zoom
4. Select Video → OBS Virtual Camera

**Expected behavior**

The image is displayed without distortion.

**Screenshots**

<img width="1211" alt="スクリーンショット 2020-05-20 12 43 45" src="https://user-images.githubusercontent.com/41992406/82402815-4fa2d780-9a98-11ea-8aaf-b6bc56d5c6cb.png">

**Desktop (please complete the following information):**
 - OS version: macOS Catalina 10.15.4
 - Application: Zoom 5.0.2
 - Virtualcam version: 1.1.0 and 1.0.0
 - OBS version: 25.0.8

**Comment by gxalpha** [comment]
Which resolution are you using? We seem to have problems with some "unusual" ones

**Comment by adachishohei** [comment]
Is that the resolution of the image?
If so, it's here.
Canvas, "1792 * 1120
The scaling is "1194 * 746".

<img width="962" alt="スクリーンショット 2020-05-20 16 47 47" src="https://user-images.githubusercontent.com/41992406/82419907-fa77bd80-9ab9-11ea-8a81-746139e49253.png">

**Comment by adachishohei** [comment]
I'm sorry.
There seems to have been a problem with the canvas and scaling settings.
If you set each of them to the same value, the output was fine!

**Comment by gxalpha** [comment]
Ok good 👍 
Could you describe what you did?
Maybe that helps us find out what the problem is

**Comment by adachishohei** [comment]
OK. 👍 
The following steps were taken to resolve the problem

1. Select Prefarences → Video.
2 Set the resolution of the canvas to "1920 * 1080".
3. Set the scaling resolution to "1920 * 1080".
4. restart OBS
5. Start OBS, then "tool" → "Start virtual camera".

Is there anything else you want to know?

**Comment by johnboiles** [comment]
Fascinating! I wonder if I'm telling the plugin the output resolution of OBS but not the scaled resolution. There might be a simple fix here.
