### ISSUE TITLE
Image coming through distorted on non-standard resolutions

### ISSUE THREAD

**Issue by mchety** [johnboiles/obs-mac-virtualcam#135]
The plug-in had been working fine until recently the virtual camera feed was very distorted and pixilated

**To Reproduce**

1. Open OBS
2. Start the Virtual Webcam
3. Open google meets and start a meeting

**Expected behavior**
That the feed would come in without being pixelated

**Desktop (please complete the following information):**
 -Catalina 10.15.4
 - Chrome
 - 1.1.0
 - OBS version 25.0.8

**Additional context**
It had been working perfectly the other day, I also tried uninstalling and re-installing.

ScreenShot:

<img width="1120" alt="Screen Shot 2020-05-20 at 11 14 44 AM" src="https://user-images.githubusercontent.com/65556297/82476916-f0d76100-9a8b-11ea-8908-e1e277a2b920.png">

**Comment by johnboiles** [comment]
What resolution are you using in OBS?

**Comment by mchety** [comment]
720x1280

**Comment by johnboiles** [comment]
Interseting! Portrait? Is that the resolution for both the canvas and scaled resolutions?

![image](https://user-images.githubusercontent.com/218876/82477767-c59d4380-9a84-11ea-9636-1f159899ba3a.png)

**Comment by mchety** [comment]
Sorry, it's actually 1280 by 720, and that is for the base canvas, the output is 424x240.

![Screen Shot 2020-05-20 at 11 32 16 AM](https://user-images.githubusercontent.com/65556297/82478060-90492380-9a8d-11ea-8c88-62ba6d1a6f8d.png)

**Comment by mchety** [comment]
It is actually working now after setting both the base and output to 16x9

**Comment by gxalpha** [comment]
We should probably add a "Distorted aspect ratio" and "Unusual resolution" warning.

Might send a proposal tomorrow.

**Comment by johnboiles** [comment]
Awesome! Thank you!

It's also not clear to me what resolutions are supported by the dal plugins. I originally had thought it was something about the mismatch between canvas and scaled resolutions but that seems like not the case. If I set both to 424x240 then things still show as garbled in QuickTime.

![image](https://user-images.githubusercontent.com/218876/82502056-30617580-9aab-11ea-9b20-335d24306d75.png)

Maybe things need to be multiples of 16? Would be good to try to further understand what is going on here.

**Comment by johnboiles** [comment]
Reopening to track this issue. We should either fix this (if possible) or provide a warning

**Comment by rydalch** [comment]
I ran into this issues as well. This thread saved me!

**Comment by therealdanbient** [comment]
Sorry I just posted about this bug.  I am having the same issue going into Zoom.  They released a new version that allows for virtual cams again.  But I can't get it to not be diagonal...

**Comment by gxalpha** [comment]
This is probably a problem with your resolution, only certain resolutions seem to work. 
Could you try setting both resolutions to 1280x720?

Also this should be addressed with #138, kinda.

**Comment by johnboiles** [comment]
I just did some quick tests with some random resolutions and it seems to me, that as long as both dimensions are divisible by 16, it works fine.

**Comment by dodgepong** [comment]
What about divisible by 8? Or is 16 the smallest increment that produces usable video?

**Comment by johnboiles** [comment]
I haven't done super thorough tests (I have some documented in #138) but the resolution I had above (424x240) is divisible by 8 (but not 16) and does not work.

I haven't found a resolution that's divisible by 16 that _doesn't_ work, but I haven't tested super thoroughly.

It's totally just a hypothesis at this point. Possible there's some other pattern this is adhering to.

**Comment by johnboiles** [comment]
[This](https://stackoverflow.com/questions/46879895/byte-per-row-is-wrong-when-creating-a-cvpixelbuffer-with-width-multiple-of-90) is interesting, though it mentions 16-byte alignment (which would be 8 pixels). Maybe I can log `CVPixelBufferGetBytesPerRowOfPlane` and see if that gives me any clues.

**Comment by johnboiles** [comment]
Going to try this out and see if it gives me any hints
```diff
diff --git a/src/dal-plugin/CMSampleBufferUtils.mm b/src/dal-plugin/CMSampleBufferUtils.mm
index 4eb33b26..a301b386 100644
--- a/src/dal-plugin/CMSampleBufferUtils.mm
+++ b/src/dal-plugin/CMSampleBufferUtils.mm
@@ -25,6 +25,11 @@ OSStatus CMSampleBufferCreateFromData(NSSize size, CMSampleTimingInfo timingInfo
         return err;
     }

+    size_t dstRowbytes = CVPixelBufferGetBytesPerRowOfPlane(pixelBuffer, 0);
+    if (dstRowbytes != (size.width * 2)) {
+        ELog(@"CVPixelBufferGetBytesPerRowOfPlane gives a different number of bytes per row than expected (expected:%d returned:%d", (int)(size.width * 2), (int)dstRowbytes);
+    }
+
     // Generate the video format description from that pixel buffer
     CMFormatDescriptionRef format;
     err = CMVideoFormatDescriptionCreateForImageBuffer(NULL, pixelBuffer, &format);
```

**Comment by johnboiles** [comment]
Ok! That gave me `OBSDAL: CVPixelBufferGetBytesPerRowOfPlane gives a different number of bytes per row than expected (expected:848 returned:864`

So it looks like CVPixelBuffer creates certain width buffers.

**Comment by johnboiles** [comment]
Ok I think I have a fix. I'd love some help testing if y'all could download artifacts from that build and test it out. https://github.com/johnboiles/obs-mac-virtualcam/runs/711046656

**Comment by johnboiles** [comment]
Ok went ahead and created a new release with this fix. Seems to fix the issue for @gxalpha and I and I'm pretty confident it won't break anything for more normal resolutions. Can y'all go try it out?

**Comment by wesalvaro** [comment]
Looks like this is still an issue #160
