### ISSUE TITLE
[BUG] Does not work on program that require code signing

### ISSUE THREAD

**Issue by Enteerman** [johnboiles/obs-mac-virtualcam#136]
**Describe the bug**
Using Zoom(The program, not from browser) produces the following error in Console.app:
`Error loading /Library/CoreMediaIO/Plug-Ins/DAL/obs-mac-virtualcam.plugin/Contents/MacOS/obs-mac-virtualcam:  dlopen(/Library/CoreMediaIO/Plug-Ins/DAL/obs-mac-virtualcam.plugin/Contents/MacOS/obs-mac-virtualcam, 0x0106): code signature in (/Library/CoreMediaIO/Plug-Ins/DAL/obs-mac-virtualcam.plugin/Contents/MacOS/obs-mac-virtualcam) not valid for use in process: mapping process is a platform binary, but mapped file is not`

**To Reproduce**
1. Install OBS mac virtual cam
2. Open Console.app
3. Open zoom program
4. See error on console

**Desktop (please complete the following information):**
 - OS version: macOS Mojave 10.14.5
 - Application: Zoom
 - Virtualcam version: 1.1.0
 - OBS version: 25.0.8

**Additional context**

**Comment by gxalpha** [comment]
Have you seen [this](https://github.com/johnboiles/obs-mac-virtualcam/wiki/Compatibility#apps-dont-allow-dal-plugins)?

**Comment by Enteerman** [comment]
oh thanks
