### ISSUE TITLE
[Feature Request] Use C++17

### ISSUE THREAD

**Issue by gxalpha** [johnboiles/obs-mac-virtualcam#137]
**Is your feature request related to a problem? Please describe.**
I can't use std::gcd due to the c++-version being gnu++14.

**Describe the solution you'd like**
I'd like to change the version to gnu++17, does anything speak against that?

**Describe alternatives you've considered (if applicable)**
I could also just write a function that does what I need, though this would add additional code that wouldn't be necessary otherwise.

**Comment by gxalpha** [comment]
Ok I can't even get it to work if I change everything in all CMakeLists as well as Xcode C++ Language dialect (probably because I missed something), so I'm just gonna write my own code, should be changeable later on.

**Comment by johnboiles** [comment]
Interesting!! What errors did you get? There might be some weirdness related to ObjectiveC++ And newer C standards

What C standard does OBS use? We should try to stick close-ish to that I think.
