### ISSUE TITLE
 [BUG]

### ISSUE THREAD

**Issue by OlogyCrew** [johnboiles/obs-mac-virtualcam#139]
**Describe the bug**

**To Reproduce**
Has anyone had a problem of watching videos on line after installing this plugin? It wiped out my audio settings and now i can't view any video on line. Keeps saying "if your video doesn't start soon try restarting your device" ?I have never had any issue of playing videos on FaceBook or YouTube before.. any suggestions would be greatly appreciated. Thanks.. Im trying not to freak out too much...HELP!!
**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS version: [e.g. macOS Catalina 10.15.4]
 - Application: [e.g. Chrome, Zoom]
 - Virtualcam version: [e.g. 1.1.0]
 - OBS version: [e.g. 25.0.8]

**Additional context**

**Comment by OlogyCrew** [comment]
OS version: High Sierra 10.13.6
App: Chrome
OBS: 25.0.8 (64) bit

**Comment by gxalpha** [comment]
This seems new to me, never had problems with this.
Have you tried restarting your device?

**Comment by OlogyCrew** [comment]
I have tried everything i can think of. I even uninstalled OBS reinstalled
it, reconfigured the audio, I don't know why it removed all my audio
config. when i installed the Virtual cam.. Sound is back, I removed the
plugins. Still not working. Im at a lost right now as to what to try.
Thanks for your reply.

**Comment by gxalpha** [comment]
Are you sure it is the virtualcam? Or have you installed other apps that may cause the issue?
I would suggest reverting anything you've done to your computer shortly before the issue first started appearing.

**Comment by OlogyCrew** [comment]
Heys guys, They issue was bit rate of the audio devices one was at 24 and
NDI is at 32 bit. I had to uninstall NDI until i get a 32bit audio
interface. I'm using a Focusrite Saffire 6 and it only goes up to 24 bit.
Videos and sound plays again. Thanks

**Comment by gxalpha** [comment]
Nice!
No problem :)
