### ISSUE TITLE
[Feature Request] Support for Audio

### ISSUE THREAD

**Issue by thedug** [johnboiles/obs-mac-virtualcam#140]
**Is your feature request related to a problem? Please describe.**

It would be awesome if you supported audio as well. 
Right now I have to use zoom's share desktop audio feature to get audio into zoom.
It would be nice to have it sync'd with the video and be able to live mix it in obs studio.

**Describe the solution you'd like**
If I could pick a channel, or even just get channel 1. I would go into Zoom and select the obs output as a virtual input, just like I do for video. 

**Describe alternatives you've considered (if applicable)**
I've tried NDI output from OBS but it has sync issues. 

**Additional context**

**Comment by gxalpha** [comment]
https://github.com/obsproject/rfcs/blob/master/accepted/0015-virtual-camera-support.md#Drawbacks
> The most obvious omission from this RFC is the lack of virtual audio output in addition to virtual camera output. However, though the features are logically closely related, they are unfortunately vastly different technically speaking.
