### ISSUE TITLE
QuickTime recording stops itself with warning

### ISSUE THREAD

**Issue by dfiorijr** [johnboiles/obs-mac-virtualcam#143]
The virtual camera works great - except one thing that was a little annoying when 
I was using QuickTime to troubleshoot audio routing schemes with OBS and evaluate different bluetooth and usb microphones and their relative delays in preparation for using Zoom.

QuickTime and VirtualCam worked great for monitoring, but when I tried to record a trial with QuickTime's record video feature, QuickTime immediately stoped itself. While it did capture two frames as a movie, I could not get it to properly record a movie when using the OBS Virtual Camera Device. I resorted to CAMTASIA 3's built in recording feature instead, and that worked very well with VirtualCam and so I was able to do everything I needed to do after all. 

**To Reproduce**
1. Launch QuickTime while the virtual camera is running
2. When window appears to select a file to play, press Done to avoid playing anything.
3. Go to the Pull Down Menu, pull down the File menu, and select New Movie Recording.
4. Move cursor to video window and pull down source menu immediately adjacent to the record button dialog box that appears. That is done by clicking on the caron – the down pointing arrow head – to the immediate right of the round record button which is the button with the red circle inside.
5. Select the OBS Virtual Camera Device
6. Wait until the OBS Virtual Camera video image appears. I find that if I have just changed the resolution of the OBS Video it might be necessary to close OBS are relaunch it to get the OBS Virtual Camera to work.
7. Press the record button. 
8. Notice that you get a warning dialog box that announces that the recording has stopped and prompts with OK button.
9. Press the OK button. Notice that the first video frame appears with a dialog box with a play button. Pressing Play will show a video comprised of two fully formed frames; one frame the beginning frame and the 2nd frame the last frame.

**Expected behavior**
Recording should proceed until the user stops it by pressing the same button that started it. In contrast, this is the correct behavior, when, for example, the FaceTime HD Camera (Built-In) is selected .

**Desktop (please complete the following information):**
 - OS version: High Sierra 10.13.6]
 - Application: QuickTIme 10.4
 - Virtualcam version:  1.1.0
 - OBS version: 25.0.8

**Additional context**
1. There is no problem recording with OBS.
2. There is no problem recording with the CAMTASIA 3 intrinsic recording facility.
3. The Virtual Camera works very well with the latest version of Zoom.

**Comment by gxalpha** [comment]
This is known and should be fixed with the next release, alternativly you can also try to compile it yourself (the DAL part is the important one).
Thanks for reporting though!

**Comment by johnboiles** [comment]
Yep i'll go ahead and push a new release with my fix for this. I had hoped to fix a few more things before cutting a release but I'm short on time this week.

**Comment by johnboiles** [comment]
Check out the [latest release](https://github.com/johnboiles/obs-mac-virtualcam/releases/tag/v1.1.1) and please reopen if that doesn't fix it for you.

**Comment by gxalpha** [comment]
Has the version number been changed?

**Comment by johnboiles** [comment]
:) thanks for checking. I remembered this time
