### ISSUE TITLE
[BUG]Virtualcam is not working with Zoom 5.0.4

### ISSUE THREAD

**Issue by alaghi000** [johnboiles/obs-mac-virtualcam#145]
**Describe the bug**
Zoom version 5.0.4 is now working with virtual cam devices like Snap Camera, but obs-mac-virtualcam is not working on zoom.

**To Reproduce**
-Start VirtualCam on OBS
-Open Zoom
-Start a meeting
-Select camera input
- VirtualCam is not available on Zoom to select

**Expected behavior**
VirtualCam should be available on Zoom

**Screenshots**

**Desktop (please complete the following information):**
 - OS version: macOS Catalina 10.15.4
 - Application: Zoom
 - Virtualcam version: 1.1.1
 - OBS version: 25.0.8

**Additional context**
It works on zoom disabling code signature by the command in terminal:
sudo codesign --remove-signature /Applications/zoom.us.app/

**Comment by johnboiles** [comment]
Zoom has a whitelist of virtual camera plugins they allow. See this [comment](https://github.com/johnboiles/obs-mac-virtualcam/issues/4#issuecomment-633700264) for the list.

Please reach out to Zoom and ask them to allow this plugin! Perhaps if enough people ask, they will add it to their whitelist.
