### ISSUE TITLE
[BUG] Zoom not detecting virtualcam

### ISSUE THREAD

**Issue by smithkyle** [johnboiles/obs-mac-virtualcam#146]
**Describe the bug**
I have the virtualcam installed, and other apps like Quicktime pick it up and can use it, but Zoom does not detect it.

**To Reproduce**
1. Install virtualcam
2. Open OBS, turn virtualcam on
3. Open Zoom, check available video sources for virtualcam to no avail.

**Expected behavior**
The virtualcam should show in the list of available camera sources. 

**Desktop (please complete the following information):**
 - OS version: MacOS 10.14.6
 - Application: Zoom v5.0.4
 - Virtualcam version: 1.1.2
 - OBS version: 25.0.8

**Additional context**
Zoom IS detecting third party cameras, because I installed SnapCam to test, and Zoom picks it up and uses it without issue. It just isn't detecing virtualcam

**Comment by smithkyle** [comment]
Just tried with Google Meet, and it DOES, indeed, see the obs virtualcam. So I'm not sure if it's a virtualcam issue or a Zoom issue. The fact that I was able to install SnapCam after I installed virtualcam, and Zoom picked that up without issue tells me its virtual cam. But while Zoom did not pick it up, Google Meet did, so it's at least being seen by some applications, just not all...

**Comment by smithkyle** [comment]
Bah sorry - I guess I missed #145 sorry :/

**Comment by johnboiles** [comment]
Yeah! Go tell Zoom to add my code signature to their whitelist! See also [this comment](https://github.com/johnboiles/obs-mac-virtualcam/issues/4#issuecomment-633700264) for their current whitelist.
