### ISSUE TITLE
Virtual Camera not shown in Zoom, FaceTime, Photo Booth -- but Google Meet

### ISSUE THREAD

**Issue by lsinger** [johnboiles/obs-mac-virtualcam#151]
These applications don't recognize the virtual camera: Zoom, FaceTime, Photo Booth

I therefore thought maybe it's not running or the install is broken or something else, but -- Google Meet, launched in Chrome, does see the camera and is able to use it as expected. 

Anything I could be doing wrong here? 

Desktop:

 - OS version: macOS Catalina 10.15.5
 - Application: Chrome 83.0.4103.61, Zoom 5.0.4 (the one where the re-enabled virtual camera support)
 - Virtualcam version: 1.1.2 (latest [from here](https://github.com/johnboiles/obs-mac-virtualcam/releases))
 - OBS version: 25.0.8

**Additional context**
Zoom is listed (again?) in the README so I'd hoped that the 5.0.4 Zoom release had resolved the issue of not being able to use the OBS virtual camera in Zoom.

**Comment by gxalpha** [comment]
See the wiki on more information about [compatibility](https://github.com/johnboiles/obs-mac-virtualcam/wiki/Compatibility).
Also see #4 for additional info about the current state of Zoom

**Comment by lsinger** [comment]
Thanks for your help and work on this @gxalpha, hadn’t seen that one!
