### ISSUE TITLE
[Feature Request] Make Test Card Localized

### ISSUE THREAD

**Issue by gxalpha** [johnboiles/obs-mac-virtualcam#154]
**Is your feature request related to a problem? Please describe.**
As @Dodgepong pointed out [here](https://github.com/johnboiles/obs-mac-virtualcam/issues/34#issuecomment-619184698), the card should be localizable.

**Describe the solution you'd like**
The test card text would need to be localizable.
The fact that it is being drawn from code both helps and makes it more difficult here. On the positive side, it wouldn't need a picture for every language. On the negative side, we'd need to manipulate what PaintCode has generated, and seeing that code that won't be exactly easy, but should be possible. The major difficulties with this would be
a) figuring out where the lines need to end with each language and finding out how big the rectangles would need to be and
b) sending information about which language should be used to the DAL plugin

**Describe alternatives you've considered (if applicable)**
Remove text entirely or leave it as is, but both would be unfavorable in my opinion

**Additional context**
Test Card Code is in TestCard.mm under DAL

**Comment by dodgepong** [comment]
Personally, my preference would be to remove text entirely, but I'm open to discussion about it if there are strong opposite opinions. I suppose it depends on who we want this function to serve more: the user using the program, or the people viewing the output.

**Comment by johnboiles** [comment]
I think the test card should primarily serve the user using the program. I think in most use cases, the user will see the test card in a preview window, then enable the virtual camera before joining a video conference (or otherwise using the virtual camera).

That said, I don't feel too strongly about having text on the test card. I like it overall, but it's a pain to localize. So I could be swayed to remove it.

**Comment by gxalpha** [comment]
<img width="615" alt="Bildschirmfoto 2020-06-19 um 16 50 46" src="https://user-images.githubusercontent.com/59806498/85145742-549ca780-b24d-11ea-933d-9cda0c45ce5e.png">
I guess there's more to do 😄 
At least if someone has the time and motivation, though we should wait for the final decision

**Comment by dodgepong** [comment]
At least, having a replaceable PNG on the Windows side is easy to do. I have no idea how feasible that is on Mac.

**Comment by gxalpha** [comment]
At the moment we're drawing the test card from code to make scaling easier so we'll need some changes, but there once was a png file and I think it wasn't that complicated

**Comment by dodgepong** [comment]
This is more the direction I would lean for the placeholder card

![virtualcam-placeholder](https://user-images.githubusercontent.com/838450/85190398-2091a880-b286-11ea-9e62-6eb1b1bd1bb3.png)

Or perhaps even without the camera icon, with just the OBS logo in the middle. For example, here's what Snap does with the Snap camera: 

![](https://cdn.discordapp.com/attachments/398528383266586627/723742868140851200/unknown.png)

**Comment by dodgepong** [comment]
Pull request here: https://github.com/obsproject/obs-studio/pull/3087

**Comment by iamkirkbater** [comment]
What would be the level of effort required to enable the user to add their own test card through OBS preferences instead of using the default one here or having to fork and rebuild?

**Comment by johnboiles** [comment]
Test card is gone now in the official OBS version (a simple image is rendered instead)
