### ISSUE TITLE
Where did v1.2.0 go?

### ISSUE THREAD

**Issue by solderjs** [johnboiles/obs-mac-virtualcam#156]
I just got an email about a v1.2.0 release, but I clicked the download link and... it does not exist! 

https://github.com/johnboiles/obs-mac-virtualcam/releases/tag/1.2.0

Whatever shall I do?

**Comment by gxalpha** [comment]
It went back to void.
Accidentally clicked "Release" on an unfinished draft.

**Comment by johnboiles** [comment]
v1.2.0 is up for real now!
