### ISSUE TITLE
[compatability]

### ISSUE THREAD

**Issue by carlobellini** [johnboiles/obs-mac-virtualcam#157]
Hi - thanks so much for this plugin. I just cant get OBS with virtual cam turned on to be recognised in the new Zoom version 5.0.4. Anyone else with issues/fixes?

**Comment by gxalpha** [comment]
https://github.com/johnboiles/obs-mac-virtualcam/wiki/Compatibility

**Comment by carlobellini** [comment]
Zoom says new version re-enables virtual cameras

https://support.zoom.us/hc/en-us/articles/360043996131-New-updates-for-May-24-2020

**Comment by johnboiles** [comment]
It's not fully true. They enabled a handful of specific virtual cameras. See #4 where someone posted the list.

**Comment by gxalpha** [comment]
Nt for every virtual camera at least.
Read from here if you are interested: https://github.com/johnboiles/obs-mac-virtualcam/issues/4#issuecomment-633700264

**Comment by carlobellini** [comment]
thx so much - greatly appreciated
