### ISSUE TITLE
[Support] OBS virtual cam in Zoom 5.0.4 (Mac)

### ISSUE THREAD

**Issue by boomarts** [johnboiles/obs-mac-virtualcam#158]
**Describe the issue**
The Zoom 5.0.4, which re-enabled the virtual camera, cannot detect the OBS virtual camera on MacOS Catalina 10.15. It can detect other virtual cam program. The Zoom version before being disabled can detect the OBS virtual cam. Anyone reports this issue? Thank you. 

**Desktop (please complete the following information):**
 - OBS version: 25.0.8
- Zoom 5.0.4
- MacOS Catalina 10.15

**Comment by johnboiles** [comment]
Zoom's release notes are misleading. They only enabled a handful of specific virtual cameras. Perhaps reach out to their support and ask them to add this plugin to their whitelist. See #4 for details.
