### ISSUE TITLE
[BUG] in OBS menu tools "start virtual cam" not exist

### ISSUE THREAD

**Issue by sambenito** [johnboiles/obs-mac-virtualcam#159]
**Describe the bug**
In mac Os High Sierra + OBS 24.0.6 + virtualcam 1.2.0 + zoom 5.0.3
after installing virtualcam and restart, the option "Start virtual cam" does not appears in menu Tools of OBS, in zoom just say "please start virtual cam"

**Comment by gxalpha** [comment]
Please try using OBS 25.0.8 (the newest version)
https://cdn-fastly.obsproject.com/downloads/obs-mac-25.0.8.dmg

**Comment by sambenito** [comment]
excelent! thanks
