### ISSUE TITLE
Menu items won't expand on click when obs starts.

### ISSUE THREAD

**Issue by amozoss** [johnboiles/obs-mac-virtualcam#16]
I followed the build instructions and ran `./obs`

When obs first loads, none of the menus are clickable. They don't expand when clicked on. However, if I switch to another program such as chrome (cmd-tab) and then come back to obs, the menus start working.

**Comment by gxalpha** [comment]
Can confirm, happens to me as well (since an on-off-button got added I think); I've kinda accepted it now but your right, thats a bug :D

**Comment by johnboiles** [comment]
I have seen the same issue. Have you tried removing this plugin (or making a clean build of obsproject/obs-studio) and seeing if the issue still happens? To remove the plugin, from the OBS clone directory, you can run:

    rm build/rundir/obs-plugins/obs-mac-virtualcam.so

**Comment by gxalpha** [comment]
Fresh build from OBS, happens there as well. Gonna write a bug report.

**Comment by johnboiles** [comment]
Thanks @gxalpha! Please link it here when you do.

Going to close this issue. Feel free to reopen @amozoss if you have reason to believe this issue is related to the `obs-mac-virtualcam` plugin.

**Comment by gxalpha** [comment]
@johnboiles here you go https://github.com/obsproject/obs-studio/issues/2678
