### ISSUE TITLE
[Support]Terminal keeps making a beeping noise. Is this normal?

### ISSUE THREAD

**Issue by tvhess77** [johnboiles/obs-mac-virtualcam#161]
_Please read the "Discussion / Support" section of the Readme first. Only open an issue if you don't get an answer on the OBS or someone tells you to._

**Describe the issue**
I have installed everything as directed.  OBS runs great. I can use the Virtual Camera in Zoom and Google Meet.  But the entire time it is running the terminal is making system error noises and bouncing in the tray.  

**To Reproduce**
1. Go to terminal
2. Click on start running
3. See error in terminal window and on the mac tray on the left

**Behavior**
The system error noise comes out of my computer, terminal looks like it's throwing an error.

**Screenshots**
Attaching a video to show

**Desktop (please complete the following information):**
 - OS version: macOS Catalina 10.15.5
 - Application (if applicable): [e.g. Chrome, Safari]
 - Virtualcam version: [e.g. 1.0.0] not sure how to check that
 - OBS version: 25.0.8
[obs terminal errors.mov.zip](https://github.com/johnboiles/obs-mac-virtualcam/files/4728252/obs.terminal.errors.mov.zip)

**Additional context**

**Comment by gxalpha** [comment]
Is there a reason why you start OBS from terminal?
If so, could you please post the outputs it makes? I can't really read them in the video.
Btw you can check the virtualcam version by inserting `cat /Library/CoreMediaIO/Plug-Ins/DAL/obs-mac-virtualcam.plugin/Contents/Info.plist | grep -a1 CFBundleVersion` into Terminal

**Comment by johnboiles** [comment]
If you install obs-mac-virtualcam from the [pkg release](https://github.com/johnboiles/obs-mac-virtualcam/releases) you can just download OBS 25.0.8 from the OBS website and double click it.
