### ISSUE TITLE
90 degrees rotation

### ISSUE THREAD

**Issue by luciano-mrprint** [johnboiles/obs-mac-virtualcam#163]
is it possible to rotate 90 degrees?

**Comment by Joel4763** [comment]
Well the camera, no. But you can rotate in OBS.

**Comment by johnboiles** [comment]
Yeah, I think it would make sense to just do the rotation in OBS. @luciano-mrprint any reason you don't want to just do it there?

**Comment by luciano-mrprint** [comment]
We need to broadcast simultaneously to YouTube and Instagram. We have done it by opening two instances of OBS. One normal 16x9 and the other 9x16 rotated 90 degrees. But that leaves the system unstable. Eventually one of the two instances crashes. The idea of ​​rotating the camera is to use the webcam for Instagram transmission, because the application we use allows you to use the OBS camera, keeping only one instance open.

**Comment by gxalpha** [comment]
I don't think rotating the camera would really solve your issue then as one stream, including it's contents like persons, pictures etc, would also be rotated, wouldn't it?

**Comment by johnboiles** [comment]
I think this is out of the scope of this plugin. I also don't fully understand your use case, if you just sent the exact same composited video to instagram (in portrait) that you're sending to YouTube (in landscape) wouldn't your aspect ratio be messed up for the video?
