### ISSUE TITLE
[BUG] Virtual Camera doesn't seem to start

### ISSUE THREAD

**Issue by nawkboy** [johnboiles/obs-mac-virtualcam#166]
https://obsproject.com/forum/threads/virtual-camera-doesnt-seem-to-start.123873/

I successfully installed v1.2.0 of obs-mac-virtualcam. Tools->Start Virtual Camera shows up in the OBS menu. When I launch the virtual camera I can't seem to find the virtual camera in any application I try from. Looking at the log file below there is obviously a problem, although I don't know how to quickly go about solving the problem. I am hoping someone on the forum will have a good suggestion.

The "Uninstalling" instructions at: https://github.com/johnboiles/obs-mac-virtualcam
talk about the following files.
/Library/CoreMediaIO/Plug-Ins/DAL/obs-mac-virtualcam.plugin
/Library/Application\ Support/obs-studio/plugins/obs-mac-virtualcam
I have confirmed both files exist. (I didn't want to uninstall them, just validate they were installed.)

The ons-mac-virtualcam package I used is:
https://github.com/johnboiles/obs-mac-virtualcam/releases/download/v1.2.0/obs-mac-virtualcam-3ca8f62-v1.2.0.pkg

Here is the log file from OBS:
13:02:18.608: CPU Name: Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz
13:02:18.608: CPU Speed: 2200MHz
13:02:18.608: Physical Cores: 4, Logical Cores: 8
13:02:18.608: Physical Memory: 16384MB Total
13:02:18.608: OS Name: Mac OS X (NSMACHOperatingSystem)
13:02:18.608: OS Version: Version 10.15.4 (Build 19E287)
13:02:18.608: Kernel Version: 19.4.0
13:02:18.621: hotkeys-cocoa: Using layout 'com.apple.keylayout.US'
13:02:18.621: Portable mode: false
13:02:18.765: OBS 25.0.8 (mac)
13:02:18.765: ---------------------------------
13:02:18.767: ---------------------------------
13:02:18.767: audio settings reset:
13:02:18.767: samples per sec: 44100
13:02:18.767: speakers: 2
13:02:18.787: ---------------------------------
13:02:18.787: Initializing OpenGL...
13:02:18.814: Loading up OpenGL on adapter Intel Inc. Intel Iris Pro OpenGL Engine
13:02:18.814: OpenGL loaded successfully, version 4.1 INTEL-14.5.22, shading language 4.10
13:02:18.909: ---------------------------------
13:02:18.909: video settings reset:
13:02:18.909: base resolution: 1440x900
13:02:18.909: output resolution: 1152x720
13:02:18.909: downscale filter: Bicubic
13:02:18.909: fps: 30/1
13:02:18.909: format: NV12
13:02:18.909: YUV mode: 601/Partial
13:02:18.909: NV12 texture support not available
13:02:18.911: Audio monitoring device:
13:02:18.911: name: Default
13:02:18.911: id: default
13:02:18.911: ---------------------------------
13:02:18.932: Failed to load 'en-US' text for module: 'decklink-ouput-ui.so'
13:02:18.969: os_dlopen(libpython3.7m.dylib->libpython3.7m.dylib): dlopen(libpython3.7m.dylib, 257): image not found
13:02:18.969:
13:02:18.970: [Python] Could not load library: libpython3.7m.dylib
13:02:19.241: A DeckLink iterator could not be created. The DeckLink drivers may not be installed
13:02:19.241: No blackmagic support
13:02:19.340: [VideoToolbox encoder]: Adding VideoToolbox H264 encoders
13:02:19.401: [obs-browser]: Version 2.8.6
13:02:19.576: os_dlopen(/Applications/VLC.app/Contents/MacOS/lib/libvlccore.dylib->/Applications/VLC.app/Contents/MacOS/lib/libvlccore.dylib): dlopen(/Applications/VLC.app/Contents/MacOS/lib/libvlccore.dylib, 257): image not found
13:02:19.576:
13:02:19.576: Couldn't find VLC installation, VLC video source disabled
13:02:19.594: Failed to load 'en-US' text for module: 'obs-mac-virtualcam.so'
13:02:19.594: [obs-mac-virtualcam] version=1.2.0
13:02:19.594: ---------------------------------
13:02:19.594: Loaded Modules:
13:02:19.594: obs-mac-virtualcam.so
13:02:19.594: vlc-video.so
13:02:19.594: text-freetype2.so
13:02:19.594: rtmp-services.so
13:02:19.594: obs-x264.so
13:02:19.594: obs-vst.so
13:02:19.594: obs-transitions.so
13:02:19.594: obs-outputs.so
13:02:19.594: obs-libfdk.so
13:02:19.594: obs-filters.so
13:02:19.594: obs-ffmpeg.so
13:02:19.594: obs-browser.so
13:02:19.594: mac-vth264.so
13:02:19.594: mac-syphon.so
13:02:19.594: mac-decklink.so
13:02:19.594: mac-capture.so
13:02:19.594: mac-avcapture.so
13:02:19.594: linux-jack.so
13:02:19.594: image-source.so
13:02:19.594: frontend-tools.so
13:02:19.594: decklink-ouput-ui.so
13:02:19.594: coreaudio-encoder.so
13:02:19.594: ---------------------------------
13:02:19.595: os_dlopen(../obs-plugins/obs-browser->../obs-plugins/obs-browser.so): dlopen(../obs-plugins/obs-browser.so, 257): image not found
13:02:19.595:
13:02:19.595: ==== Startup complete ===============================================
13:02:19.631: Service '' not found
13:02:19.638: All scene data cleared
13:02:19.638: ------------------------------------------------
13:02:19.670: coreaudio: device 'Built-in Microphone' initialized
13:02:19.671: [Loaded global audio device]: 'Mic/Aux'
13:02:19.809: MacBookCamera: Selected device 'FaceTime HD Camera'
13:02:19.812: MacBookCamera: Using preset 1280x720
13:02:19.933: Switched to scene 'Scene 1'
13:02:19.933: ------------------------------------------------
13:02:19.933: Loaded scenes:
13:02:19.933: - scene 'Scene 1':
13:02:19.937: - source: 'TextTestJames' (text_ft2_source_v2)
13:02:19.937: - source: 'BrowserTest' (browser_source)
13:02:19.937: - source: 'TestImage' (image_source)
13:02:19.937: - source: 'MacBookCamera' (av_capture_input)
13:02:19.937: - scene 'Scene 2':
13:02:19.937: - source: 'TextTestJames' (text_ft2_source_v2)
13:02:19.937: - source: 'MacBookCamera' (av_capture_input)
13:02:19.937: - source: 'BrowserTest' (browser_source)
13:02:19.937: - scene 'SceneZoe':
13:02:19.937: - source: 'MacBookCamera' (av_capture_input)
13:02:19.937: - source: 'BrowserTest' (browser_source)
13:02:19.937: - source: 'TextTestZoe' (text_ft2_source_v2)
13:02:19.937: ------------------------------------------------
13:02:20.029: Switched to Preview/Program mode
13:02:20.029: ------------------------------------------------
13:02:20.354: adding 46 milliseconds of audio buffering, total audio buffering is now 46 milliseconds (source: Mic/Aux)
13:02:20.354:

**Comment by gxalpha** [comment]
If you're saying you don't see a camera at all (not even a test screen) that means there is a program with the DAL plugin.
Could you please
* specify the programs you tried to use and
* check Console.app for logs with "obs-mac-virtualcam"?

That should help identify the problem.
Thanks!

**Comment by nawkboy** [comment]
default	08:15:26.645020-0500	obs	obs-mac-virtualcam(DAL): PlugInMain version=1.2.0
default	08:15:26.645128-0500	obs	obs-mac-virtualcam(DAL): HardwarePlugIn_QueryInterface
default	08:15:26.645167-0500	obs	obs-mac-virtualcam(DAL): HardwarePlugIn_Release sRefCount now = 0
default	08:15:26.645210-0500	obs	obs-mac-virtualcam(DAL): HardwarePlugIn_InitializeWithObjectID self=0x2305e768
default	08:15:26.645505-0500	obs	obs-mac-virtualcam(DAL): HardwarePlugIn_ObjectSetPropertyData Device(33) kCMIOObjectPropertyListenerAdded self=0x2305e768 data(int)=1684629094
default	08:15:26.645559-0500	obs	obs-mac-virtualcam(DAL): Device unhandled setPropertyDataWithAddress for kCMIOObjectPropertyListenerAdded
default	08:15:26.645600-0500	obs	obs-mac-virtualcam(DAL): HardwarePlugIn_ObjectSetPropertyData Device(33) kCMIOObjectPropertyListenerAdded self=0x2305e768 data(int)=1869180523
default	08:15:26.645636-0500	obs	obs-mac-virtualcam(DAL): Device unhandled setPropertyDataWithAddress for kCMIOObjectPropertyListenerAdded
default	08:15:26.645674-0500	obs	obs-mac-virtualcam(DAL): HardwarePlugIn_ObjectSetPropertyData Device(33) kCMIOObjectPropertyListenerAdded self=0x2305e768 data(int)=1885762592
default	08:15:26.645709-0500	obs	obs-mac-virtualcam(DAL): Device unhandled setPropertyDataWithAddress for kCMIOObjectPropertyListenerAdded
default	08:15:27.903346-0500	obs	obs-mac-virtualcam(DAL): HardwarePlugIn_ObjectSetPropertyData Device(33) kCMIOObjectPropertyListenerAdded self=0x2305e768 data(int)=1818850926
default	08:15:27.903450-0500	obs	obs-mac-virtualcam(DAL): Device unhandled setPropertyDataWithAddress for kCMIOObjectPropertyListenerAdded
default	08:15:27.903523-0500	obs	obs-mac-virtualcam(DAL): HardwarePlugIn_ObjectSetPropertyData Device(33) kCMIOObjectPropertyListenerAdded self=0x2305e768 data(int)=1869180523
default	08:15:27.903589-0500	obs	obs-mac-virtualcam(DAL): Device unhandled setPropertyDataWithAddress for kCMIOObjectPropertyListenerAdded
default	08:15:27.903669-0500	obs	obs-mac-virtualcam(DAL): HardwarePlugIn_ObjectSetPropertyData Device(33) kCMIOObjectPropertyListenerAdded self=0x2305e768 data(int)=1937009955
default	08:15:27.903731-0500	obs	obs-mac-virtualcam(DAL): Device unhandled setPropertyDataWithAddress for kCMIOObjectPropertyListenerAdded
default	08:15:27.903806-0500	obs	obs-mac-virtualcam(DAL): HardwarePlugIn_ObjectSetPropertyData Device(33) kCMIOObjectPropertyListenerAdded self=0x2305e768 data(int)=1886156132
default	08:15:27.903872-0500	obs	obs-mac-virtualcam(DAL): Device unhandled setPropertyDataWithAddress for kCMIOObjectPropertyListenerAdded
default	08:15:27.903939-0500	obs	obs-mac-virtualcam(DAL): HardwarePlugIn_ObjectSetPropertyData Device(33) kCMIOObjectPropertyListenerAdded self=0x2305e768 data(int)=1935833461
default	08:15:27.904004-0500	obs	obs-mac-virtualcam(DAL): Device unhandled setPropertyDataWithAddress for kCMIOObjectPropertyListenerAdded
default	08:15:27.904066-0500	obs	obs-mac-virtualcam(DAL): Device unhandled hasPropertyWithAddress for kCMIOObjectPropertyOwnedObjects
default	08:15:27.904126-0500	obs	obs-mac-virtualcam(DAL): Device unhandled hasPropertyWithAddress for kCMIOObjectPropertyOwnedObjects
default	08:15:27.904189-0500	obs	obs-mac-virtualcam(DAL): Device unhandled hasPropertyWithAddress for kCMIOObjectPropertyOwnedObjects
default	08:15:27.904254-0500	obs	obs-mac-virtualcam(DAL): Stream unhandled hasPropertyWithAddress for kCMIOObjectPropertyOwnedObjects
default	08:15:27.904315-0500	obs	obs-mac-virtualcam(DAL): Stream unhandled hasPropertyWithAddress for kCMIOObjectPropertyOwnedObjects
default	08:15:27.904448-0500	obs	obs-mac-virtualcam(DAL): Stream unhandled hasPropertyWithAddress for kCMIOObjectPropertyOwnedObjects
default	08:15:27.904516-0500	obs	obs-mac-virtualcam(DAL): Device unhandled hasPropertyWithAddress for kCMIOObjectPropertyOwnedObjects
default	08:15:27.904581-0500	obs	obs-mac-virtualcam(DAL): Device unhandled hasPropertyWithAddress for kCMIOObjectPropertyOwnedObjects
default	08:15:27.904644-0500	obs	obs-mac-virtualcam(DAL): Device unhandled hasPropertyWithAddress for kCMIOObjectPropertyOwnedObjects
default	08:15:27.904714-0500	obs	obs-mac-virtualcam(DAL): Stream unhandled hasPropertyWithAddress for kCMIOObjectPropertyOwnedObjects
default	08:15:27.904776-0500	obs	obs-mac-virtualcam(DAL): Stream unhandled hasPropertyWithAddress for kCMIOObjectPropertyOwnedObjects
default	08:15:27.904836-0500	obs	obs-mac-virtualcam(DAL): Stream unhandled hasPropertyWithAddress for kCMIOObjectPropertyOwnedObjects
default	08:15:27.904900-0500	obs	obs-mac-virtualcam(DAL): Device unhandled hasPropertyWithAddress for kCMIOObjectPropertyOwnedObjects
default	08:15:27.904962-0500	obs	obs-mac-virtualcam(DAL): Device unhandled hasPropertyWithAddress for kCMIOObjectPropertyOwnedObjects
default	08:15:27.905024-0500	obs	obs-mac-virtualcam(DAL): Device unhandled hasPropertyWithAddress for kCMIOObjectPropertyOwnedObjects
default	08:15:27.905087-0500	obs	obs-mac-virtualcam(DAL): Stream unhandled hasPropertyWithAddress for kCMIOObjectPropertyOwnedObjects
default	08:15:27.905148-0500	obs	obs-mac-virtualcam(DAL): Stream unhandled hasPropertyWithAddress for kCMIOObjectPropertyOwnedObjects
default	08:15:27.905208-0500	obs	obs-mac-virtualcam(DAL): Stream unhandled hasPropertyWithAddress for kCMIOObjectPropertyOwnedObjects
default	08:15:27.905270-0500	obs	obs-mac-virtualcam(DAL): Device unhandled hasPropertyWithAddress for kCMIOObjectPropertyOwnedObjects
default	08:15:27.905329-0500	obs	obs-mac-virtualcam(DAL): Device unhandled hasPropertyWithAddress for kCMIOObjectPropertyOwnedObjects
default	08:15:27.905390-0500	obs	obs-mac-virtualcam(DAL): Device unhandled hasPropertyWithAddress for kCMIOObjectPropertyOwnedObjects
default	08:15:27.905455-0500	obs	obs-mac-virtualcam(DAL): Stream unhandled hasPropertyWithAddress for kCMIOObjectPropertyOwnedObjects
default	08:15:27.905513-0500	obs	obs-mac-virtualcam(DAL): Stream unhandled hasPropertyWithAddress for kCMIOObjectPropertyOwnedObjects
default	08:15:27.905636-0500	obs	obs-mac-virtualcam(DAL): Stream unhandled hasPropertyWithAddress for kCMIOObjectPropertyOwnedObjects
default	08:15:27.905703-0500	obs	obs-mac-virtualcam(DAL): Device unhandled hasPropertyWithAddress for kCMIOObjectPropertyOwnedObjects
default	08:15:27.905764-0500	obs	obs-mac-virtualcam(DAL): Device unhandled hasPropertyWithAddress for kCMIOObjectPropertyOwnedObjects
default	08:15:27.905874-0500	obs	obs-mac-virtualcam(DAL): Device unhandled hasPropertyWithAddress for kCMIOObjectPropertyOwnedObjects
default	08:15:27.905946-0500	obs	obs-mac-virtualcam(DAL): Stream unhandled hasPropertyWithAddress for kCMIOObjectPropertyOwnedObjects
default	08:15:27.906008-0500	obs	obs-mac-virtualcam(DAL): Stream unhandled hasPropertyWithAddress for kCMIOObjectPropertyOwnedObjects
default	08:15:27.906070-0500	obs	obs-mac-virtualcam(DAL): Stream unhandled hasPropertyWithAddress for kCMIOObjectPropertyOwnedObjects
default	08:15:27.906131-0500	obs	obs-mac-virtualcam(DAL): Device unhandled hasPropertyWithAddress for kCMIOObjectPropertyOwnedObjects
default	08:15:27.906191-0500	obs	obs-mac-virtualcam(DAL): Device unhandled hasPropertyWithAddress for kCMIOObjectPropertyOwnedObjects
default	08:15:27.906274-0500	obs	obs-mac-virtualcam(DAL): HardwarePlugIn_ObjectSetPropertyData Stream(34) kCMIOObjectPropertyListenerAdded self=0x2305e768 data(int)=1885762592
default	08:15:27.906379-0500	obs	obs-mac-virtualcam(DAL): Stream unhandled setPropertyDataWithAddress for kCMIOObjectPropertyListenerAdded
default	08:15:27.906449-0500	obs	obs-mac-virtualcam(DAL): Device unhandled hasPropertyWithAddress for kCMIOObjectPropertyOwnedObjects
default	08:15:27.906510-0500	obs	obs-mac-virtualcam(DAL): Device unhandled hasPropertyWithAddress for kCMIOObjectPropertyOwnedObjects
default	08:15:27.906583-0500	obs	obs-mac-virtualcam(DAL): Device unhandled hasPropertyWithAddress for kCMIOObjectPropertyOwnedObjects
default	08:15:27.906843-0500	obs	obs-mac-virtualcam(DAL): Device unhandled hasPropertyWithAddress for kCMIOObjectPropertyOwnedObjects
default	08:15:27.906908-0500	obs	obs-mac-virtualcam(DAL): Device unhandled hasPropertyWithAddress for kCMIOObjectPropertyOwnedObjects
default	08:15:27.906970-0500	obs	obs-mac-virtualcam(DAL): Device unhandled hasPropertyWithAddress for kCMIOObjectPropertyOwnedObjects
default	08:15:27.907062-0500	obs	obs-mac-virtualcam(DAL): Device unhandled hasPropertyWithAddress for kCMIODevicePropertySuspendedByUser
default	08:15:27.907126-0500	obs	obs-mac-virtualcam(DAL): Device unhandled hasPropertyWithAddress for kCMIOObjectPropertyOwnedObjects
default	08:15:27.907180-0500	obs	obs-mac-virtualcam(DAL): Device unhandled hasPropertyWithAddress for kCMIOObjectPropertyOwnedObjects

**Comment by nawkboy** [comment]
I tried testing a little more today and have somewhat good news.

The zoom webclient successfully saw the OBS virtual camera.
The native zoom client version 5.0.5 still can not see it.

I thought the newest version of zoom was supposed to re-enable virtual cameras.

**Comment by gxalpha** [comment]
For zoom see https://github.com/johnboiles/obs-mac-virtualcam/wiki/Compatibility
