### ISSUE TITLE
Compatibility.md Skype Notes Typo

### ISSUE THREAD

**Issue by bobvan** [johnboiles/obs-mac-virtualcam#169]
**Describe the bug**
The notes column of the Skype row in Compatibility.md doubles some backslashes.

**To Reproduce**
1. Install Skype if not already installed.
2. Copy/paste `codesign` command from Notes column of Skype row.
3. See `zsh: no matches found: /Applications/Skype.app/Contents/Frameworks/Skype Helper \(Renderer\).app`.
4. See error in console output.

**Expected behavior**
`codesign` should complete without error.

**Console output**
Instead of `codesign` completing without error, I see
`zsh: no matches found: /Applications/Skype.app/Contents/Frameworks/Skype Helper \(Renderer\).app`

**Desktop (please complete the following information):**
 - OS version: macOS Catalina 10.15.5
 - Application: Skype
 - Virtualcam version: 1.2.0
 - OBS version:  25.0.8

**Additional context**
I tried to create a fork of the Wiki so I could submit a pull request but couldn't figure out how GitHub handles wiki pull requests.

**Comment by gxalpha** [comment]
Thanks for reporting!
Something similar has been posted [here](https://github.com/johnboiles/obs-mac-virtualcam/issues/131#issuecomment-640096965), could you test if that works?

**Comment by gxalpha** [comment]
Seems like this got corrected.
