### ISSUE TITLE
feature request: make OBS audio output available as well as virtual camera

### ISSUE THREAD

**Issue by jtagg** [johnboiles/obs-mac-virtualcam#17]
It would be great and add additional workflow flexibility if the audio output from OBS were also available as an input as well as the video feed for cases where video and audio are produced from OBS.

**Comment by gxalpha** [comment]
hi @jtagg this is planned; but afaik split up into another project as video alone is hard enough of a task. Take a look at the RFC-Discussion [here](https://github.com/obsproject/rfcs/pull/15#issuecomment-607969774) if you are interested

**Comment by jtagg** [comment]
Ok! Thank you for the pointer to the discussion and sorry I missed that.

**Comment by johnboiles** [comment]
Yeah I 100% agree. But the overlap in the DAL plugin (video) and HAL plugin (audio) code would be very very minimal. It would be awesome if someone wanted to get started on a `obs-mac-virtualaudio` plugin or something like that.

**Comment by andrewodri** [comment]
Just a heads up; it seems that audio specific discussion has been moved to obsproject/rfcs#16 (for now at least).

The nice thing with audio portion is that there is some _really_ pretty HAL code out there, whereas the DAL code is mostly horrific.

**Comment by johnboiles** [comment]
That's good to hear @andrewodri! The DAL code out there is definitely horrific -- I'm weighing if I have enough stamina to just start over on that part from scratch.

Going to close this. But someone please go work on obsproject/rfcs#16 😄
