### ISSUE TITLE
[Feature Request] Virtual filter output

### ISSUE THREAD

**Issue by pedroslopez** [johnboiles/obs-mac-virtualcam#170]
**Describe the solution you'd like**
Add the ability to only output certain sources through a filter, like on the windows counterpart of virtualcam.

**Comment by chetwatkins** [comment]
This would be great. We were just trying to do this and realized it was only an option in the  windows version right now.

**Comment by johnboiles** [comment]
If this is still something you want, you should advocate for it on the obs-studio GitHub since all future development is moving there.
