### ISSUE TITLE
[BUG] Camera Feed not showing in BIGBLUEBUTTON

### ISSUE THREAD

**Issue by uwe22** [johnboiles/obs-mac-virtualcam#173]
What an amazing tool, thank you!

the videoconference software bigbluebutton https://bigbluebutton.org/ allows selecting the obs-mac-virtual cam. But only some first frames are displayed. The image freezes.

**To Reproduce**
![Screen Shot 2020-06-12 at 00 16 38](https://user-images.githubusercontent.com/11908297/84404626-0cc0c380-ac42-11ea-8d1a-5b3c305af240.jpg)

1. install the abs mac virtual cam
2. start obs and stat the virtual cam
3. Open a session in BigBlueButton
4. Share the virtual webcamera.

**Expected behavior**
I expected the output from OBS to be visible in the webcam window.

**Screenshots**

**Desktop (please complete the following information):**
 - OS version: [macOS 10.14.6]
 - Application: [BRAVE Browser and Chrome]
 - Virtualcam version: [1.2.0]
 - OBS version: [25.0.8]

**Additional context**
It seems there is a huge drain in memory. the whole computer becomes less responsive. I have tried to downscale the resolution from OBS.

**Comment by gxalpha** [comment]
This seems to be a Compatibility problem with your browser. Could you please check console.app for bugs with `obs-mac-vitualcam`?
Also, does the test card (the output visible if the cam is inactive) say "1.2.0" at the bottom? I thought that memory leak (as well as what seems to be the timing issue which makes some apps only show a couple of frames) should have been fixed...

**Comment by uwe22** [comment]
the test card does say correctly 1.2.0
I tested again with Chrome latest version Version 83.0.4103.97 (Official Build) (64-bit)
and BigBlueButton.

I have looked in the browser javascript console. there are some warnings.
and a lot coming up in the console.
I exported this for you. maybe it can help you.
I did not see anything abnormal in the system monitor regarding processes, memory or network. Obs goes up from about 30 to 60 percent cpu usage when I start the virtual cam.
[cosole_log.txt](https://github.com/johnboiles/obs-mac-virtualcam/files/4771068/cosole_log.txt)
![Screen Shot 2020-06-12 at 22 23 04](https://user-images.githubusercontent.com/11908297/84508592-7b168c00-acfd-11ea-80eb-0eadd83307f7.jpg)
![Screen Shot 2020-06-12 at 22 27 36](https://user-images.githubusercontent.com/11908297/84508597-7eaa1300-acfd-11ea-9a60-2605647ce23f.jpg)
![Screen Shot 2020-06-12 at 22 31 11](https://user-images.githubusercontent.com/11908297/84508601-7fdb4000-acfd-11ea-99dd-1d7afc521b82.jpg)

**Comment by KlausHB** [comment]
Here on macOS Mojave the startpicture and video of OBS appeared but scrambled :-(
<img width="604" alt="Bildschirmfoto 2020-10-01 um 20 22 11" src="https://user-images.githubusercontent.com/10743089/94852588-671ca480-042a-11eb-8b28-f872852f66ed.png">

In MS Teams everything works fine.

Any hints?

Best regards 

Klaus

**Comment by gxalpha** [comment]
Try reinstalling the virtualcam plugin. Restart your computer. If that doesn't help, browse #160. Also please refer there for further questions, this is the wrong issue for the problem you're facing.

**Comment by KlausHB** [comment]
thanx for the prompt answer.
playing arround with the advanced settings i found a solution by reactivating the v-sync. A checkbox deactivated that.
Now it works :-))

Klaus
