### ISSUE TITLE
[Feature Request]mirror option in output virtual cam

### ISSUE THREAD

**Issue by Psi-Lin** [johnboiles/obs-mac-virtualcam#174]
Google meet mirrors the cam. Sharing documents and screen sharing is delivering mirrored images to the audience. 
Current workaround is to mirror each scene object independently. 

Problem with the workaround is that output generated within OBS is mirrored. 

Best place for this option because of the global working is a setting under tools.

**Comment by dodgepong** [comment]
Are you sure that other people on the call see the output mirrored, or do you only see your output mirrored on your own view preview? Most video calling systems will show you your own webcam in a mirrored view, but will show it correctly to everyone else on the call.

**Comment by dodgepong** [comment]
I just checked it myself by calling myself on a separate Google account using Google Meet. My own view was mirrored but the person joining the call saw the image non-mirrored.

**Comment by Psi-Lin** [comment]
**shamed** you are absolutely right. So this feature request leads to nowhere. 
I should have tried this test by myself before i opened this request. Sorry for the inconvenience!

**Comment by gxalpha** [comment]
After some discussion on the Discord a few days ago I saw I think we should be reopen this, with the button saying something like "usually not needed" and further explanation, this may reduce the number of bug reports and feature requests

**Comment by GVDub** [comment]
Microsoft Teams automatically mirrors what comes in from OBS Virtual Cam, with no in app ability to "de-mirror." So far it's the only app I've come across that has that issue.

**Comment by gxalpha** [comment]
Again to clarify, for the person it isn't mirrored, only your preview is!

**Comment by dodgepong** [comment]
It sounds like the solution here is going to be to not have an option to mirror output, and instead show a message somewhere explaining what's going on.

Adding the feature would almost 100% just be giving users a way to shoot themselves in the foot, because it is almost never actually needed.

**Comment by johnboiles** [comment]
What if there was a 'mirror' button that just popped a dialog that explains that you don't really want to mirror your stream 😂 (only half joking)

**Comment by GVDub** [comment]
> Again to clarify, for the person it isn't mirrored, only your preview is!

Nope. it was mirrored when it was live (as of 10 AM today).

**Comment by dodgepong** [comment]
If that's true, I might argue that Teams should be the one to fix that. If they reverse people's cameras in the output, frankly that's horseshit.

**Comment by dodgepong** [comment]
I just tested this in the Mac version of Teams, and the viewers on my call saw it with the correct orientation. not mirrored. Here is a screenshot of what they saw:

![macos](https://user-images.githubusercontent.com/838450/85086473-b6ef9c80-b1a8-11ea-8c40-e609b64249e6.png)

**Comment by Fenrirthviti** [comment]
To clarify this, it looks like that Teams will _always_ mirror your own video preview, but not the actual output. So if it's mirrored for you, it's correct for everyone else. This also means that if it's not mirrored for you, then it will be mirrored for everyone else. You probably saw the preview and thought you needed to mirror, which it was already doing as part of the preview, but NOT the output.

**Comment by dodgepong** [comment]
Confirmation on the behavior I just observed here (as well as a way to tell Teams to add a feature to not mirror your own preview): https://microsoftteams.uservoice.com/forums/555103-public/suggestions/39267535-toggle-video-camera-mirroring-on-or-off-for-teams

**Comment by johnboiles** [comment]
Closing this as I think adding a mirror option would almost always cause users to shoot themselves in the foot.
