### ISSUE TITLE
[Support]Start Virtual Camera not an option in Tools

### ISSUE THREAD

**Issue by RONCOmke** [johnboiles/obs-mac-virtualcam#175]
_Please read the "Discussion / Support" section of the Readme first. Only open an issue if you don't get an answer on the OBS or someone tells you to. Attention: While Zoom says they re-enabled virtual cameras, only certain ones they whitelisted work. Currently, this plugin does not work with Zoom out of the box! See https://github.com/johnboiles/obs-mac-virtualcam/wiki/Compatibility#apps-dont-allow-dal-plugins for a workaround._

**Describe the issue**
I installed the .pkg in the latest release. Launched OBS and Google Meets. Google recognizes the input, but comes up with a screen that states "OBS Virtual Cam Inactive"
I go to OBS and under the TOOLS section, Start Virtual Cam isn't an option.
**Behavior**
A clear and concise description of what happened.

**Screenshots**

**Desktop (please complete the following information):**
 - OS version: macOS Catalina 10.15.4
 - Application (if applicable): Google Chrome
 - Virtualcam version: 1.2.0
 - OBS version: 24.0.6

**Additional context**

**Comment by RONCOmke** [comment]
Updating to OBS 25.0.8 solved the issue, but my image is now mirrored in google Meet

**Comment by gxalpha** [comment]
see #174 for mirror problems
