### ISSUE TITLE
screens black, using sony a7 and the imaging edge app

### ISSUE THREAD

**Issue by swi808** [johnboiles/obs-mac-virtualcam#176]
_Please read the "Discussion / Support" section of the Readme first. Only open an issue if you don't get an answer on the OBS or someone tells you to. Attention: While Zoom says they re-enabled virtual cameras, only certain ones they whitelisted work. Currently, this plugin does not work with Zoom out of the box! See https://github.com/johnboiles/obs-mac-virtualcam/wiki/Compatibility#apps-dont-allow-dal-plugins for a workaround._

**Describe the issue**
A clear and concise description of what the problem is.

**To Reproduce**

**Behavior**
A clear and concise description of what happened.

**Screenshots**

**Desktop (please complete the following information):**
 - OS version: [e.g. macOS Catalina 10.15.4]
 - Application (if applicable): [e.g. Chrome, Safari]
 - Virtualcam version: [e.g. 1.0.0]
 - OBS version: [e.g. 25.0.8]

**Additional context**

**Comment by gxalpha** [comment]
Could you please fill out the information above so that we can understand your issue? :smile:

**Comment by johnboiles** [comment]
Closing until you provide more details.
