### ISSUE TITLE
when using DingTalk app for video conference the screen becomes blurred and indistinct

### ISSUE THREAD

**Issue by Daniellee1231** [johnboiles/obs-mac-virtualcam#177]
![image](https://user-images.githubusercontent.com/59252325/85350540-f238f500-b533-11ea-8c7d-3a1b0dd15c32.png)

**Comment by gxalpha** [comment]
Hey, please fill out the information on the issue template first to give us more information about your system. For this, open a new issue and select "Support request" and fill out the data.
To me this looks like an old bug that should be fixed, but I can't tell without further information.
