### ISSUE TITLE
[Support] Plugin is not working for any application

### ISSUE THREAD

**Issue by sfdcoderaz-git** [johnboiles/obs-mac-virtualcam#178]
I have downloaded the plugin, and it is showing up in the tool bar in OBS. For some reason, the plugin is not working in any application, including QuickTime, which according to the wiki should have no problem. I have tried everything I can think of, including restarting my computer, updating my computer and OBS software, giving OBS full disk access, but it still doesn't work. When I create a new movie recording in quicktime, it just shows my face. Any help would be much appreciated.
![Screen Shot 2020-06-23 at 10 07 24](https://user-images.githubusercontent.com/57157067/85433467-57dbb000-b539-11ea-9377-da7df3c211b6.png)
![Screen Shot 2020-06-23 at 10 07 50](https://user-images.githubusercontent.com/57157067/85433510-6629cc00-b539-11ea-93e9-79541a72d823.png)
![Screen Shot 2020-06-23 at 10 08 05](https://user-images.githubusercontent.com/57157067/85433655-983b2e00-b539-11ea-81f0-cd39434e4612.png)

**Comment by johnboiles** [comment]
Please fill out the details that were included in the issue template:

 - OS version: [e.g. macOS Catalina 10.15.4]
 - Application (if applicable): [e.g. Chrome, Safari]
 - Virtualcam version: [e.g. 1.0.0]
 - OBS version: [e.g. 25.0.8]

Also include a screenshot of the sources list from QuickTime.

**Comment by gxalpha** [comment]
You need to select the camera in QuickTime by clicking the small triangle right of the start/stop recording button (see below).
<img width="441" alt="Bildschirmfoto 2020-06-23 um 19 25 01" src="https://user-images.githubusercontent.com/59806498/85435199-651f8b80-b587-11ea-88f8-7a495756f3f7.png">
Then, select the OBS virtual camera there.
<img width="231" alt="Bildschirmfoto 2020-06-23 um 19 27 15" src="https://user-images.githubusercontent.com/59806498/85435360-a0ba5580-b587-11ea-91dc-bdf5bc5fa479.png">


Other apps should also have their camera setting somewhere.

**Comment by sfdcoderaz-git** [comment]
@gxalpha  thank you for the answer
