### ISSUE TITLE
Unable to generate Xcodeproj

### ISSUE THREAD

**Issue by Raj123456788** [johnboiles/obs-mac-virtualcam#179]
Followed https://github.com/johnboiles/obs-mac-virtualcam/wiki/Developing#using-the-cmake-xcode-generator

**Describe the bug**
Using the cmake Xcode generator does not work: I followed below steps 
You can use cmake to generate an xcodeproj file to open all the files in Xcode. This is my preferred way of developing code on this plugin.

# Set an environment variable that points to the directory for your OBS clone
export OBS_DIR=$PWD/../obs-studio
# Set an environment variable pointing to QT
export QTDIR=$(brew --prefix)/opt/qt

mkdir xcode
cd xcode
cmake -DLIBOBS_INCLUDE_DIR:STRING=$OBS_DIR/libobs -DLIBOBS_LIB:STRING=$OBS_DIR/build/libobs/libobs.dylib -DOB

**Desktop (please complete the following information):**
 - OS version:  10.15.4]
 - Application: [ Zoom]
 - Virtualcam version: [1.2.0]
 - OBS version: [e.g. 25.0.8]

**Additional context** I get below error
 cmake -DLIBOBS_INCLUDE_DIR:STRING=$OBS_DIR/libobs -DLIBOBS_LIB:STRING=$OBS_DIR/build/libobs/libobs.dylib -DOBS_FRONTEND_LIB:STRING=$OBS_DIR/build/UI/obs-frontend-api/libobs-frontend-api.dylib -DQTDIR:STRING=$QTDIR -G Xcode ..
CMake Error: The source directory "/Users/Test/Downloads/Testobsplugin/obs-studio/build/rundir/RelWithDebInfo/bin" does not appear to contain CMakeLists.txt.
Specify --help for usage, or press the help button on the CMake GUI

**Comment by gxalpha** [comment]
Have you created your own build of OBS? You need to do that first so that cmake can access the libobs files. 
The steps are described above the snipped you posted.

**Comment by Raj123456788** [comment]
Yes, i tried the steps above but I am getting -bash: ./obs: Input/output error when I run # Run your build of OBS
cd $OBS_DIR/build/rundir/RelWithDebInfo/bin
./obs

**Comment by Raj123456788** [comment]
<img width="648" alt="Screen Shot 2020-06-24 at 2 51 59 PM" src="https://user-images.githubusercontent.com/16295521/85631427-5dfd8980-b62a-11ea-882e-9586bc2f4df9.png">
This is my folder structure. Tell me where to cd into to run above command.

**Comment by gxalpha** [comment]
Seems to not be a current issue anymore.
Please reopen if it still is.

**Comment by Raj123456788** [comment]
@gxalpha can you please answer my question Feeding the plugin with samples@Runtime? I f you have any documentation where I can select an image and feed it. Please let me know.
