### ISSUE TITLE
Heads up -- new zoom update disables virtual cameras

### ISSUE THREAD

**Issue by mstksg** [johnboiles/obs-mac-virtualcam#18]
Not sure if maintainers are already aware, but just opening this up here in case people are having issues like I was.  The latest zoom update (4.6.9) swaps a flag that allows unvalidated camera input, breaking snapcam and others.  *Presumably* it was done to address the security PR nightmare it is currently facing.

From snapcamera team -- <https://support.lensstudio.snapchat.com/hc/en-us/articles/360041102572-How-do-I-use-Snap-Camera-with-Zoom->

> Unfortunately, Zoom’s latest update on Mac (version 4.6.9) doesn’t work with Snap Camera. Zoom’s engineering team is aware of this issue and we hope Zoom will fix this issue in an update shortly.

Some discussion of the change -- <https://medium.com/@dkiesow/how-to-fix-the-virtual-camera-function-in-zoom-mac-only-9872a6d9ea5>

> Last week Zoom released an update. For Mac it was version 4.6.9. I immediately installed it, assuming it had addressed some of the noted security issues. It may have but it also disabled virtual cameras on both Mac and PC. That is a problem as I was relying on that feature and had purchased ManyCam specifically for that purpose.
> It is not clear if Zoom intended to break virtual cameras, maybe the feature is vulnerable to attack. But there is still no official mention of it I can find. I filed tickets with Zoom and ManyCam to get answers. Zoom has not replied (they may be busy?) but ManyCam did.

The last link does include download links to older versions of zoom, for testing purposes.

Technical details and analysis --  <https://stackoverflow.com/questions/61114738/are-macos-virtual-webcams-inherently-incompatible-with-10-14s-hardened-runtime>

> Zoom for Mac 4.6.9, which addresses scary security flaws, removes the `disable-library-validation` entitlement.
>
> With the same release, Snap Camera, a virtual webcam app, stopped working.
>
> I'm not familiar with the particular APIs you use to build a virtual webcam, but it looks like it involves CoreMediaIO plugins ... out of curiosity, I tried a couple other virtual webcams -- Iriun Webcam and EpocCam –- and they behave similarly. Both have CoreMediaIO plugins, and neither works with recent Zoom.
>
> All three virtual cameras work in Microsoft Teams, which has the entitlement ... they also work in Google Chrome (on this test page). It looks like at least one of Chrome's helpers has the entitlement ... I've also noticed that the plugin appears in Activity Monitor's Open Files and Ports for a couple processes belonging to Teams and Chrome

Spent a decent amount of time tracking this down, and was "relieved" to know that the issue is on Zoom's side, not OSX's (for now, at least).  For me so far, I have been able to use zoom's older version fine when calling people on the latest version.

**Comment by gxalpha** [comment]
Oh wow, thank you very much!

**Comment by johnboiles** [comment]
Thanks for the report and all the info! We're discussing the zoom issue (and other codesigning related issues) here: https://github.com/johnboiles/obs-mac-virtualcam/issues/4#issuecomment-611910527

**Comment by mstksg** [comment]
@johnboiles ah, thanks for the reference!  I must have missed it, i'm not too familiar with the lingo.  Feel free to close this if you feel it is redundant.
