### ISSUE TITLE
Plugin Failed to Build

### ISSUE THREAD

**Issue by DavidTNguyen** [johnboiles/obs-mac-virtualcam#180]
### Plugin Failed to Build

**Screenshots**
![Screen Shot 2020-06-25 at 12 08 15 AM](https://user-images.githubusercontent.com/11265859/85657741-0423b080-b678-11ea-8132-856860764bbf.png)

**Desktop (please complete the following information):**
 - OS version: [e.g. macOS Mojave 10.14.6 ]

**Additional context**
`
$ cmake -DLIBOBS_INCLUDE_DIR:STRING=$OBS_DIR/libobs -DLIBOBS_LIB:STRING=$OBS_DIR/build/libobs/libobs.dylib -DOBS_FRONTEND_LIB:STRING=$OBS_DIR/build/UI/obs-frontend-api/libobs-frontend-api.dylib -DQTDIR:STRING=$QTDIR ..
make -j
-- The C compiler identification is AppleClang 10.0.1.10010046
-- The CXX compiler identification is AppleClang 10.0.1.10010046
-- Check for working C compiler: /Library/Developer/CommandLineTools/usr/bin/cc
-- Check for working C compiler: /Library/Developer/CommandLineTools/usr/bin/cc - works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /Library/Developer/CommandLineTools/usr/bin/c++
-- Check for working CXX compiler: /Library/Developer/CommandLineTools/usr/bin/c++ - works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Found Libobs: /Users/z076095/dev/obs-mac-virtualcam/build/../obs-studio/build/libobs/libobs.dylib  
CMake Error at cmake/Modules/FindLibobs.cmake:98 (include):
  include could not find load file:

    /Users/z076095/dev/obs-mac-virtualcam/build/../obs-studio/libobs/../cmake/external/ObsPluginHelpers.cmake
Call Stack (most recent call first):
  src/obs-plugin/CMakeLists.txt:3 (find_package)

-- Configuring incomplete, errors occurred!
See also "/Users/z076095/dev/obs-mac-virtualcam/build/CMakeFiles/CMakeOutput.log".
make: *** No targets specified and no makefile found.  Stop.

`

**Comment by gxalpha** [comment]
Have you built obs-studio before trying to build the plugin?

**Comment by DavidTNguyen** [comment]
I made a small tweak to the command that export the path of OBS_STUDIO,
then the plug-in build worked
