### ISSUE TITLE
[BUG]Can't use Mac OS 11.0

### ISSUE THREAD

**Issue by mikage-961pro** [johnboiles/obs-mac-virtualcam#181]
**Describe the bug**
Can't use Mac OS 11.0.

**To Reproduce**

**Expected behavior**
Use Zoom 

**Desktop (please complete the following information):**
 - OS version: Mac OS 11.0
 - Application:Zoom
 - Virtualcam version:1.2.0
 - OBS version: 25.0.8

**Comment by johnboiles** [comment]
Thanks for the report! Did you also try QuickTime? What version of Zoom are you using? They just enabled all virtual cameras in their most recent version released last week?

**Comment by cl0h** [comment]
I had this issue and after some tips here garnered from a different bug report I resolved it by resigning the Zoom app with one additional permission. This will leave you with a second version of the Zoom app that works with John's plugin.
There are useful instructions detailed at [this page](https://www.nicksherlock.com/2020/04/using-a-canon-dslr-as-a-webcam-with-zoom-us/) after the text: "To fix this you need to codesign the zoom.us app "

**Comment by gxalpha** [comment]
Just to clarify, this plugin should work with zoom out of the box now.

@mikage-961pro did it work in 10.15?
If yes, could you check if the `/Library/CoreMediaIO/Plug-Ins/DAL` still exists and if yes, is there a `obs-mac-virtualcam.plugin` file there? We sadly don't have any experience with 10.16 yet and *perhaps* Apple messed with this stuff.
If it is still there, please check Console.app for any logs with `obs-mac-virtualcam` when reproducing the problem and report back 😃

**Comment by mikage-961pro** [comment]
> Thanks for the report! Did you also try QuickTime? What version of Zoom are you using? They just enabled all virtual cameras in their most recent version released last week?

QuickTime is also unavailable. 
![スクリーンショット 2020-07-03 10 33 24](https://user-images.githubusercontent.com/50665049/86422655-adbe0e00-bd18-11ea-9e4c-fe5181898693.png)

![スクリーンショット 2020-07-03 10 33 59](https://user-images.githubusercontent.com/50665049/86422681-b9113980-bd18-11ea-8618-60691f468bd2.png)

**Comment by mikage-961pro** [comment]
> I had this issue on latest Catalina. After confirming Quicktime worked and ensuring I was on the latest Zoom version, I resolved the issue of the OBS virtual camera not showing up in Zoom by re-signing the Zoom app with an additional permission. This will leave you with a second version of the Zoom app that works with John's plugin.
> There are useful instructions to do this detailed at [this page](https://www.nicksherlock.com/2020/04/using-a-canon-dslr-as-a-webcam-with-zoom-us/) after the text: "To fix this you need to codesign the zoom.us app "


It was the same even if I fixed it

![スクリーンショット 2020-07-03 10 43 33](https://user-images.githubusercontent.com/50665049/86423207-37221000-bd1a-11ea-891f-c1bf9b14542d.png)

**Comment by mikage-961pro** [comment]
> did it work in 10.15?

Yes.
It was available in 10.15.


Upload logs such as spin logs.
[log.zip](https://github.com/johnboiles/obs-mac-virtualcam/files/4867346/log.zip)

**Comment by mikage-961pro** [comment]
p.s 
I can use CamTwist for some reason.

**Comment by mikage-961pro** [comment]
I found a solution, so I will write it here.

1. Uninstall OBS
2. Reinstall OBS
3.Run the installer at https://github.com/johnboiles/obs-mac-virtualcam/releases/tag/v1.2.0

Thanks to everyone for taking the consultation.
