### ISSUE TITLE
[BUG] No "Tools -> Start Virtual Camera" menu item in OBS

### ISSUE THREAD

**Issue by noamross** [johnboiles/obs-mac-virtualcam#182]
**Describe the bug**
After installing, restarting my machine and starting OBS, there is no "Start Virtual Camera" menu item uder "Tools" in OBS.  OBS Virtualcam _is_ an available camera for Zoomm, and it shows the inactive screen with the spinning wheel.

**To Reproduce**
1. Start OBS
2. Click on 'Tools' menu item
3. See no menu option

**Expected behavior**
An OBS menu item to appear to start the Virtualcam

**Desktop (please complete the following information):**
 - OS version: macOS Catalina 10.15.4
 - Application: OBS
 - Virtualcam version: obs-mac-virtualcam-3ca8f62-v1.2.0.pkg
 - OBS version: 24.0.6

**Comment by gxalpha** [comment]
You need to use OBS 25 for this plugin.
Download the newest version of OBS on https://obsproject.com/download
