### ISSUE TITLE
[Support]

### ISSUE THREAD

**Issue by jharuni** [johnboiles/obs-mac-virtualcam#184]
OBS doesn't load virtualcam plugin, log file says QtWidgets version is incompatible.

MacOS 10.13.6, OBS 24.0.6, obs-mac-virtualcam 1.2.0

OBS log says: 
13:43:10.388: os_dlopen(/Library/Application Support/obs-studio/plugins/obs-mac-virtualcam/bin/obs-mac-virtualcam.so->/Library/Application Support/obs-studio/plugins/obs-mac-virtualcam/bin/obs-mac-virtualcam.so): dlopen(/Library/Application Support/obs-studio/plugins/obs-mac-virtualcam/bin/obs-mac-virtualcam.so, 257): Library not loaded: @executable_path/../Frameworks/QtWidgets.framework/Versions/5/QtWidgets
13:43:10.388:   Referenced from: /Library/Application Support/obs-studio/plugins/obs-mac-virtualcam/bin/obs-mac-virtualcam.so
13:43:10.388:   Reason: Incompatible library version: obs-mac-virtualcam.so requires version 5.14.0 or later, but QtWidgets provides version 5.10.0

**Comment by gxalpha** [comment]
You need OBS 25 to use this plugin,, older versions aren't supported.
