### ISSUE TITLE
[Support] Cam not available in Discord

### ISSUE THREAD

**Issue by Lucas8do** [johnboiles/obs-mac-virtualcam#186]
**Describe the bug**
I can not find the Virtual Cam in Discord
I have installed all new Versions, but it dose not find the Cam.

**To Reproduce**
1. Go to 'Discord'
2. Click on 'Preferences'
3. Scroll down to 'Video Input'
4. See error (No Virtual Cam)

**Expected behavior**
Discord found the Cam

**Desktop (please complete the following information):**
 - OS version: macOS Catalina 12.15.6
 - Application: Discord
 - Virtualcam version: Newest

**Comment by gxalpha** [comment]
Does it work in Google Chrome and QuickTime Player (or any other program)?

**Comment by Lucas8do** [comment]
> Does it work in Google Chrome and QuickTime Player (or any other program)?

Yes it does.
It works in Zoom, QuickTime and in Chrome.

**Comment by gxalpha** [comment]
Ok, check out this: https://github.com/johnboiles/obs-mac-virtualcam/wiki/Compatibility#apps-dont-allow-dal-plugins
If the solutions there don't work, feel free to reopen the issue, I'll close it for now
