### ISSUE TITLE
[BUG] The virtual webcam (OBS) does not show in hangouts dropdown of video devices

### ISSUE THREAD

**Issue by anilbbiradar** [johnboiles/obs-mac-virtualcam#188]
_Attention: While Zoom says they re-enabled virtual cameras, only certain ones they whitelisted work. Currently, this plugin does not work with Zoom out of the box! See https://github.com/johnboiles/obs-mac-virtualcam/wiki/Compatibility#apps-dont-allow-dal-plugins for a workaround._

**Describe the bug**
I installed the plugin and it appears in the 'Tools' drop down on OBS. When I start the virtual webcam it does not appear in the list of video devices in google hangouts. 

**To Reproduce**
1. Open 'OBS app"
2. Click on 'Tools'
3. Scroll down to 'Start Virtual Camera'
4. Click on 'Start Virtual Camera'

**Expected behavior**
Google hangouts should have the OBS webcam in the video device dropdown. 

**Screenshots**

**Desktop (please complete the following information):**
 - OS version: [macOS Mojave 10.14.6]
 - Application: [ Chrome]
 - Virtualcam version: [obs-mac-virtualcam-3ca8f62-v1.2.0 09-40-59-062]
 - OBS version: [25.0.8 64 bit]

**Additional context**

**Comment by gxalpha** [comment]
Did you restart Chrome and your computer?
If yes, does it work on other websites like meet.jit.si?

**Comment by tharveypa** [comment]
Just installed new OBS and this virtual camera. Tried various orderings of starting virtual camera in OBS and starting Zoom, the virtual camera does not appear in the Zoom camera options.
<img width="387" alt="Screen Shot 2020-07-29 at 8 44 08 PM" src="https://user-images.githubusercontent.com/18314363/88867729-55294600-d1dc-11ea-9465-39a1273b50cd.png">
![Screen Shot 2020-07-29 at 8 42 30 PM](https://user-images.githubusercontent.com/18314363/88867736-578ba000-d1dc-11ea-8d7d-fd80cd5fcf94.png)

**Comment by tofutim** [comment]
Mine still doesn't work. At one point I had to compile my own version and change the camera name and that did the trick. But it should work now right? Out of the box?

**Comment by johnboiles** [comment]
@anilbbiradar were you ever able to get it to work?
