### ISSUE TITLE
[Feature Request] Change default background when Virtual Camera is not started

### ISSUE THREAD

**Issue by Dyphen** [johnboiles/obs-mac-virtualcam#189]
**Is your feature request related to a problem? Please describe.**
If Virtual Camera were in use, if OBS were to crash, the following background would be displayed (shown at bottom).

While helpful for getting started, I wouldn't want participants in a meeting to see this.

**Describe the solution you'd like**

Allow the user to change the default background to nothing (solid black?), or more involved, to set a background (color, picture).

**Describe alternatives you've considered (if applicable)**
N/A

**Additional context**
<img width="1278" alt="image" src="https://user-images.githubusercontent.com/6294998/88859632-1a1d1780-d1c8-11ea-8804-224c4bf9f6e9.png">

**Comment by chancedickson** [comment]
i'd like to take a look into this issue if the maintainers don't mind 🙂

**Comment by johnboiles** [comment]
Go for it!

**Comment by dodgepong** [comment]
Note that in Windows version of the official virtual cam that is now built in to OBS Studio (in v26), the background is a static PNG and can be replaced by users by just replacing the PNG file itself.

**Comment by gxalpha** [comment]
How does it work UX wise?
The problem with macOS is that sandboxed apps aren't really able to access user files and if the host is sandboxed the DAL plugin won't be able to access these files either (at least I don't think it would be). So it would probably need to be sent from OBS meaning to update the png you'd need to at least run something in OBS to send it. This will result in a horrible UX and probably many support requests.
(This all of course only applies if @chancedickson doesn't find another (better) solution)

**Comment by johnboiles** [comment]
This functionality is going into the version that is going to ship along with OBS soon!
