### ISSUE TITLE
[Support] OBS compile fails

### ISSUE THREAD

**Issue by emrecalisir** [johnboiles/obs-mac-virtualcam#195]
Hello,

I receive an error while compiling the OBS virtual cam. Can you please help me with this?

[ 67%] Built target decklink-ouput-ui_autogen
Undefined symbols for architecture x86_64:
  "__Py_Dealloc", referenced from:
      _py_to_libobs_ in obs-scripting-python.c.o
      _libobs_to_py_ in obs-scripting-python.c.o
      _add_functions_to_py_module in obs-scripting-python.c.o
      _add_to_python_path in obs-scripting-python.c.o
      _load_python_script in obs-scripting-python.c.o
      _obs_python_script_update in obs-scripting-python.c.o
      _obs_python_script_unload in obs-scripting-python.c.o
      ...
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: *** [deps/obs-scripting/libobs-scripting.dylib] Error 1
make[1]: *** [deps/obs-scripting/CMakeFiles/obs-scripting.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
[ 70%] Built target decklink-ouput-ui
[ 70%] Built target obs_autogen
make: *** [all] Error 2

It happened on my macOS Catalina 10.15.5 while trying to install OBS Virtual CM from this repository
https://github.com/obsproject/obs-studio.git

I got the error after running this command
cmake .. && make -j 

I appreciate your help. Thank you.

**Comment by gxalpha** [comment]
If you only need to install the virtual camera, use the installer. It can be downloaded [here](). Sadly many tutorials for this are very old.
In case you want to compile it for other reasons, for the error above you just need to rerun `cmake .. && make -j`. It will always throw Error 2, but if it days "Built target obs-studio" you're done.

**Comment by emrecalisir** [comment]
Thank you!
