### ISSUE TITLE
[Feature Request] Act as a Front-facing Camera 

### ISSUE THREAD

**Issue by larvata** [johnboiles/obs-mac-virtualcam#196]
**Describe the issue**
In WebRTC the developer can use `facingMode` property to specify which camera should be used.
https://developer.mozilla.org/en-US/docs/Web/API/MediaTrackConstraints/facingMode

For those sites, only the front-facing camera can be used, 
so obs-mac-virtualcam will not be listed in the camera list.

I don't know how Chrome determining the camera type, 
and also not sure whether it's appropriate to request this feature.

**To Reproduce**
Go to `https://webgazer.cs.brown.edu/calibration.html`
Only the real front-facing camera can be used.

**Desktop (please complete the following information):**
 - OS version: [macOS Catalina 10.14.6]
 - Application (if applicable): [Chrome]
 - Virtualcam version: [1.2.0]
 - OBS version: [25.0.8]

**Comment by johnboiles** [comment]
Interesting. I'm not sure if this is possible with DAL plugins. Can you try [Snap Camera](https://snapcamera.snapchat.com/) and see if that shows up as a front-facing webcam?

**Comment by johnboiles** [comment]
Don't think this is possible. And if it's possible, I'm not totally sure it's desirable. OBS sources aren't necessarily front-facing cameras.
