### ISSUE TITLE
Video sometimes freezes or doesn't initialize in Google Meet

### ISSUE THREAD

**Issue by johnboiles** [johnboiles/obs-mac-virtualcam#2]
This is a weird one. I'm able to see my own preview video just fine in Google Meet in Chrome, and this plugin works totally fine in other Chrome web apps (e.g. Jitsi). But For some reason in Google Meet (at least in Chrome) the person on the other end consistently tells me my video is either frozen or entirely blank.

**Comment by johnboiles** [comment]
I'm kinda stabbing in the dark here since Google Meet's internals are a black box. But in the wise words of @kalmanm timestamps are _always_ the problem so I tried this https://github.com/johnboiles/obs-mac-virtualcam/commit/db3249d99b36d4d427da1147bc91426c6c68ad9d

**Comment by johnboiles** [comment]
Ok I have no idea why but moving to 720p resolution seems to have solved this for me. Maybe Meet does not like low res webcams?

**Comment by johnboiles** [comment]
Going to close this for now since it's been working reliably all afternoon 🎉I'll reopen if I see this again.

**Comment by gianlucahmd** [comment]
Hi John, just installed your plugin but I can't see the new virtual camera on Chrome or any other videoconf service...any idea what may be?

**Comment by gxalpha** [comment]
hi gian, 
1) Was the virtualcam already running when you started Chrome? It needs to be.
2) If it already was, please specify the problem in a new issue, please don't reuse those which are already closed
