### ISSUE TITLE
[Support] camera starts but no device visible

### ISSUE THREAD

**Issue by kschurter** [johnboiles/obs-mac-virtualcam#203]
Virtual webcam is not visible in Zoom, Chrome, Skype when I install OBS and obs-mac-virtualcam without root privileges.

1. Install plugin without admin password by running the following commands in Terminal:

```
pkgutil --expand /path/to/obs-mac-virtualcam-3ca8f62-v1.2.0.pkg ~/virtualcam
cd ~/virtualcam
tar -xvf Payload -C ~
```

2. Open ~/Applications/OBS.app
3. Click Tools > Start Virtual Camera
4. Open Zoom 5.2.1
5. Observe that no virtual camera is available under video settings

The log file shows that frame are being output by the virtual camera, but the device is not visible.
[2020-08-28 15-13-45.txt](https://github.com/johnboiles/obs-mac-virtualcam/files/5143902/2020-08-28.15-13-45.txt)

**Comment by gxalpha** [comment]
Since you need to edit the all-users /Library files (`/Library/CoreMediaIO/Plug-Ins/DAL`) (which are protected) I don't see a way how the installer would run successfully.
Try just double clicking the installer or download the obs-mac-virtualcam.plugin file and move it to `/Library/CoreMediaIO/Plug-Ins/DAL`.
Note that the OBS log only refers to the OBS-plugin, but there are in total two plugins you need to install.

**Comment by kschurter** [comment]
Thanks. I cannot use Apple's installer program because I do not have an admin password. Instead, I avoid writing to `/Library` by using the `-C` flag in order to extract and move the package payload to `$HOME/Library/Application Support/obs-studio/plugins/` and `$HOME/Library/CoreMediaIO/DAL/`.

**Comment by gxalpha** [comment]
To my knowledge, there is no way around the /Library folder (and thus using this without an admin password).

Or did I misunderstand your request and it *did* work? If so, please report back.

**Comment by kschurter** [comment]
The package created all the files it was supposed to, i.e. all the files listed when you press Cmd+I after launching Apple's Installer by double clicking the package. The only difference is that the directories are prefixed with my home directory, instead of being installed at the root. OBS starts up, sees the virtualcam plugin, complains about 'en-US' in the log file, and loads the module anyway. Here is an excerpt:

07:50:12.851: Failed to load 'en-US' text for module: 'obs-mac-virtualcam.so'
07:50:12.851: [obs-mac-virtualcam] version=1.2.0
07:50:12.852: ---------------------------------
07:50:12.852:   Loaded Modules:
07:50:12.852:     obs-mac-virtualcam.so
07:50:12.852:     vlc-video.so
07:50:12.852:     text-freetype2.so
07:50:12.852:     rtmp-services.so
07:50:12.852:     obs-x264.so
07:50:12.852:     obs-vst.so
07:50:12.852:     obs-transitions.so
07:50:12.852:     obs-outputs.so
07:50:12.852:     obs-libfdk.so
07:50:12.852:     obs-filters.so
07:50:12.852:     obs-ffmpeg.so
07:50:12.852:     obs-browser.so
07:50:12.852:     mac-vth264.so
07:50:12.852:     mac-syphon.so
07:50:12.852:     mac-decklink.so
07:50:12.852:     mac-capture.so
07:50:12.852:     mac-avcapture.so
07:50:12.852:     linux-jack.so
07:50:12.852:     image-source.so
07:50:12.852:     frontend-tools.so
07:50:12.852:     decklink-ouput-ui.so
07:50:12.852:     coreaudio-encoder.so
07:50:12.852: ---------------------------------

When I click 'Start Virtual Camera' in OBS, there is nothing written in the log file. If I launch an application like Zoom and try to select the virtual camera, I cannot find it. When I click 'Stop Virtual Camera', three lines such as these are logged:

08:03:14.922: Output 'virtualcam_output': stopping
08:03:14.922: Output 'virtualcam_output': Total frames output: 761
08:03:14.922: Output 'virtualcam_output': Total drawn frames: 762

Maybe there is an environment variable that I need to export before starting OBS? I tried prepending the location of my DAL directory and obs-studio/plugins/obs-mac-virtualcam/bin directory to PATH before launching OBS and Zoom from the Terminal. But that did not fix it.

Thanks for your help. If it is possible to run the plugin after installing it this way, I think it could be helpful to others. If not, I will just persuade my IT admins to give me an admin password.

**Comment by aayore** [comment]
I'm seeing the same thing on two different machines (both 10.15.6 running Zoom 5.2.1).  It may be worth noting that I can see the virtual camera in Google Meet, but not in Zoom.

**Comment by kschurter** [comment]
> Update: full machine reboot and I'm able to see the virtual cam in Zoom.

Glad that worked for you. A reboot did not solve the issue for me. The virtual camera does not appear in Skype or Google Meet, either.

**Comment by gxalpha** [comment]
@kschurter you have a different problem from what @aayore had
To my knowledge you need admin rights, or it won't work.
Simply changing the path won't work, as the OS only checks for .plugins in the folders it expects them to be.
Please try getting admin rights, otherwise the plugin won't work for you I'm afraid :(
Closing this issue now, feel free to reopen it in case the plugin doesn't work with an admin password either.

**Comment by johnboiles** [comment]
Installing virtual cameras requires admin rights for good reason: these DAL virtual camera plugins execute code in the host program that uses the virtual camera. This means, that a bad actor could potentially use a DAL plugin to steal data from other programs on the computer. It would be a vulnerability in macOS to allow non-admin users to install DAL plugins.
