### ISSUE TITLE
OBS Virtual Camera downloads not  working on MAC 10.11.6 El Capitan  [Support]

### ISSUE THREAD

**Issue by benjaminentgroup** [johnboiles/obs-mac-virtualcam#204]
I download the mac link i tried all none have worked. is it my system is to old or am i doing something wrong. I have obs closed when i download, i tried restarting my computer, i tried deleting my obs download new one still nothing when i hit tools no Virtual cam option.

**Comment by gxalpha** [comment]
You need OBS 25+ for this plugin, which unfortunately is only available for macOS 10.13 or higher :(
