### ISSUE TITLE
[Support] Virtual Cam Distorted in Meets

### ISSUE THREAD

**Issue by peteravan** [johnboiles/obs-mac-virtualcam#207]
I'm a complete novice on using OBS and Virtual Cam, so excuse the probable user error that is causing my issue. That said, after I start the virtual camera in OBS and restarted Chrome, I see OBS Virtual Camera as a video device. All good so far. Except once it loads on the screen, I get this crazy distorted image.

![Screen Shot 2020-09-02 at 11 29 09 PM](https://user-images.githubusercontent.com/70681203/92071876-7fd76300-ed75-11ea-86c6-e8e845017c96.png)

I've uninstalled, re-installed, emptied all the cookies, etc. for everything I can think of to no avail. Now I'm stumped.

**Desktop (please complete the following information):**
 - OS version: macOS Catalina 10.15.6
 - Application: Chrome
 - Virtualcam version: latest release (v1.2.0 I think)
 - OBS version: 25.0.8

**Additional context**
My Macbook is old (mid2012), so maybe I just don't have the processing power?

**Comment by gxalpha** [comment]
This is a problem we know of, and don't really know how to fix (at least no one has successfully tried it).
If you already tried reinstalling (with manual deletion), try setting both of your OBS resolutions to 1280*720.
If that doesn't help, there are some janky worksarounds in #160. Also check there for more information about this.
I'm gonna close this as it is a duplicate, but don't hesitate to check back if you have further questions (or found a solution :D)
