### ISSUE TITLE
When using google meet image is stretched out to the left

### ISSUE THREAD

**Issue by mtfirn** [johnboiles/obs-mac-virtualcam#208]
**Describe the bug**
Any scene in OBS when trying to connect to Google Meet gets stretched out and distorted. It is fine in Zoom and other image software.

**To Reproduce**
1. Go to 'Tools'
2. Click on 'Start Virtual Camera'
3. Make a google meet session and select OBS as video input
4. Look at video box.

**Expected behavior**
A normal looking image

**Screenshots**
<img width="751" alt="Screen Shot 2020-09-09 at 6 15 03 PM" src="https://user-images.githubusercontent.com/28830116/92660584-af7ff100-f2c8-11ea-90e0-9b48e3994ad6.png">

**Desktop (please complete the following information):**
 - OS version: [e.g. macOS Catalina 10.15.6]
 - Application: [e.g. Chrome, google meet]
 - Virtualcam version: [e.g. 1.2.0]
 - OBS version: [e.g. 25.0.8]

**Additional context**

**Comment by gxalpha** [comment]
This is a problem we know of, and don't really know how to fix (at least no one has successfully tried it).
If you already tried reinstalling (with manual deletion), try setting both of your OBS resolutions to 1280*720.
If that doesn't help, there are some janky worksarounds in #160. Also check there for more information about this.
I'm gonna close this as it is a duplicate, but don't hesitate to check back if you have further questions
