### ISSUE TITLE
[BUG] Mirrored Text on TestCard is spelled wrong

### ISSUE THREAD

**Issue by simoneves** [johnboiles/obs-mac-virtualcam#209]
**Describe the bug**

The text says "Mirrorred" not "Mirrored".

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Additional context**

**Comment by simoneves** [comment]
I tried to do a PR, but I don't have write access to the repo to push a branch, so I guess I'm doing that wrong.

**Comment by gxalpha** [comment]
You should be able to do a PR.
Have you created a fork, pushed it there and then create a PR with that fork,?

**Comment by johnboiles** [comment]
Wow good eye! How did we miss this for so long

**Comment by simoneves** [comment]
@gxalpha That'll be what I didn't do. Sorry. I'm only really used to using our company private repo on Github.
@johnboiles I have no idea. I spotted it in five seconds, without even using a mirror! ;)

**Comment by simoneves** [comment]
PR up

**Comment by simoneves** [comment]
Really nice work on this project, guys. I'm using it (along with Blackhole for audio) to get OBS into StreamYard so that we can still use StreamYard's really easy (and remotely-controllable) crawls and other graphics.
