### ISSUE TITLE
create OBS branch and/or PR

### ISSUE THREAD

**Issue by gimlids** [johnboiles/obs-mac-virtualcam#21]
I'd love to be able to distribute an OBS version with this built in. Is there a branch somewhere with this inside OBS?

**Comment by gxalpha** [comment]
no.

**Comment by gxalpha** [comment]
The build isn't close to production ready, tho the end goal is to ship is with OBS. Check https://github.com/obsproject/rfcs/pull/15 for further information.

**Comment by johnboiles** [comment]
Definitely that's the goal eventually (see the README) but we've got to work out the kinks first and get buy in from the other OBS devs via the RFC as @gxalpha mentions. If you want to contribute, building simpler DAL code as described in [this comment](https://github.com/johnboiles/obs-mac-virtualcam/issues/15#issuecomment-612373633) is the biggest need right now.
