### ISSUE TITLE
[Feature Request]

### ISSUE THREAD

**Issue by Jay1082** [johnboiles/obs-mac-virtualcam#211]
I wanted to know if there was a way to change the name/rename the webcam for the OBS VirtualCam on Mac. It would be awesome if there was a feature like that because I really need to change the name. Thanks

**Comment by gxalpha** [comment]
If you are not a developer there isn't a way.
If you are willing to recompile the plugin yourself you'd need to rename it in https://github.com/johnboiles/obs-mac-virtualcam/blob/master/src/dal-plugin/Device.mm
