### ISSUE TITLE
[BUG]It does not work with obs-mac-24.0.2-installer.pkg that is compatible with MacOs Elcapitan

### ISSUE THREAD

**Issue by programmer5670** [johnboiles/obs-mac-virtualcam#213]
The virtual cam item does not appear in the Tools menu.
However, when you add sources, the OBS Virtual Cam can be selected but the properties windows shows an image explaining that OBS Virtual Cam is inactive.

Is there a way to activate the Virtual cam in OBS 24.0.2 which is the last releas compatible with Elcapitan?

**Comment by gxalpha** [comment]
No, this unfortunately only works with OBS 25 and higher.
