### ISSUE TITLE
[Feature Request] To make it compatible with OBS 24.0.2 which is the last release compatible with Elcapitan

### ISSUE THREAD

**Issue by programmer5670** [johnboiles/obs-mac-virtualcam#214]
**Is your feature request related to a problem? Please describe.**
There are some systems where it is not possible to update MacOS. For instance Mac Pro Early 2009 only admits Elcapitan so last version of OBS cannot be installed on it.

**Describe the solution you'd like**
To be able to use the virtual camera plugin with OBS 24.0.2 which is the last release compatible with Elcapitan

**Additional context**
The plugin can be installed on MacOS Elcapitan. However the Virtual cam menu item is not shown in the Tools menu.

Log:
Sep 16 19:36:12 Mac-Pro-User com.apple.usbmuxd[80]: notice    Log from 6-d2de38676c8233d96b18b26cdd7968b63eb51817@0xfa400000: handleConnectResult new session to port 5055 failed: 61
Sep 16 19:36:12 Mac-Pro-User obs[3027]: obs-mac-virtualcam(DAL): Server is not available

**Comment by johnboiles** [comment]
I'm definitely not going to work on this. It's likely that using video conferencing while using OBS+VirtualCam would not work on a 2009 computer anyways based on CPU constraints.

That said, this is open source, so if you want to take a stab at it be my guest.

**Comment by programmer5670** [comment]
Thank you for your reply, John. Actually, it would work, as I have been using Parallels Desktop in this same machine with the last version of OBS and virtual cam for windows. So, I used it as a video input for Skype, Google Meet, etc.
However I am not a programmer and cannot modify the code to make the MacOs plugin compatible with Elcapitan and OBS 24.0.2 and to use natively in Mac. I wish I could afford to buy a new computer to use the plugin you have created :-). I have no idea how much it would cost such development or the complexity of it. Nice work, anyway.
