### ISSUE TITLE
[Feature Request] Rename Source Classes

### ISSUE THREAD

**Issue by genkiyooka** [johnboiles/obs-mac-virtualcam#215]
**Describe the bug**
CMIO DAL plug-ins are dylibs loaded into the client's address space.  All Objective-C classes within a single process utilize a single shared namespace.  Therefore, the ObjC classnames ideally should be disambiguated from other classes using a prefixing scheme or similar.  I would suggestion something like JBOBSMacVirtualCamStream instead of Stream and so forth.

**Comment by gxalpha** [comment]
This is interesting. Could you link further documentation regarding this?

**Comment by johnboiles** [comment]
That makes sense to me in theory! But i'd be a little surprised if the system didn't handle this somehow (is there anyway to add namespaces when loading dylibs/plugins?). And I seem to remember I've run this plugin alongside the [boilerplate example](https://github.com/johnboiles/coremediaio-dal-minimal-example/blob/master/CMIOMinimalSample/Stream.mm) I made which has the same class names. It'd be nice to repro this and prove it's actually an issue before we make the names ugly :)

**Comment by johnboiles** [comment]
Yeah as we figured out in #232 this was definitely a real problem. Thanks for reporting @genkiyooka!

**Comment by johnboiles** [comment]
This is done in #242
