### ISSUE TITLE
obs-mac-virtualcam process running all the time after use

### ISSUE THREAD

**Issue by DrRob** [johnboiles/obs-mac-virtualcam#219]
**Describe the bug**
After using obs-mac-virtualcam with OBS Studio to feed video into Zoom, I stop the virtual webcam and then exit OBS Studio, but the logs (seen in the Console application) continue showing a lot of "obs-mac-virtualcam(DAL): Queue is full, bailing out" messages.  The only way I have found to stop this is to reboot the Mac.

**To Reproduce**
1. Open OBS Studio
2. Tools->Start Virtual Camera
3. Use it with Zoom (I guess this step isn't necessary to trigger the problem)
4. Tools->Stop Virtual Camera
5. Quit OBS Studio
6. Look in the Console app for log messages from caphost.

After rebooting the Mac these log messages stop until the next time the virtual webcam is used.

**Expected behavior**
Log messages relating to obs-mac-virtualcam stop.

**Screenshots**
It's just text so I'll copy and paste it here:
default	11:50:05.829618+0100	caphost	obs-mac-virtualcam(DAL): Queue is full, bailing out
default	11:50:05.862759+0100	caphost	obs-mac-virtualcam(DAL): Queue is full, bailing out
default	11:50:05.897028+0100	caphost	obs-mac-virtualcam(DAL): Queue is full, bailing out
default	11:50:05.929821+0100	caphost	obs-mac-virtualcam(DAL): Queue is full, bailing out
default	11:50:05.963771+0100	caphost	obs-mac-virtualcam(DAL): Queue is full, bailing out
default	11:50:05.996324+0100	caphost	obs-mac-virtualcam(DAL): Queue is full, bailing out
default	11:50:06.030343+0100	caphost	obs-mac-virtualcam(DAL): Queue is full, bailing out
default	11:50:06.041673+0100	caphost	obs-mac-virtualcam(DAL): Server is not available
default	11:50:06.062725+0100	caphost	obs-mac-virtualcam(DAL): Queue is full, bailing out
default	11:50:06.096303+0100	caphost	obs-mac-virtualcam(DAL): Queue is full, bailing out
default	11:50:06.129426+0100	caphost	obs-mac-virtualcam(DAL): Queue is full, bailing out
default	11:50:06.163623+0100	caphost	obs-mac-virtualcam(DAL): Queue is full, bailing out
default	11:50:06.196161+0100	caphost	obs-mac-virtualcam(DAL): Queue is full, bailing out
default	11:50:06.230375+0100	caphost	obs-mac-virtualcam(DAL): Queue is full, bailing out
default	11:50:06.262790+0100	caphost	obs-mac-virtualcam(DAL): Queue is full, bailing out
default	11:50:06.296178+0100	caphost	obs-mac-virtualcam(DAL): Queue is full, bailing out
default	11:50:06.329524+0100	caphost	obs-mac-virtualcam(DAL): Queue is full, bailing out
default	11:50:06.362947+0100	caphost	obs-mac-virtualcam(DAL): Queue is full, bailing out
default	11:50:06.395994+0100	caphost	obs-mac-virtualcam(DAL): Queue is full, bailing out
default	11:50:06.430102+0100	caphost	obs-mac-virtualcam(DAL): Queue is full, bailing out
default	11:50:06.462690+0100	caphost	obs-mac-virtualcam(DAL): Queue is full, bailing out
default	11:50:06.496191+0100	caphost	obs-mac-virtualcam(DAL): Queue is full, bailing out
default	11:50:06.529437+0100	caphost	obs-mac-virtualcam(DAL): Queue is full, bailing out
default	11:50:06.562644+0100	caphost	obs-mac-virtualcam(DAL): Queue is full, bailing out
default	11:50:06.596069+0100	caphost	obs-mac-virtualcam(DAL): Queue is full, bailing out
default	11:50:06.629360+0100	caphost	obs-mac-virtualcam(DAL): Queue is full, bailing out
default	11:50:06.662798+0100	caphost	obs-mac-virtualcam(DAL): Queue is full, bailing out
default	11:50:06.697006+0100	caphost	obs-mac-virtualcam(DAL): Queue is full, bailing out
default	11:50:06.729346+0100	caphost	obs-mac-virtualcam(DAL): Queue is full, bailing out
default	11:50:06.763794+0100	caphost	obs-mac-virtualcam(DAL): Queue is full, bailing out
default	11:50:06.796992+0100	caphost	obs-mac-virtualcam(DAL): Queue is full, bailing out
default	11:50:06.829370+0100	caphost	obs-mac-virtualcam(DAL): Queue is full, bailing out
default	11:50:06.862730+0100	caphost	obs-mac-virtualcam(DAL): Queue is full, bailing out
default	11:50:06.896287+0100	caphost	obs-mac-virtualcam(DAL): Queue is full, bailing out
default	11:50:06.929728+0100	caphost	obs-mac-virtualcam(DAL): Queue is full, bailing out
default	11:50:06.962748+0100	caphost	obs-mac-virtualcam(DAL): Queue is full, bailing out
default	11:50:06.996419+0100	caphost	obs-mac-virtualcam(DAL): Queue is full, bailing out
default	11:50:07.030163+0100	caphost	obs-mac-virtualcam(DAL): Queue is full, bailing out
default	11:50:07.041842+0100	caphost	obs-mac-virtualcam(DAL): Server is not available
default	11:50:07.062980+0100	caphost	obs-mac-virtualcam(DAL): Queue is full, bailing out
default	11:50:07.097024+0100	caphost	obs-mac-virtualcam(DAL): Queue is full, bailing out
default	11:50:07.129523+0100	caphost	obs-mac-virtualcam(DAL): Queue is full, bailing out
default	11:50:07.163038+0100	caphost	obs-mac-virtualcam(DAL): Queue is full, bailing out
default	11:50:07.196033+0100	caphost	obs-mac-virtualcam(DAL): Queue is full, bailing out
default	11:50:07.230035+0100	caphost	obs-mac-virtualcam(DAL): Queue is full, bailing out
default	11:50:07.262666+0100	caphost	obs-mac-virtualcam(DAL): Queue is full, bailing out
default	11:50:07.296024+0100	caphost	obs-mac-virtualcam(DAL): Queue is full, bailing out
default	11:50:07.330044+0100	caphost	obs-mac-virtualcam(DAL): Queue is full, bailing out
default	11:50:07.363725+0100	caphost	obs-mac-virtualcam(DAL): Queue is full, bailing out
default	11:50:07.396188+0100	caphost	obs-mac-virtualcam(DAL): Queue is full, bailing out
default	11:50:07.429685+0100	caphost	obs-mac-virtualcam(DAL): Queue is full, bailing out
default	11:50:07.463803+0100	caphost	obs-mac-virtualcam(DAL): Queue is full, bailing out
default	11:50:07.496289+0100	caphost	obs-mac-virtualcam(DAL): Queue is full, bailing out
default	11:50:07.530019+0100	caphost	obs-mac-virtualcam(DAL): Queue is full, bailing out
default	11:50:07.563671+0100	caphost	obs-mac-virtualcam(DAL): Queue is full, bailing out
default	11:50:07.596456+0100	caphost	obs-mac-virtualcam(DAL): Queue is full, bailing out
default	11:50:07.630307+0100	caphost	obs-mac-virtualcam(DAL): Queue is full, bailing out
default	11:50:07.662753+0100	caphost	obs-mac-virtualcam(DAL): Queue is full, bailing out
default	11:50:07.696291+0100	caphost	obs-mac-virtualcam(DAL): Queue is full, bailing out
default	11:50:07.730328+0100	caphost	obs-mac-virtualcam(DAL): Queue is full, bailing out
default	11:50:07.763643+0100	caphost	obs-mac-virtualcam(DAL): Queue is full, bailing out
default	11:50:07.797164+0100	caphost	obs-mac-virtualcam(DAL): Queue is full, bailing out
default	11:50:07.830334+0100	caphost	obs-mac-virtualcam(DAL): Queue is full, bailing out
default	11:50:07.863774+0100	caphost	obs-mac-virtualcam(DAL): Queue is full, bailing out
default	11:50:07.896271+0100	caphost	obs-mac-virtualcam(DAL): Queue is full, bailing out
default	11:50:07.929362+0100	caphost	obs-mac-virtualcam(DAL): Queue is full, bailing out
default	11:50:07.962950+0100	caphost	obs-mac-virtualcam(DAL): Queue is full, bailing out
default	11:50:07.996856+0100	caphost	obs-mac-virtualcam(DAL): Queue is full, bailing out
default	11:50:08.030414+0100	caphost	obs-mac-virtualcam(DAL): Queue is full, bailing out
default	11:50:08.042078+0100	caphost	obs-mac-virtualcam(DAL): Server is not available
default	11:50:08.063901+0100	caphost	obs-mac-virtualcam(DAL): Queue is full, bailing out
default	11:50:08.096040+0100	caphost	obs-mac-virtualcam(DAL): Queue is full, bailing out
default	11:50:08.129287+0100	caphost	obs-mac-virtualcam(DAL): Queue is full, bailing out
default	11:50:08.163635+0100	caphost	obs-mac-virtualcam(DAL): Queue is full, bailing out
default	11:50:08.196068+0100	caphost	obs-mac-virtualcam(DAL): Queue is full, bailing out
default	11:50:08.230010+0100	caphost	obs-mac-virtualcam(DAL): Queue is full, bailing out
default	11:50:08.262835+0100	caphost	obs-mac-virtualcam(DAL): Queue is full, bailing out
default	11:50:08.296951+0100	caphost	obs-mac-virtualcam(DAL): Queue is full, bailing out
default	11:50:08.329423+0100	caphost	obs-mac-virtualcam(DAL): Queue is full, bailing out
default	11:50:08.363610+0100	caphost	obs-mac-virtualcam(DAL): Queue is full, bailing out
default	11:50:08.396008+0100	caphost	obs-mac-virtualcam(DAL): Queue is full, bailing out
default	11:50:08.430303+0100	caphost	obs-mac-virtualcam(DAL): Queue is full, bailing out
default	11:50:08.462651+0100	caphost	obs-mac-virtualcam(DAL): Queue is full, bailing out
default	11:50:08.496285+0100	caphost	obs-mac-virtualcam(DAL): Queue is full, bailing out
default	11:50:08.530311+0100	caphost	obs-mac-virtualcam(DAL): Queue is full, bailing out
default	11:50:08.562779+0100	caphost	obs-mac-virtualcam(DAL): Queue is full, bailing out
default	11:50:08.596061+0100	caphost	obs-mac-virtualcam(DAL): Queue is full, bailing out
default	11:50:08.629322+0100	caphost	obs-mac-virtualcam(DAL): Queue is full, bailing out
default	11:50:08.663634+0100	caphost	obs-mac-virtualcam(DAL): Queue is full, bailing out
default	11:50:08.696957+0100	caphost	obs-mac-virtualcam(DAL): Queue is full, bailing out
default	11:50:08.729351+0100	caphost	obs-mac-virtualcam(DAL): Queue is full, bailing out
default	11:50:08.762778+0100	caphost	obs-mac-virtualcam(DAL): Queue is full, bailing out
default	11:50:08.795979+0100	caphost	obs-mac-virtualcam(DAL): Queue is full, bailing out
default	11:50:08.830281+0100	caphost	obs-mac-virtualcam(DAL): Queue is full, bailing out
default	11:50:08.863642+0100	caphost	obs-mac-virtualcam(DAL): Queue is full, bailing out
default	11:50:08.896910+0100	caphost	obs-mac-virtualcam(DAL): Queue is full, bailing out
default	11:50:08.930258+0100	caphost	obs-mac-virtualcam(DAL): Queue is full, bailing out
default	11:50:08.963581+0100	caphost	obs-mac-virtualcam(DAL): Queue is full, bailing out
default	11:50:08.996210+0100	caphost	obs-mac-virtualcam(DAL): Queue is full, bailing out
default	11:50:09.029300+0100	caphost	obs-mac-virtualcam(DAL): Queue is full, bailing out
default	11:50:09.041613+0100	caphost	obs-mac-virtualcam(DAL): Server is not available
default	11:50:09.062720+0100	caphost	obs-mac-virtualcam(DAL): Queue is full, bailing out
default	11:50:09.096003+0100	caphost	obs-mac-virtualcam(DAL): Queue is full, bailing out
default	11:50:09.129328+0100	caphost	obs-mac-virtualcam(DAL): Queue is full, bailing out
default	11:50:09.163374+0100	caphost	obs-mac-virtualcam(DAL): Queue is full, bailing out
default	11:50:09.195955+0100	caphost	obs-mac-virtualcam(DAL): Queue is full, bailing out
default	11:50:09.229293+0100	caphost	obs-mac-virtualcam(DAL): Queue is full, bailing out

**Desktop (please complete the following information):**
 - OS version: MacOS Catalina 10.15.6
 - Application: obs-mac-virtualcam + OBS Studio + Zoom 
 - Virtualcam version: 1.2.0
 - OBS version: 25.0.8
 - Zoom version: 5.2.3 (45131.0907)

**Additional context**

**Comment by gxalpha** [comment]
This plugin is indeed two separate programs: One is an OBS plugin, the other one is a CoreMedia plugin that gets started with applications that use cameras. The expected behavior is that you shouldn't see these log files if you have zoom closed. If OBS is running doesn't matter at all.
Could you report back if this still happens after you close Zoom (and all programs that use cameras)?

**Comment by DrRob** [comment]
Aaaah, I understand it better now, thank you.  The "Queue is full, bailing out" occurs if I stop sending video in Zoom or end the meeting without first stopping the virtual camera in OBS.  If I stop the virtual camera in OBS after that, these messages continue (which I'm slightly puzzled about - I clearly haven't fully understood how the pieces fit together).  The messages stop when I fully quit Zoom (not just end the meeting).

So it seems that if I don't want to quit Zoom after I end the meeting, the cleanest way to finish the meeting is to stop the virtual camera in OBS first before ending the meeting in Zoom.
