### ISSUE TITLE
Discord and OBS Virtual Camera not showing in Discord Cameras List

### ISSUE THREAD

**Issue by FirePumpkin** [johnboiles/obs-mac-virtualcam#220]
Ran plugin down on Mac
Started OBS
Went to Tools, started OBS Virtual Camera
Opened Discord
Opened User Settings, Video
Selected Camera drop down menu, OBS Virtual Camera is not listed

Restarted all programs, same result

Am I missing something?

**Comment by gxalpha** [comment]
See https://github.com/johnboiles/obs-mac-virtualcam/wiki/Compatibility and follow the steps there.
Please reopen this issue if the problem persists.

**Comment by gxalpha** [comment]
Hey, could you check if there is a file called `obs-mac-virtualcam.plugin` in `/Library/CoreMediaIO/Plug-Ins/DAL/`? (Go there via Finder -> Go to -> Go to folder , then paste the location there)
