### ISSUE TITLE
[BUG] virtualcam picture is blurred / unscharfes Bild

### ISSUE THREAD

**Issue by mschindl** [johnboiles/obs-mac-virtualcam#222]
**Describe the bug**
Virualcam picture is blurred.

Retina display screenshoot:
![image](https://user-images.githubusercontent.com/26382876/94853680-09895780-042c-11eb-8ee3-b143d0edfbdf.png)

Current blurred picture with Google Meet over OBS virtualcam :
![image](https://user-images.githubusercontent.com/26382876/94853736-2160db80-042c-11eb-8764-d362cc9a231a.png)

Screen sharing with Google Meet:
![image](https://user-images.githubusercontent.com/26382876/94854083-a51ac800-042c-11eb-88fc-9c2cc289fd6b.png)

**To Reproduce**

1. open OBS
2. start virtual cam
3. share it on video conference software
-> difference settings didn't help

**Expected behavior**
A clear sharped picture like direct screen sharing from the video conference software like google meet, bluejeans, teams...

**Screenshots**
Settings:
![image](https://user-images.githubusercontent.com/26382876/94852800-b662d500-042a-11eb-9b9c-d208522307b6.png)

![image](https://user-images.githubusercontent.com/26382876/94853014-06da3280-042b-11eb-9c56-18f1c13cf70a.png)

Google Meet:
![image](https://user-images.githubusercontent.com/26382876/94853151-3b4dee80-042b-11eb-86c5-0cff5ec694cc.png)

**Desktop (please complete the following information):**
 - OS version: macOS Catalina 10.15.7
 - Application: Chrome, Bluejeans, Teams
 - Virtualcam version: 1.2.0
 - OBS version: 26.0
- Macbook 16" 2020

**Additional context**
Two cams tested:
- GoPro Hero8
- FaceTime HD Cam

Different settings tested:
- "x264" / Apple VT H264 software encoder / Apple VT H264 hardware encoder
- 1920x1080 / 1280x720
- 60 / 30fps

Internet connection:
![image](https://user-images.githubusercontent.com/26382876/94853276-73edc800-042b-11eb-8957-3ff7542a6e6f.png)

**Comment by dodgepong** [comment]
Screen sharing over Google Meet produces a higher quality image but low framerate, and sends webcam images are low quality but high framerate. This is a problem with Google Meet, not the virtual camera.

**Comment by mschindl** [comment]
That makes sense and it’s usually not the use case to present content over the person view.
