### ISSUE TITLE
Choppy and Laggy Video output (Microsoft Teams)

### ISSUE THREAD

**Issue by GinosergioZ** [johnboiles/obs-mac-virtualcam#223]
I Have a MacBook Air retina 13” (model 9,1)  quadcore intel i5 1,1GHz 8Gb RAM, macOS 10.15.6

I have installed OBS Studio for MAC, ver. 26.0.2
Then I installed Virtualcam plugin v.1.2.0

I wish to use Virtualcam for Microsoft Teams, with a green screen to change my background.  When I go in Teams options, I can select the virtual cam and I see the preview. The video preview starts quite fine, but after some seconds becomes choppy and starts to lag. The lag increase while I watch. After 30 seconds the lag is 8/10 seconds.

I have tried to make a video call with a colleague. He sees my video and he confirm that is choppy and delayed (I also see myself in a small window in Teams)

I have done a Mac reset after install. I have made the OBS Studio Auto-configuration-wizard asking to optimize for recording. It has set canvas resolution to 1440x900, output resolution to 768x480, 30fps (bicubic downscale)

I do not have other apps to test the OBS+VirtualCam output, but I do not think that the problem is related to Teams.

Other things I have to say:
- I own this MAC since few days, I know almost nothing about MAC
- My MAC seems slow in many things, opening apps, even sometime the mouse pointer freeze for 1/2 seconds
- The system fan is often very loud, top speed
- I have a second monitor, LG 4K at native resolution, maybe this is too stressful for the CPU?  (Cpu use by OBS Studio is about 5%)

I wish to understand if this is an issue or it is only a performance problem of my setup / machine, and what can I do to have better result.  I wish to buy one of the apps that allow to use the iPhone as a webcam, to have better video quality, but then if I have to lower the resolution again, that app becomes useless..

Thank you

**Comment by Gring0** [comment]
The same issue on MacBook Pro (15-inch, 2017), 2,9 GHz Intel Core i7, Radeon Pro 560

**Comment by gxalpha** [comment]
@GinosergioZ @Gring0 please send a clean OBS log so I can understand the problem better:
To make a clean log file, please follow these steps:
> 1) Restart OBS
> 2) Start your stream/recording for at least 30 seconds (or however long it takes for the issue to happen). Make sure you replicate any issues as best you can, which means having any games/apps open and captured, etc.
> 3) Stop your stream/recording.
> 4) Select Help > Log Files > Upload Current Log File. Copy the URL and paste it here.
