### ISSUE TITLE
distorted video in Google hangouts

### ISSUE THREAD

**Issue by pixelass** [johnboiles/obs-mac-virtualcam#224]
**Describe the bug**
The video in hangouts is skewed. This happened after the update of OBS.

**To Reproduce**
1. Enable virtual camera in OBS
2. Use obs as video source in google hangouts
3. The output is skewed/sliced/unusable

**Expected behavior**
The video in Google Hangouts should be visible and not distorted

**Screenshots**

<img width="886" alt="Screen Shot 2020-10-09 at 08 51 14" src="https://user-images.githubusercontent.com/1148334/95552224-9de75180-0a0c-11eb-9404-94b33b9b5a9e.png">

**Desktop (please complete the following information):**
 - OS version: macOS 10.15.7 
 - Application: Google Hangouts
 - Virtualcam version: v1.2.0
 - OBS version: 26.0.2

**Comment by pixelass** [comment]
probably the same issue as #160

**Comment by gxalpha** [comment]
Yes, please refer there instead. 
Also no, we don't know how to fix it yet :(
