### ISSUE TITLE
[HELP]Macbook Air 2019 Camera turns VERY NOISY

### ISSUE THREAD

**Issue by danuputra** [johnboiles/obs-mac-virtualcam#227]
after install it my friend's Macbook Air 2019 internal camera turns VERY NOISY

**Comment by gxalpha** [comment]
Please add some more details and fill out the form.

**Comment by johnboiles** [comment]
If you decide to file another issue, please add more details. OBS, and video conferencing in general can use a lot of CPU and cause your fans to run.
