### ISSUE TITLE
[BUG] Crash on CFRetain when DAL plugin is called by another application

### ISSUE THREAD

**Issue by yousifa** [johnboiles/obs-mac-virtualcam#228]
**Describe the bug**
Plugin crashes upon load by application (eg. Quicktime Player or Cameo) at CFRetain in copyBufferQueueWithAlteredProc

**To Reproduce**
1. Compile DAL plugin
2. Copy to /Library/CoreMediaIO/Plug-Ins/DAL folder

**Expected behavior**
Test frame should appear in video app when plugin is selected as virtual camera

**Desktop (please complete the following information):**
 - OS version: e.g. macOS Catalina 10.15.6
 - Application: Quicktime (Crashes), Cameo (Crashes)
 - Virtualcam version: master head
 - OBS version: [e.g. 26.0.0]

**Screenshots**

<img width="938" alt="Screen Shot 2020-10-20 at 12 54 16 AM" src="https://user-images.githubusercontent.com/6870090/96557210-c96d0600-126e-11eb-9186-c204887e0bb4.png">

**Notes**
I can no longer get the pre-built version of the DAL plugin to work in my OS. It behaves in the same manner.

**Comment by yousifa** [comment]
More details from console:

<img width="1348" alt="Screen Shot 2020-10-20 at 9 58 20 AM" src="https://user-images.githubusercontent.com/6870090/96619247-cac42000-12ba-11eb-8f75-2e959a23b978.png">
<img width="1350" alt="Screen Shot 2020-10-20 at 9 58 35 AM" src="https://user-images.githubusercontent.com/6870090/96619281-d3b4f180-12ba-11eb-990c-14a319e30751.png">
<img width="1362" alt="Screen Shot 2020-10-20 at 9 58 49 AM" src="https://user-images.githubusercontent.com/6870090/96619302-dc0d2c80-12ba-11eb-88d7-fa184250846e.png">

**Comment by johnboiles** [comment]
Thanks for reporting and thanks for digging down and capturing the crashing line. Does this happen with the pre-built package as well?

**Comment by yousifa** [comment]
The prebuilt package worked until I built it myself. I then deleted what I built and now the prebuilt crashes with the same problem. 🤷‍♂️

**Comment by yousifa** [comment]
Note: I notice that the camera in Zoom doesn't "start" anymore (I can select it but not activate it) and it just crashes QuickTime on load.

**Comment by johnboiles** [comment]
Did you make sure to completely delete the plugin before installing the pkg? (`sudo rm -rf /Library/CoreMediaIO/Plug-Ins/DAL/obs-mac-virtualcam.plugin`)

I've had some wonky behavior where sometimes the pkg installer doesn't like to overwrite things if they're newer.

**Comment by yousifa** [comment]
Yes, I deleted all my plugins actually and restarted the computer. There are no hidden files in that directory either.

**Comment by johnboiles** [comment]
Very weird. Not necessarily weird that I would have a Core Foundation memory issue (that stuff is hard to get right), but weird that I haven't heard about it from anyone else _and_ it only started after you built from source. Very strange.

**Comment by johnboiles** [comment]
Looking closer i see your line in the logs `Err -12772 in CMSimpleQueueCreate`, that looks like the culprit -- the queue is never created. Googling a bit it [looks like](https://github.com/theos/sdks/blob/master/iPhoneOS11.2.sdk/System/Library/Frameworks/CoreMedia.framework/Headers/CMSimpleQueue.h#L65) that error is `kCMSimpleQueueError_ParameterOutOfRange`.

It looks like the only parameter we give it is fps. Could it be possible at one time you tried to set some crazy FPS and now it's saved in NSUserDefaults? Maybe build the plugin yourself and add some logging to the FPS value [here](https://github.com/johnboiles/obs-mac-virtualcam/blob/4bd585204ae220068bd55eddf7239b9c8fd8b1dc/src/dal-plugin/Stream.mm#L135).

**Comment by yousifa** [comment]
My FPS is NaN, where on a working system it is 0

<img width="643" alt="Screen Shot 2020-10-21 at 2 39 52 PM" src="https://user-images.githubusercontent.com/6870090/96790229-4a311c80-13ab-11eb-9cb4-9881abb035b5.png">

**Comment by yousifa** [comment]
I changed the key "obs-mac-virtualcam-test-card-fps" to another name and it worked!

Where are these keys stored?

Maybe we should check for NaN?

**Comment by johnboiles** [comment]
@yousifa I attempted a fix in #241 can you delete your version and download the pkg-installer from here https://github.com/johnboiles/obs-mac-virtualcam/actions/runs/386450538 and try it out?

**Comment by johnboiles** [comment]
I went ahead and cut a build with the potential fix from #241 in it: https://github.com/johnboiles/obs-mac-virtualcam/releases/tag/v1.3.1

**Comment by johnboiles** [comment]
Ping @yousifa can you try out the fix?

**Comment by yousifa** [comment]
@johnboiles I no longer see the issue. Not sure if its because I changed that value previously or because of your fix. Sorry for the delay here

**Comment by johnboiles** [comment]
Ok let's close for now.
