### ISSUE TITLE
[BUG] Resuming from sleep mode on Mac doesn't restart camera

### ISSUE THREAD

**Issue by mikehatch** [johnboiles/obs-mac-virtualcam#231]
Leaving OBS and virtual camera running for use in various meetings throughout the day, and left running overnight.  When resuming in the morning, the built-in camera is off, and the OBS view is frozen.  To get it going must change cameras in the meeting app (Google Meet) to turn on the camera and get the OBS virtual camera working again and switch back.

**To Reproduce**
1. Go to Google Meet
2. Click on vertical dots in bottom right, Settings, Video
3. Drop down camera options, select FaceTime HD Camera (Built-in)
- Camera turns on
4. Repeat step 3, change back to OBS Virtual Camera

**Expected behavior**
If virtual camera is running and selected in meeting software, camera turns on automatically and starts recording

**Desktop (please complete the following information):**
 - OS version: macOS Catalina 10.15.7
 - Application: OBS, obs-mac-virtualcam, Google Meet
 - Virtualcam version: 1.2.1
 - OBS version: 26.0.2 (64 bit)

**Comment by johnboiles** [comment]
This could be a bug with this plugin, a bug with OBS, or a bug with Chrome. @mikehatch can you try to reproduce with other software? Maybe also watch the logs that include `(DAL)` in Console.app and post them here?
