### ISSUE TITLE
[BUG]Virtual camera can't work with EOS Webcam Utility (Mac OSX Mojave)

### ISSUE THREAD

**Issue by amirher** [johnboiles/obs-mac-virtualcam#232]
Every time I installed this plugin, my OBS can't feed video capture from EOS Webcam utility. In order to get back video feed from EOS Webcam, I need to uninstall this plugin.

**Comment by johnboiles** [comment]
Hmm can you paste the Info.plists from both plugins? In terminal you can run

```bash
cat /Library/CoreMediaIO/Plug-Ins/DAL/obs-mac-virtualcam.plugin/Contents/Info.plist | pbcopy
```

Then paste the results here. And then run

```bash
cat /Library/CoreMediaIO/Plug-Ins/DAL/EOSWebcam.plugin/Contents/Info.plist | pbcopy
```

Then paste here.

**Comment by amirher** [comment]
Ok. I had to reinstall your virtual camera plugin and as expected my EOS webcam utility stops working. 

Anyway, below are the output as requested:
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>CFBundleDevelopmentRegion</key>
	<string>English</string>
	<key>CFBundleExecutable</key>
	<string>obs-mac-virtualcam</string>
	<key>CFBundleIdentifier</key>
	<string>com.johnboiles.obs-mac-virtualcam.dal-plugin</string>
	<key>CFBundleInfoDictionaryVersion</key>
	<string>6.0</string>
	<key>CFBundleName</key>
	<string>OBS Virtual Camera</string>
	<key>CFBundlePackageType</key>
	<string>BNDL</string>
	<key>CFBundleShortVersionString</key>
	<string>1.2.1</string>
	<key>CFBundleVersion</key>
	<string>1.2.1</string>
	<key>CFBundleSupportedPlatforms</key>
	<array>
		<string>MacOSX</string>
	</array>
	<key>CFPlugInFactories</key>
	<dict>
		<key>35FDFF29-BFCF-4644-AB77-B759DE932ABE</key>
		<string>PlugInMain</string>
	</dict>
	<key>CFPlugInTypes</key>
	<dict>
		<key>30010C1C-93BF-11D8-8B5B-000A95AF9C6A</key>
		<array>
			<string>35FDFF29-BFCF-4644-AB77-B759DE932ABE</string>
		</array>
	</dict>
	<key>LSMinimumSystemVersion</key>
	<string>10.13</string>
	<key>CMIOHardwareAssistantServiceNames</key>
	<array>
		<string>com.johnboiles.obs-mac-virtualcam.server</string>
	</array>
</dict>
</plist>

For EOS Webcam :

<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>BuildMachineOSBuild</key>
	<string>19E287</string>
	<key>CFBundleDevelopmentRegion</key>
	<string>English</string>
	<key>CFBundleExecutable</key>
	<string>EOSWebcam</string>
	<key>CFBundleIdentifier</key>
	<string>com.canon.usa.cmio.DAL.EOSWebcam</string>
	<key>CFBundleInfoDictionaryVersion</key>
	<string>6.0</string>
	<key>CFBundleName</key>
	<string>EOSWebcam</string>
	<key>CFBundlePackageType</key>
	<string>BNDL</string>
	<key>CFBundleShortVersionString</key>
	<string>0.0.1.20</string>
	<key>CFBundleSignature</key>
	<string>????</string>
	<key>CFBundleSupportedPlatforms</key>
	<array>
		<string>MacOSX</string>
	</array>
	<key>CFBundleVersion</key>
	<string>0.0.1.20</string>
	<key>CFPlugInFactories</key>
	<dict>
		<key>03C9F749-731F-4F4D-B9CD-9C54C09BBC7D</key>
		<string>CanonCMIODPPlugIn</string>
	</dict>
	<key>CFPlugInTypes</key>
	<dict>
		<key>30010C1C-93BF-11D8-8B5B-000A95AF9C6A</key>
		<array>
			<string>03C9F749-731F-4F4D-B9CD-9C54C09BBC7D</string>
		</array>
	</dict>
	<key>CMIOHardwareAssistantServiceNames</key>
	<array>
		<string>com.canon.usa.cmio.DPA.EOSWebcam</string>
	</array>
	<key>DTCompiler</key>
	<string>com.apple.compilers.llvm.clang.1_0</string>
	<key>DTPlatformBuild</key>
	<string>11E503a</string>
	<key>DTPlatformVersion</key>
	<string>GM</string>
	<key>DTSDKBuild</key>
	<string>19E258</string>
	<key>DTSDKName</key>
	<string>macosx10.15</string>
	<key>DTXcode</key>
	<string>1141</string>
	<key>DTXcodeBuild</key>
	<string>11E503a</string>
	<key>LSMinimumSystemVersion</key>
	<string>10.11</string>
</dict>
</plist>

Hopes these would help you to resolve the issue.

Thanks

**Comment by amirher** [comment]
Ok. I had to reinstall your virtual-camera plugin and as expected my EOS Webcam utility stops working. Anyway as requested attached is the output file of the commands.

[obs-virtualcamera.txt](https://github.com/johnboiles/obs-mac-virtualcam/files/5473487/obs-virtualcamera.txt)

Hopes this could help you to resolve the issue.

Thanks

**Comment by johnboiles** [comment]
Huh this is a strange one. I don't see anything fishy in the plist files.

Does EOS Webcam Utility work in any other apps (e.g. QuickTime, Zoom, etc) while this plugin is installed? Or does it just not work in OBS?

**Comment by amirher** [comment]
Yup. My Zoom works fine and can directly feed from EOS Webcam while OBS doesn't.

**Comment by timbl** [comment]
I am also trying to use bother EOS adapter and OBS virtual webcab.  Wonder whether they re trying to use the same point to insert themselves in the chain.  In the system logs, searching for obs-mac-virtualcam I see a lot of:


Nov 23 17:12:15 cascade10-2 caphost[1522]: objc[1522]: Class Device is implemented in both /Library/CoreMediaIO/Plug-Ins/DAL/EOSWebcamUtility.plugin/Contents/MacOS/EOSWebcamUtility (0x106b69660) and /Library/CoreMediaIO/Plug-Ins/DAL/obs-mac-virtualcam.plugin/Contents/MacOS/obs-mac-virtualcam (0x10701e690). One of the two will be used. Which one is undefined.

Looks like both use the same hack and it clashes ...

**Comment by timbl** [comment]
In fact there seem to be problems with 4 classes: Stream, Device, Plugin and ObjectStore.



MacOS/obs-mac-virtualcam (0xb8356b8). One of the two will be used. Which one is undefined.
Nov 23 17:12:15 cascade10-2 caphost[1522]: objc[1522]: Class ObjectStore is implemented in both /Library/CoreMediaIO/Plug-Ins/DAL/EOSWebcamUtility.plugin/Contents/MacOS/EOSWebcamUtility (0x106b69688) and /Library/CoreMediaIO/Plug-Ins/DAL/obs-mac-virtualcam.plugin/Contents/MacOS/obs-mac-virtualcam (0x10701e5c8). One of the two will be used. Which one is undefined.
Nov 23 17:12:15 cascade10-2 caphost[1522]: objc[1522]: Class PlugIn is implemented in both /Library/CoreMediaIO/Plug-Ins/DAL/EOSWebcamUtility.plugin/Contents/MacOS/EOSWebcamUtility (0x106b69610) and /Library/CoreMediaIO/Plug-Ins/DAL/obs-mac-virtualcam.plugin/Contents/MacOS/obs-mac-virtualcam (0x10701e618). One of the two will be used. Which one is undefined.
Nov 23 17:12:15 cascade10-2 caphost[1522]: objc[1522]: Class Device is implemented in both /Library/CoreMediaIO/Plug-Ins/DAL/EOSWebcamUtility.plugin/Contents/MacOS/EOSWebcamUtility (0x106b69660) and /Library/CoreMediaIO/Plug-Ins/DAL/obs-mac-virtualcam.plugin/Contents/MacOS/obs-mac-virtualcam (0x10701e690). One of the two will be used. Which one is undefined.
Nov 23 17:12:15 cascade10-2 caphost[1522]: objc[1522]: Class Stream is implemented in both /Library/CoreMediaIO/Plug-Ins/DAL/EOSWebcamUtility.plugin/Contents/MacOS/EOSWebcamUtility (0x106b696d8) and /Library/CoreMediaIO/Plug-Ins/DAL/obs-mac-virtualcam.plugin/Contents/MacOS/obs-mac-virtualcam (0x10701e6b8). One of the two will be used. Which one is undefined.

**Comment by timbl** [comment]
The symptom for me is that after installing this  webcam plugin, it doesn't appear in the Tools menu.

**Comment by PatTheMav** [comment]
I'd guess both (EOSWebCamUtility and obs-mac-virtualcam) both used https://github.com/lvsti/CoreMediaIO-DAL-Example as their basis for their code (I know virtualcam is), so they share that part of the code. With ObjC being late-binding, there are now two classes with the same name available and the class lookup will pick one at random.

**Comment by gxalpha** [comment]
@PatTheMav so the information in #215 is correct?

**Comment by PatTheMav** [comment]
I'd say so. ObjectiveC doesn't bind to code sections at compile time, but instead looks up symbols by name at runtime, as everything is translated to variants of `objc_msgSend` in C which takes a string-based selector for the target of your message.

So any plugin based on the minimal example without changing their class names will exist in the namespace of an app that loads DAL plugins and as such the selector will be ambiguous.

**Comment by gxalpha** [comment]
That also means that that problem also exists in the version that currently is in OBS on the main branch, right?
I think I'll need to send a PR there :D

**Comment by PatTheMav** [comment]
Yes and I prepared a PR already, testing the build as we speak.

**Comment by gxalpha** [comment]
oh i see, cool

**Comment by PatTheMav** [comment]
Cameo works great as a test suite, especially as it loads all DAL plugins and gives you debug output.

**Comment by dodgepong** [comment]
If you'd like to test a fix, there's a build artifact of OBS with this plugin pre-installed, with the namespace fix applied here: https://github.com/obsproject/obs-studio/pull/3758 (Go to Checks > CI Multiplatform Build > macOS 64-bit > Artifacts in the upper right corner > choose the macOS .dmg file)

**Comment by johnboiles** [comment]
@timbl @PatTheMav yep that looks like the problem. Interesting find that Canon is using my code! I wonder how many others are too.

@PatTheMav thanks for the fix! I can't wait for that official OBS build with the mac virtualcam built in! @dodgepong @jp9000 do you expect to release OBS w/ macOS virtual cam soon, or should I apply the same fix to this repo as a fix for folks in the meantime?

**Comment by dodgepong** [comment]
We expect a release soon, probably a beta/RC within the next week or two.

**Comment by johnboiles** [comment]
@timbl @amirher can you wait that long? ;)

This plugin will be deprecated/archived as soon as the official OBS release goes out with this code in it.

**Comment by johnboiles** [comment]
I also added a note to my sample code to encourage people to change the class names before shipping https://github.com/johnboiles/coremediaio-dal-minimal-example/blob/master/README.md#before-shipping-code

**Comment by PatTheMav** [comment]
> @timbl @amirher can you wait that long? ;)
> 
> This plugin will be deprecated/archived as soon as the official OBS release goes out with this code in it.

Does the plugin work on macOS 10.12 or 10.11 and older OBS versions? Because then it would be the only way for people to use virtual webcam output on older Macs that OBS 26+ does not support anymore. Still your choice to just "freeze" the plugin as-is.

**Comment by johnboiles** [comment]
I've never really focused on supporting anything below OBS 25.0.8 and macOS below 10.15. So i'm not totally sure. I seem to remember seeing reports of it working on 10.14, but I'd be surprised if it worked on 10.12 without modifications. It definitely wasn't ever a focus of mine.

**Comment by johnboiles** [comment]
Ok I went ahead and fixed the namespaces. @amirher @timbl go try the latest [v1.3.1 release](https://github.com/johnboiles/obs-mac-virtualcam/releases/tag/v1.3.1)!
