### ISSUE TITLE
[BUG]A weird thing happen

### ISSUE THREAD

**Issue by ZiKorT** [johnboiles/obs-mac-virtualcam#234]
**Describe the bug**
When I start the virtual cam I just got this weird thing

Edit: I test with other application and discord is th only one who can't detect the virtual cam
**To Reproduce**
1. I downloaded the plugin
2. I restarted my Mac
3. I started the plugin
4. And I saw the problem

**Expected behavior**
Idk why I see that, maybe a resolution problem or something like this

**Screenshots**
![Capture d’écran 2020-11-16 à 09 09 22](https://user-images.githubusercontent.com/74531873/99228911-97a77a80-27ed-11eb-8e8d-f98fe5e2da9e.jpg)

**Desktop (please complete the following information):**
 - OS version: Mojave 10.14.6
 - Application: Discord
 - Virtualcam version: 1.2.1
 - OBS version: 26.0.2
**Additional context**
Btw thank you if you can help me or just take a look to the problem :)

(I'm french so sorry if I don't speak english very well)

**Comment by gxalpha** [comment]
Check this site, follow the instructions.
https://github.com/johnboiles/obs-mac-virtualcam/wiki/Compatibility
If it still doesnt work after that please reopen the issue
