### ISSUE TITLE
Building script not running on catalina

### ISSUE THREAD

**Issue by ShKlinkenberg** [johnboiles/obs-mac-virtualcam#24]
Hi there, i can't get the build script to run on mac is catalina. I'm getting a kinds of go errors. Do you perhaps have a working script for catalina? 

Best,
Sharon

**Comment by johnboiles** [comment]
Hi Sharon, please provide some kind of log if you need help. Most of us are building on Catalina without errors.

**Comment by ShKlinkenberg** [comment]
Hi John, thanks for the quick response. Mind you, I'm a total noob to building code. You have to give me some instructions on what to do, log wise.

**Comment by johnboiles** [comment]
Hey Sharon, you've to to copy/paste or screenshot whatever errors you see and post them here.

However, this plugin is not in a state that's ready for non-developers to make much use of. It might be best to just hold off until we have some of the issues worked out and make a release pkg build.

**Comment by ShKlinkenberg** [comment]
Dear John,

Thanks again for your quick response. I will hold it off.

I got the following error on running:


cmake .. && make -j

-- OBS_VERSION: 25.0.5-13-gda353103

CMake Error at /usr/local/opt/qt/lib/cmake/Qt5Gui/Qt5GuiConfigExtras.cmake:9 (message):

  Failed to find "gl.h" in

  "/System/Library/Frameworks/OpenGL.framework/Headers;/System/Library/Frameworks/AGL.framework/Headers".

Call Stack (most recent call first):

  /usr/local/opt/qt/lib/cmake/Qt5Gui/Qt5GuiConfig.cmake:202 (include)

  /usr/local/opt/qt/lib/cmake/Qt5Widgets/Qt5WidgetsConfig.cmake:94 (find_package)

  CMakeLists.txt:222 (find_package)

Keep up the great work.

Best,
Sharon
