### ISSUE TITLE
Possibility to install in user Applications

### ISSUE THREAD

**Issue by speekha** [johnboiles/obs-mac-virtualcam#243]
I have OBS installed on a mac, but do not have admin rights on that computer. So I can install apps in my user's Applications folder, but not in the root Applications folder. Installer does not allow to choose the folder to install in.

Installer should allow to select which Applications folder to install in.

**Comment by gxalpha** [comment]
This is not possible since DAL plugins need to go specifically to `/Library/CoreMediaIO/Plug-Ins/DAL/`, which is where the installer puts it to. Otherwise, they won't get recognized by the system.
