### ISSUE TITLE
how to view virtual cam option on mac[Support]

### ISSUE THREAD

**Issue by ddan69** [johnboiles/obs-mac-virtualcam#244]
I install plugin of OBS virtual cam on my Mac OS Big Sur 11.0.1, my OBS release is 26.0.2 (mac).
I can't see virtual cam option but only start virtual cam.
What can I do to see orizontal flip option?
Thanks

**Comment by johnboiles** [comment]
Please fill out the template. Where _specifically_ don't you see the 'virtual cam option'?

**Comment by ddan69** [comment]
![image](https://user-images.githubusercontent.com/75143007/100484190-abab8000-30fb-11eb-8220-b48059a16615.png)

**Comment by ddan69** [comment]
I see only start and stop virtual cam but not option...

**Comment by gxalpha** [comment]
What option are you expecting to see?

**Comment by ddan69** [comment]
![image](https://user-images.githubusercontent.com/75143007/100514302-cd484e00-3173-11eb-91cb-b07fb19fde87.png)
this option... I find this option on Windows plugin but not on Mac plugin

**Comment by gxalpha** [comment]
You only find it in the windows plugin, but since OBS 26 there is a virtual camera built into OBS which also does not have these settings, since they are not relevant and potentially lead the user to shoot themselves in the foot when changing them.

**Comment by ddan69** [comment]
ok thanks!
