### ISSUE TITLE
[BUG] OBS Virtual cam options is missing in all softwares - macOS

### ISSUE THREAD

**Issue by jasin755** [johnboiles/obs-mac-virtualcam#245]
1. Start OBS
2. Select some video source
3. Start Virtual Cam
4. Start MS-Teams, Skype or Discord
5. OBS Virtual cam is missing in camera options.

- MacOS Big Sur

**Comment by hitenmistry75** [comment]
I am having the same issue too.  It doesn't even show as a camera in Mac System Report.

**Comment by gxalpha** [comment]
Which system are you on? Please fill out the issue template

**Comment by hitenmistry75** [comment]
Big Sur 11.01 Intel macbook pro 2020

**Comment by johnboiles** [comment]
MS-Teams, Skype and Discord all disallow virtual cameras. Try chrome or zoom.

**Comment by DerNuntius** [comment]
Same problem here. No logs found.

**Comment by Herbyessen** [comment]
Same on Catalina.

**Comment by Mei-Lewis-Mei** [comment]
Same issue here, Catalina 10.15.7. Virtual camera installed and turned on in OBS but not showing up in any other apps, including zoom.

This page
https://github.com/johnboiles/obs-mac-virtualcam
under the section "Known Issues", the first point says:

"...Start the virtual camera before starting the Zoom application."

I have not been able to do that because I cannot figure out how to.
The installer doesn't say where the app is being installed and it's not in the Applications folder. Where is it please?

**Comment by gxalpha** [comment]
It is not an app that you start, and the information there is somewhat misleading. You need to install the virtual camera first, and then start zoom.

**Comment by Mei-Lewis-Mei** [comment]
Thanks @gxalpha.

I've done that then, and turned on virtual camera in the drop down in OBS, still nothing.
Does anyone know the install location on OSX please?

**Comment by josephmwells** [comment]
Same problem here. No OBS Virtual Cam in any software on any browser, including compatible ones. Opened OBS, started virtual cam, opened video app, no virtual cam option. I'm also having a similar issue as #250 , could that be related?

**Comment by gxalpha** [comment]
@Mei-Lewis-Mei @josephmwells please check this folder for `obs-mac-virtualcam.plugin`:
`/Library/CoreMediaIO/Plug-Ins/DAL`

**Comment by Soundthink1** [comment]
@gxalpha getting the same issue. I checked in /Library/CoreMediaIO/Plug-Ins/DAL and obs-mac-virtualcam.plugin is there.

**Comment by Soundthink1** [comment]
NVM just updated Zoom. Works great thx

**Comment by Ayko1595** [comment]
I also have an issue with finding the virtual cam option in all software (using MacOS Big Sur). Has anyone found a solution to this?

**Comment by wookayin** [comment]
Likely due to #4. If you look at a console log, you might be able to find more detailed information. One very easy way to do so is launch an application from Terminal to see stdout logs:

e.g.
```
$ Applications/Skype.app/Contents/MacOS/Skype 
```

and see if any log messages relevant to `mac-virtualcam`.

**Comment by johnboiles** [comment]
> It doesn't even show as a camera in Mac System Report.

Virtual cameras don't show up in System Report

@hitenmistry75 @DerNuntius @Mei-Lewis-Mei @josephmwells @Ayko1595, we can't help y'all very much if you don't share more specifically what software you're trying to use. Maybe add a screenshot of the camera selector so we can confirm you're looking in the right place.

@wookayin's suggestion is the best way to diagnose. Alternately you can also look in Console.app for logs that mention `mac-virtualcam`.

Make sure to do the things mentioned in the README.md. Specifically: make sure to restart your host software (e.g. Zoom, Chrome), and try restarting your computer.

**Comment by ThomasLvll** [comment]
Hello, same problem for me. Virtual cam is shown into Chrome only. I launched Photo Booth and Microsoft Teams from terminal to look for their logs, and this is what I got:
Photo Booth:
`Photo Booth[5453:1011965] Error loading /Library/CoreMediaIO/Plug-Ins/DAL/obs-mac-virtualcam.plugin/Contents/MacOS/obs-mac-virtualcam:  dlopen(/Library/CoreMediaIO/Plug-Ins/DAL/obs-mac-virtualcam.plugin/Contents/MacOS/obs-mac-virtualcam, 0x0106): code signature in (/Library/CoreMediaIO/Plug-Ins/DAL/obs-mac-virtualcam.plugin/Contents/MacOS/obs-mac-virtualcam) not valid for use in process: mapping process is a platform binary, but mapped file is not`
(no, I didn't cut end of the message)

Microsoft Teams:
`2020-12-13 12:59:32.415 Microsoft Teams Helper (Renderer)[5417:1005260] Error loading /Library/CoreMediaIO/Plug-Ins/DAL/obs-mac-virtualcam.plugin/Contents/MacOS/obs-mac-virtualcam:  dlopen(/Library/CoreMediaIO/Plug-Ins/DAL/obs-mac-virtualcam.plugin/Contents/MacOS/obs-mac-virtualcam, 262): no suitable image found.  Did find:
	/Library/CoreMediaIO/Plug-Ins/DAL/obs-mac-virtualcam.plugin/Contents/MacOS/obs-mac-virtualcam: code signature in (/Library/CoreMediaIO/Plug-Ins/DAL/obs-mac-virtualcam.plugin/Contents/MacOS/obs-mac-virtualcam) not valid for use in process using Library Validation: mapping process and mapped file (non-platform) have different Team IDs
2020-12-13 12:59:32.712 Teams[5405:1004603] Error loading /Library/CoreMediaIO/Plug-Ins/DAL/obs-mac-virtualcam.plugin/Contents/MacOS/obs-mac-virtualcam:  dlopen(/Library/CoreMediaIO/Plug-Ins/DAL/obs-mac-virtualcam.plugin/Contents/MacOS/obs-mac-virtualcam, 262): no suitable image found.  Did find:
	/Library/CoreMediaIO/Plug-Ins/DAL/obs-mac-virtualcam.plugin/Contents/MacOS/obs-mac-virtualcam: code signature in (/Library/CoreMediaIO/Plug-Ins/DAL/obs-mac-virtualcam.plugin/Contents/MacOS/obs-mac-virtualcam) not valid for use in process using Library Validation: mapping process and mapped file (non-platform) have different Team IDs
	/Library/CoreMediaIO/Plug-Ins/DAL/obs-mac-virtualcam.plugin/Contents/MacOS/obs-mac-virtualcam: stat() failed with errno=22
2020-12-13 12:59:32.784 Microsoft Teams Helper (Plugin)[5418:1005385] Error loading /Library/CoreMediaIO/Plug-Ins/DAL/obs-mac-virtualcam.plugin/Contents/MacOS/obs-mac-virtualcam:  dlopen(/Library/CoreMediaIO/Plug-Ins/DAL/obs-mac-virtualcam.plugin/Contents/MacOS/obs-mac-virtualcam, 262): no suitable image found.  Did find:
	/Library/CoreMediaIO/Plug-Ins/DAL/obs-mac-virtualcam.plugin/Contents/MacOS/obs-mac-virtualcam: code signature in (/Library/CoreMediaIO/Plug-Ins/DAL/obs-mac-virtualcam.plugin/Contents/MacOS/obs-mac-virtualcam) not valid for use in process using Library Validation: mapping process and mapped file (non-platform) have different Team IDs
	/Library/CoreMediaIO/Plug-Ins/DAL/obs-mac-virtualcam.plugin/Contents/MacOS/obs-mac-virtualcam: stat() failed with errno=34`

I see many errors, but I don't really know what they mean and how to fix them...

**Comment by gxalpha** [comment]
@ThomasLvll 
To fix teams, check this site: https://github.com/johnboiles/obs-mac-virtualcam/wiki/Compatibility If that doesn't work, see #172 for some workarounds.
On the compatibility site you will also see that Photo Booth does not allow virtual cameras to work, apple *seems* to have disabled them

**Comment by ThomasLvll** [comment]
@gxalpha It looks to work great with Teams now, thank you very much!
Out of curiosity, I also tried on Discord and it makes it unable to open, but nevermind I never use camera on Discord.

**Comment by johnboiles** [comment]
Going to close this since it seems like this is mostly people trying to use the plugin with software that doesn't support virtual cameras.
