### ISSUE TITLE
[Support] Regarding native virtual camera support on 26.1

### ISSUE THREAD

**Issue by wookayin** [johnboiles/obs-mac-virtualcam#246]
I am curious what the diverged codebase of mac virtualcam support will look like. Specifically, I wonder if it is possible to use obs-mac-virtualcam (this repo) despite the built-in virtual camera plugin.

I found the native virtualcam support (starting from 26.1) has a separate codebase imported from your plugin: https://github.com/obsproject/obs-studio/tree/master/plugins/mac-virtualcam/src/dal-plugin. Well, that'd be fine, but OBS 26.1 will require to install their DAL plugin build upon starting a virtual camera for the first time, even though a third-party (i.e. this repo) has been installed. This makes me presume that a custom installation of obs-mac-virtualcam cannot be used within OBS.

That said, if both plugins are incompatible, would this repo be deprecated and new changes will start being added to the core OBS repo? 

I also asked the obs core team about this in the discord channel but wanted to bring this you to your attention too. Thanks.

**Comment by gxalpha** [comment]
> That said, if both plugins are incompatible, would this repo be deprecated from OBS 26.1 and new changes will start being added to the core OBS repo?

That is correct, the current plan is to archive this repo and keep development in the OBS codebase. This repo will have served it purpose ("The goal is for this [...] to eventually be merged into the core OBS codebase 🤞." (README.md)).

> Well, that'd be fine, but OBS 26.1 will require to install their DAL plugin build upon starting a virtual camera for the first time, even though a third-party (i.e. this repo) has been installed. This makes me presume that a custom installation of obs-mac-virtualcam cannot be used within OBS.

While the plugins are not necessarily incompatible (you could probably just rename the DAL plugin, you'd then run into global namespacing issues (see #242), all of that could be solved though), there is no purpose in having both of them.

**Comment by wookayin** [comment]
I see, thanks for the reply. I just missed the last section of README. I also appreciate the great work that has been done by the developers so far!

**Comment by johnboiles** [comment]
Yeah, I'll archive this repo once there's an OBS release that has the virtual camera. I don't see any value to keeping this code duplicated.
