### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by callemusic** [johnboiles/obs-mac-virtualcam#247]
**Describe the bug**
In Meet / Chrome since today the virtual camera view shows a distorted video with diagonal thin green lines.
Worked fine yesterday.
Works fine in Zoom. 

**To Reproduce**
1. Use Chrome Version 87.0.4280.67 (Official Build) (x86_64)
2. Open a  Google Meet
3. Choose OBS virtual cam

**Screenshots**
The fist screenshot shows what happens to the virtual cam default still image when the virtual camera is chosen.

<img width="1383" alt="Screen Shot 2020-11-29 at 10 04 19 PM" src="https://user-images.githubusercontent.com/75224057/100553782-24dbdc00-3290-11eb-9da2-1a9136534f75.png">

The second screenshot shows when I have video content running.

<img width="888" alt="Screen Shot 2020-11-29 at 10 15 07 PM" src="https://user-images.githubusercontent.com/75224057/100553802-5f457900-3290-11eb-844a-4872161adf61.png">

**Desktop (please complete the following information):**
 - OS version: Big Sur 11.0.1
 - Application: Chrome Meets
 - Virtualcam version: 1.3.1
 - OBS version: 26.0.2

**Additional context**

**Comment by johnboiles** [comment]
See the pinned issue on this https://github.com/johnboiles/obs-mac-virtualcam/issues/160

Perhaps skip to the end and try the test build I made to help us debug this.
