### ISSUE TITLE
Compatibility with MS Teams?

### ISSUE THREAD

**Issue by kn1gh7h4wk** [johnboiles/obs-mac-virtualcam#248]
Hello,

I have OBS v26.0.2 with obs-mac-virtualcam v1.3.1 running on the Mac mini M1. Works great on Zoom, but does not show up as a camera in MS Teams v1.3.00.30874. 

Is this expected or should I see it as a camera device in the list?

Thanks!

**Comment by gxalpha** [comment]
First, try out the instructions here: https://github.com/johnboiles/obs-mac-virtualcam/wiki/Compatibility
If that doesn't help, there are some janky workarounds in #172. Also please put all further comments there.
