### ISSUE TITLE
[Feature Request] Virtual audio output

### ISSUE THREAD

**Issue by jarimustonen** [johnboiles/obs-mac-virtualcam#249]
**Is your feature request related to a problem? Please describe.**

I use OBS in Zoom calls. On my setup OBS causes a small delay in video feed causing audio to be out of sync with video.

**Describe the solution you'd like**

I think the most sensible solution would be that virtual camera includes also virtual microphone that is synced with video feed.

**Comment by gxalpha** [comment]
See #125

**Comment by jarimustonen** [comment]
Thank you for the link in previous issue. Would it be possible to link some kind of solution? Many users of virtual cam plugin must have solved it somehow.

**Comment by gxalpha** [comment]
You could probably route it via BlackHole (https://github.com/ExistentialAudio/BlackHole), I do not know any details though.
Also, I haven't heard of any (other) solutions.
