### ISSUE TITLE
[BUG] Virtual Camera screen does not appear when clicking Start Virtual Camera in OBS v26

### ISSUE THREAD

**Issue by bartclaeys** [johnboiles/obs-mac-virtualcam#250]
When I click "Start Virtual Camera" from the Tools menu in OBS 26.0.2, nothing happens. I don't get to see the Virtual Camera screen. When I open the Tools menu again, I see "Stop Virtual Camera". So, I am not sure Virtual Camera is running (it doesn't show up in Google Meet).

 - OS version: macOS Catalina 10.15.7
 - Virtualcam version: 1.3.1
 - OBS version: 26.0.2

**Comment by max-ott** [comment]
Please read https://github.com/johnboiles/obs-mac-virtualcam/wiki/Compatibility and https://github.com/johnboiles/obs-mac-virtualcam/issues/4

**Comment by bartclaeys** [comment]
Max, this link describes compatibility issues with browsers and streaming apps. My post is not around that, it's simply that the Virtual Camera screen does not show up in OBS when enabling it.

**Comment by gxalpha** [comment]
@bartclaeys have you read that page? If so, which apps are you trying to use?

**Comment by bartclaeys** [comment]
Yes, read the page. My problem does not concern any app... My problem is that the "Virtual Camera" window does not open in OBS when I click "Start Virtual Camera" in the menu. That is not an app related problem at all...

**Comment by johnboiles** [comment]
What sort of window are you hoping for?

**Comment by johnboiles** [comment]
@bartclaeys how did you find out about this plugin? All of the sudden we've had a few people reach out in the last couple weeks about a mysterious 'window' that is supposed to show up. I wonder if there's some kind of confusing YouTube video or something that started going around.

**Comment by bartclaeys** [comment]
This is the window: https://cdn.streamshark.io/wp-content/uploads/2020/04/obs-options.png

I've read through blog posts and watches YouTube channels, but too many to remember which one referred to this window.

**Comment by johnboiles** [comment]
That's the old windows virtual camera i think: https://github.com/CatxFish/obs-virtual-cam

**Comment by johnboiles** [comment]
Even for windows users, that's no longer relevant, since OBS now has a built-in windows virtualcamera (and in the next release it will also have a windows virtual camera based on this codebase)
