### ISSUE TITLE
Watched a YouTube video on Windows version of OBS Studio virtual camera and noticed that camera properties include sliders to control Logitech C920S brightness, contrast, sharpness, etc. Will this functionally be added to future Mac virtual camera releases?

### ISSUE THREAD

**Issue by tcross1055** [johnboiles/obs-mac-virtualcam#253]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered (if applicable)**

**Additional context**

**Comment by fperez** [comment]
Not speaking for the dev team, but have you tried using the MacOS "Camera Settings" app? [This link](https://support.logi.com/hc/en-us/articles/360049055854) worked for me to get the current version, but if not you can look for "Camera Settings" in their [general software downloads page](https://support.logi.com/hc/en-us/articles/360024361233):

![image](https://user-images.githubusercontent.com/57394/101427441-bad8bd80-38b3-11eb-9443-afdbcd134c54.png)

I hope this helps in case adding that functionality isn't viable/easy for the dev team!

**Comment by tcross1055** [comment]
Thank you. Somehow I missed this Logitech app. This worked better than the Webcam Settings app I downloaded from the Mac App Store. Look forward to hearing if the development will incorporate camera controls into the Mac version as they have done in the Windows version.

**Comment by johnboiles** [comment]
@tcross1055 do you have a screenshot of what it looks like in the windows version? Seems strange for a virtual camera plugin to control a non-virtual camera’s settings.

**Comment by tcross1055** [comment]
It’s shown in this YouTube video - https://youtu.be/-2ZXlZIm_WI. And the attached screenshot.

![74219F97-A2A2-4E60-8D71-848D148DA36C](https://user-images.githubusercontent.com/75584474/101431521-136c8280-38d5-11eb-9a75-2bd2c6b3c1be.png)

**Comment by dodgepong** [comment]
That functionality is not provided by OBS, it's provided by the camera driver.

**Comment by tcross1055** [comment]
I’m sure that is true. But somehow the functionality is seamlessly integrated into OBS Studio for Windows.
