### ISSUE TITLE
[Support]start obs and virtual cam but doesn't appear anywhere

### ISSUE THREAD

**Issue by 1hrig** [johnboiles/obs-mac-virtualcam#254]
**Describe the issue**
I start obs,virtual cam, but it doesn't shop up in teams, zoom or Skype. What I do wrong? Need help
**To Reproduce**
1. start obs
2. create a new source "video recording"
3. select soby camera(Imaging Edge
4. image appear
5. start virtual cam
6. check that virtual cam actually had started
7. open teams or zoom or Skype
8. only video source I can select is integrated face cam.

**Behavior**
Can only select integrated face cam, instead of my Sony cam.

**Screenshots**

**Desktop:**
 - OS version:  macOS BigSur 11.0.1
 - Application: teams, Skype, zoom
 - Virtualcam version: 1.3.1 (latest installed it today)
 - OBS version:  26.0.2

**Additional context**

**Comment by johnboiles** [comment]
Teams and Skype disable virtual cameras out of the box, but Zoom should work. Can you look for any `obs-mac-virtualcam` logs in Console.app?

Did you try closing and re-opening Zoom? And perhaps restarting?

**Comment by 1hrig** [comment]
now it works. I followed the advise from case #171 

https://answers.microsoft.com/en-us/msteams/forum/msteams_tfb-msteams_tfmac/microsoft-teams-mac-os-client-is-not-recognizing/d9e863be-d9a4-4d03-a4b8-1b5c7df58828

this works very well for me!(Mainly use teams) huge thanks for your fast support!
