### ISSUE TITLE
[Support] Setting of frame delay in virtual camera plugin

### ISSUE THREAD

**Issue by CicoZhang** [johnboiles/obs-mac-virtualcam#255]
**Describe the issue**
Is there a delay of frames between the OBS and virtual camera? For the Windows' plugin, there is a setting to manually set the delay of frames, but I have not found it on Mac. Hopefully there is such a setting.

If there is such a setting, I would set the delay as 0, so OBS and virtual camera are in sync in terms of the video, then I could adjust the delay of audio in the audio interface, so the audio can also be in sync with OBS and virtual camera at the same time.

My usage scenario is streaming to YouTube (via OBS for higher quality) and holding the Zoom meeting (via the virtual camera) at the same time.

**Desktop (please complete the following information):**
 - OS version: macOS Big Sur11.0.1 (Mac Mini M1)
 - Virtualcam version: 1.3.1
 - OBS version: 26.0.2

**Comment by johnboiles** [comment]
So you want a shorter video delay from OBS to the virtual camera, or a longer delay?

**Comment by gxalpha** [comment]
There is no such option on the windows built-in virtualcam, only on the plugin.
This plugin is supposed to be feature-equal with the windows built-in virtualcam, not the plugin.

**Comment by CicoZhang** [comment]
> So you want a shorter video delay from OBS to the virtual camera, or a longer delay?

Hope for a 0 frame delay.

**Comment by johnboiles** [comment]
Well yes. 0 latency is always the goal. But it takes some time to get information between processes.

I have one idea on how to shave off a tiny bit more latency but it seems risky. I documented that idea here: https://github.com/johnboiles/obs-mac-virtualcam/issues/259
