### ISSUE TITLE
[Support]

### ISSUE THREAD

**Issue by TheWonderist** [johnboiles/obs-mac-virtualcam#256]
Virtual Cam is using potentially causing OBS to crash and drain my battery while MacBook Pro is plugged into the wall!

**To Reproduce**
Open OBS
Open Touch Portal
Turn On Virtual Cam
Stream through StreamYard with OBS Virtual cam as webcam input.

**Behavior**
The Camera initially works, but after about 30-45 minutes, the OBS program simply stops, crashes and often causes Mac to reboot, or log out.

**Screenshots**

**Desktop (please complete the following information):**
 - Catalina/Big Sur
 -Chrome, OBS Touch Portal - using web socket plugin (Will report there as well)
 - Latest build as of Monday last week.
 - Latest version

**Additional context**
I have a 2018 MacBook Pro I7 with 16 GB or ram.  OBS, Virtual Cam and possibly web sockets plugin are causing the computer to use so many resources that it crashes or my batter slowly dies... While plugged into the wall.  Battery Drain on a MacBook seems to be a known issue with this combo...

**Comment by TheWonderist** [comment]
Thanks for this email. I’m using a GoPro, through a magewell capture card. Plus 1 iPhone connected through USB. Nothing but issues. I’ve even deleted my hard drive, reformatted it, installed big sur and still have nothing but issues. All frame rates match. 

Chris Funk
The Wonderist

“Irresistible!” - Penn & Teller
“I’ve Never Seen Anything Like That!“  - Simon Cowell - AGT

www.chrisfunkmagic.com

Facebook | LinkedIn | Twitter | YouTube

**Comment by johnboiles** [comment]
What resolution are you using @TheWonderist?

Your system seems capable but you're also doing a lot on it. @tcross1055 is right, sometimes capture cards consume a bunch of resources. I'd start removing different parts of your setup one by one and seeing if the issue persists.

You could also watch memory usage of the various programs you're using in Activity Monitor.app. When things die after a while I tend to think it's some kind of memory link.

**Comment by TheWonderist** [comment]
I’m streaming at 1080p. Using obs to go into StreamYard. I’m using a high end capture card that typically doesn’t even cause my fan to turn on. 

Chris Funk
The Wonderist

“Irresistible!” - Penn & Teller
“I’ve Never Seen Anything Like That!“  - Simon Cowell - AGT

www.chrisfunkmagic.com

Facebook | LinkedIn | Twitter | YouTube

**Comment by johnboiles** [comment]
Closing as we move everything to the core OBS repo.
