### ISSUE TITLE
[Support] Qt Library error with OBS 24.0.6

### ISSUE THREAD

**Issue by nicelifeBS** [johnboiles/obs-mac-virtualcam#257]
I am not able to get the plugin to start with OBS 24.0.6 on macos Sierra. Looks like OBS is compiled with Qt 5.10 but virtualcam needs 5.14. Is there a way to get this to work? Because of macos 10.12 I am kind of stuck with 24.0.6 and cannot upgrade.

Log of startup with loading error
`12:38:08.241: CPU Name: Intel(R) Core(TM) i7-2720QM CPU @ 2.20GHz
12:38:08.241: CPU Speed: 2200MHz
12:38:08.241: Physical Cores: 4, Logical Cores: 8
12:38:08.241: Physical Memory: 8192MB Total
12:38:08.241: OS Name: Mac OS X (NSMACHOperatingSystem)
12:38:08.241: OS Version: Version 10.12.6 (Build 16G2136)
12:38:08.241: Kernel Version: 16.7.0
12:38:08.244: hotkeys-cocoa: Using layout '---------'
12:38:08.245: Portable mode: false
12:38:08.375: OBS 24.0.6 (mac)
12:38:08.375: ---------------------------------
12:38:08.376: ---------------------------------
12:38:08.376: audio settings reset:
12:38:08.376: 	samples per sec: 44100
12:38:08.376: 	speakers:        2
12:38:08.412: ---------------------------------
12:38:08.412: Initializing OpenGL...
12:38:08.428: Loading up OpenGL on adapter Intel Inc. Intel HD Graphics 3000 OpenGL Engine
12:38:08.428: OpenGL loaded successfully, version 3.3 INTEL-10.2.37, shading language 3.30
12:38:08.543: ---------------------------------
12:38:08.543: video settings reset:
12:38:08.543: 	base resolution:   1920x1080
12:38:08.543: 	output resolution: 1920x1080
12:38:08.543: 	downscale filter:  Bicubic
12:38:08.543: 	fps:               30/1
12:38:08.543: 	format:            NV12
12:38:08.543: 	YUV mode:          601/Partial
12:38:08.543: NV12 texture support not available
12:38:08.544: Audio monitoring device:
12:38:08.544: 	name: Default
12:38:08.544: 	id: default
12:38:08.545: ---------------------------------
12:38:08.552: Failed to load 'en-US' text for module: 'decklink-ouput-ui.so'
12:38:08.590: os_dlopen(libpython3.7m.dylib->libpython3.7m.dylib): dlopen(libpython3.7m.dylib, 257): image not found
12:38:08.590: 
12:38:08.590: [Python] Could not load library: libpython3.7m.dylib
12:38:08.776: No blackmagic support
12:38:08.807: [VideoToolbox encoder]: Adding VideoToolbox H264 encoders
12:38:08.915: [obs-browser]: Version 2.7.16
12:38:09.103: Could not func VLC function libvlc_clock, VLC loading failed
12:38:09.103: Ignoring old obs-browser.so version
12:38:09.114: os_dlopen(/Library/Application Support/obs-studio/plugins/obs-mac-virtualcam/bin/obs-mac-virtualcam.so->/Library/Application Support/obs-studio/plugins/obs-mac-virtualcam/bin/obs-mac-virtualcam.so): dlopen(/Library/Application Support/obs-studio/plugins/obs-mac-virtualcam/bin/obs-mac-virtualcam.so, 257): Library not loaded: @executable_path/../Frameworks/QtWidgets.framework/Versions/5/QtWidgets
12:38:09.114:   Referenced from: /Library/Application Support/obs-studio/plugins/obs-mac-virtualcam/bin/obs-mac-virtualcam.so
12:38:09.114:   Reason: Incompatible library version: obs-mac-virtualcam.so requires version 5.14.0 or later, but QtWidgets provides version 5.10.0
12:38:09.114: 
12:38:09.114: Module '/Library/Application Support/obs-studio/plugins/obs-mac-virtualcam/bin/obs-mac-virtualcam.so' not loaded`

**Comment by johnboiles** [comment]
Yeah I think to support old versions of OBS you'd need to compile this plugin yourself. OBS 24 is two major versions behind now, so I'm not going to spend time supporting it.

**Comment by nicelifeBS** [comment]
NP. I thought that this was the case. I will try my best go get it compiled for my old system.
