### ISSUE TITLE
[BUG] Plugin not working on Apple M1

### ISSUE THREAD

**Issue by Autotren** [johnboiles/obs-mac-virtualcam#258]
The plugin doesn't seem to work on the M1 mac mini running Big Sur.

OBS and the plugin install correctly, and I activate the plugin on the Tools menu, but when I open any app that uses webcams, the console throws this error:
`default	18:37:14.128426+0100	QuickTime Player	Error loading /Library/CoreMediaIO/Plug-Ins/DAL/obs-mac-virtualcam.plugin/Contents/MacOS/obs-mac-virtualcam:  dlopen(/Library/CoreMediaIO/Plug-Ins/DAL/obs-mac-virtualcam.plugin/Contents/MacOS/obs-mac-virtualcam, 0x0106): missing compatible arch in /Library/CoreMediaIO/Plug-Ins/DAL/obs-mac-virtualcam.plugin/Contents/MacOS/obs-mac-virtualcam`

`error 18:37:14.128459+0100	QuickTime Player	Cannot find function pointer OBSDALPlugInMain for factory <CFUUID 0x600000d2ada0> 35FDFF29-BFCF-4644-AB77-B759DE932ABE in CFBundle/CFPlugIn 0x12797e400 </Library/CoreMediaIO/Plug-Ins/DAL/obs-mac-virtualcam.plugin> (bundle, not loaded)`

Not even System Information detects the virtual camera.

**Comment by johnboiles** [comment]
Quick Time on Big Sur has removed support for virtual cameras. Try Zoom or Chrome

**Comment by johnboiles** [comment]
Sorry I just took a closer look and saw the `missing compatible arch` thing. What version of the plugin do you have?

**Comment by johnboiles** [comment]
(It still won't work in QuickTime, but that log line shouldn't be there)

**Comment by Autotren** [comment]
Hello, the plugin seems to work fine on Chrome.
I used the lastest version, 1.3.1
