### ISSUE TITLE
$OBS dir

### ISSUE THREAD

**Issue by emmecirm** [johnboiles/obs-mac-virtualcam#26]
Hello,
I was trying to follow all the steps to install your plugin. On my iMac 2010 v10.13 I got an error that I'll post later, now I'm trying to do the same on my laptop (macboopro 2014 v10.14) and I cannot the obs $dir, could you help me how to write \applicazioni\obs in terminal?

TIA,
Mario

**Comment by gxalpha** [comment]
Hi, if you build OBS yourself, you're not installing it in the Applications folder. By default, instead of typing `$OBS_DIR`, you'd fill in `/users/yourusername/obs-studio`. However, could you please specify the error message? That might help solve the error.

**Comment by johnboiles** [comment]
Make sure you set the `OBS_DIR` variable OR follow all the instructions in the README.md

`export OBS_DIR=/path/to/your/obs-studio/clone`

**Comment by johnboiles** [comment]
(@gxalpha thank you for all you've been doing to help others in the issues!!)
