### ISSUE TITLE
Include speex and speexdsp

### ISSUE THREAD

**Issue by ONKOL** [johnboiles/obs-mac-virtualcam#33]
May want to include speex and speexdsp in Brew Install line.  Without them, the Noise Suppression feature will not be available for Audio Inputs (found out hard way, I had speex, but not speexdsp).  Rebuild post install fixed.

**Comment by gxalpha** [comment]
Having audio is currently not the plan here, it was even moved to another RFC.

**Comment by signalwerk** [comment]
@ONKOL you seam to know how to build OBS from scratch and this plugin! Do you know [Travis CI](https://travis-ci.org/) or other CI-Services? Would you like to do a PR for this repo so it gets built automatically with Travis?

**Comment by johnboiles** [comment]
@ONKOL the goal of this plugin is to make a plugin distribution that people can add to their existing OBS builds (without having to worry about how OBS gets built). So including other plugins in the build instructions here is out of the scope of this project. Going to close this.

But! If you'd want to help out with the productionization of this thing go check out the other issues. We could def using help (including with CI as @signalwerk mentions!)
