### ISSUE TITLE
Currently does not work with Discord

### ISSUE THREAD

**Issue by harrisrobin** [johnboiles/obs-mac-virtualcam#37]
Not sure if this is known but Discord is not able to recognize OBS virtual cam. If you go to settings and try to set it as OBS Virtual cam, it shows a black screen. If you try to do it by going live, it doesn't appear as an option at all.

**Comment by johnboiles** [comment]
Thanks for the report! Could you try Snapchat's [Snap Camera](https://snapcamera.snapchat.com/) and make sure it works with Discord? That will help us narrow it down between an issue specific to Discord, or an issue only with this plugin.

**Comment by harrisrobin** [comment]
@johnboiles already tried snap camera (it was my default) and can confirm it works properly with Discord.

Thanks, let me know if I can help in any other way!

**Comment by johnboiles** [comment]
Could you try compiling @gxalpha's branch as well from #11 And then setting your obs output resolution to 1920x1080 to see if it helps?

**Comment by gxalpha** [comment]
Can confirm it doesn't work with my branch either

**Comment by LoYungSum** [comment]
It also doesn't work with Snap Camera

**Comment by johnboiles** [comment]
Would be great if someone wants to start collecting a compatibility list or something. Maybe it's just a markdown table in a COMPATIBILITY.md file or something

**Comment by johnboiles** [comment]
@gxalpha you tried the new DAL plugin with Discord right and it worked?

**Comment by gxalpha** [comment]
Yes, I can confirm it works.
