### ISSUE TITLE
Create place for discussions

### ISSUE THREAD

**Issue by gxalpha** [johnboiles/obs-mac-virtualcam#43]
Hey all, 

I thought about this a bit and I think a proper place for discussion is needed.
The thing about Github is that sending one comment on anything literally pings *everyone* who is watching, thus the mailboxes gets spammed pretty quickly.
As a result, short comments will often not get sent out of fear that you could annoy other people (which you'd probably do), but this - in a way - slows progress.

I thought that it would be helpful to have a development Discord server for this project. My reasons for this are that:
a) the official OBS support also is a Discord server so many people here probably use already
b) it allows for "specific pings". You can decide more precisely what exactly you want pings for and what not
c) it allows for quicker discussions: Answers to something don't need to be long and no-one gets annoyed
d) support questions can be dealt with better. Many people open issues to ask for support on problems that are usually dealt with already, thus again spamming the mailbox. Sometimes these issues won't even get closed, making the issues page chaotic.
e) it has voice channels - although I don't know if they are really needed.

I'm still not sure about if a Discord is really needed, I just wanted to throw the idea out there and wait for your feedback (especially johns). If the results say yes, I could set it up.

**Comment by dataopt** [comment]
I think this is a good idea. What about slack?

**Comment by rcarmo** [comment]
Why not ask the OBS folk for a “dedicated” channel on their Discord? Most of the interested people are likely already there.

**Comment by johnboiles** [comment]
Yah I think a room on the OBS discord would be ideal. Thanks @gxalpha -- it will be good to move tech support out of this space so I can focus time on development.

Thank you @gxalpha for all the work you've done to help others!

**Comment by dodgepong** [comment]
You can use the #plugins-and-tools channel (or #development depending on the question) on the OBS Discord -- I don't see a need for a dedicated channel.

**Comment by Fenrirthviti** [comment]
Also support using those two channels. They are typically pretty bursty in terms of activity, so there shouldn't be any concern about level of activity and ease of following conversations.

**Comment by gxalpha** [comment]
@johnboiles could you add a short note regarding this to readme then? If I did this with my fork it would be combined with the stuff from #11

**Comment by johnboiles** [comment]
Added a note about this to the README.md https://github.com/johnboiles/obs-mac-virtualcam#discussion--support
