### ISSUE TITLE
Step: cmake .. && make -j Not Completing

### ISSUE THREAD

**Issue by reetpetite** [johnboiles/obs-mac-virtualcam#48]
Hello everyone and thanks for the great effort,
when following the _building instructions_ I receive an error
`-- OBS_VERSION: 25.0.7-53-gefc23bb1
-- Found FFmpeg: /usr/local/bin/../lib/libavcodec.dylib (found version "58.54.100") found components:  avcodec avdevice avutil avformat 
-- Luajit support not found.
-- Scripting: Python 3 supported
-- Jansson >=2.5 not found, building bundled version
C compiler: Clang
-- Found FFmpeg: /usr/local/bin/../lib/libavformat.dylib (found version "58.29.100") found components:  avformat avutil swscale swresample avcodec 
-- Using libavcodec for image loading in libobs
-- Could NOT find LibVLC_INCLUDES (missing: VLC_INCLUDE_DIR) 
-- LibVLC includes not found, VLC video plugin disabled
-- Checking for module 'jack'
--   No package 'jack' found
-- JACK Audio Connection Kit not found, disabling JACK plugin
-- Using the bundled VST header.
-- Libfdk not found - obs-libfdk plugin disabled
-- Found FFmpeg: /usr/local/bin/../lib/libavcodec.dylib (found version "58.54.100") found components:  avcodec avfilter avdevice avutil swscale avformat swresample 
-- Found FFmpeg: /usr/local/bin/../lib/libavcodec.dylib (found version "58.54.100") found components:  avcodec avutil avformat 
-- Found ftl-sdk: ftl outputs enabled
-- SpeexDSP support not found
-- Configuring done
-- Generating done
-- Build files have been written to: /Users/***/obs-studio/build
[  0%] Built target obspython_swig_compilation
[  1%] Built target glad
[  4%] Built target jansson
[  5%] Built target obs-ffmpeg-mux
[ 10%] Built target syphon-framework
[ 10%] Built target media-playback
[ 10%] Building C object libobs/CMakeFiles/libobs.dir/util/profiler.c.o
/Users/***/obs-studio/libobs/util/profiler.c:1061:2: error: implicit declaration of function 'gzclose_w' is invalid in C99
      [-Werror,-Wimplicit-function-declaration]
        gzclose_w(gz);
        ^
/Users/***/obs-studio/libobs/util/profiler.c:1061:2: note: did you mean 'gzclose'?
/Library/Frameworks/libz.framework/Headers/zlib.h:1229:24: note: 'gzclose' declared here
ZEXTERN int ZEXPORT    gzclose OF((gzFile file));
                       ^
1 error generated.
make[2]: *** [libobs/CMakeFiles/libobs.dir/util/profiler.c.o] Error 1
make[1]: *** [libobs/CMakeFiles/libobs.dir/all] Error 2
make: *** [all] Error 2`

**Comment by gxalpha** [comment]
This is the obs-build, not the plugin-build, right? Try to enter the command a second time, it should succeed then.

**Comment by kam1092** [comment]
i tried entering the comend a secodn and third time 
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: *** [deps/obs-scripting/libobs-scripting.dylib] Error 1
make[1]: *** [deps/obs-scripting/CMakeFiles/obs-scripting.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
[ 70%] Built target decklink-ouput-ui
[ 93%] Built target obs
make: *** [all] Error 2

**Comment by gxalpha** [comment]
Error 2 means success (for some reason).
If it says "Built target obs" that means it succeeded.

**Comment by reetpetite** [comment]
> This is the obs-build, not the plugin-build, right? Try to enter the command a second time, it should succeed then.

Thanks for getting back, I want to compile obs with the virtual camera plugin for Mac as described on https://github.com/johnboiles/obs-mac-virtualcam

Am I using the wrong build?

**Comment by gxalpha** [comment]
No, you're correct. By using the instructions you will first clone and build OBS and after this clone and build the plugin. 
Just try to type `cmake .. && make -j` two times if it fails at the first attempt.

**Comment by reetpetite** [comment]
> No, you're correct. By using the instructions you will first clone and build OBS and after this clone and build the plugin.
> Just try to type `cmake .. && make -j` two times if it fails at the first attempt.

Thanks, gxalpha, it didn't work

**Comment by reetpetite** [comment]
I am sorry - this issue is unrelated to obs-mac-virtualcam - it is in the part of building obs before the plugin and the problem was my super old zlib library
