### ISSUE TITLE
Does not work with Cisco Webex Meeting Version 40.2.16.14

### ISSUE THREAD

**Issue by budisangithub** [johnboiles/obs-mac-virtualcam#49]
It was working well with Cisco Webex Meeting until last week, and today, it will not work

Cisco Webex Meetings Version 40.2.16.14 
Mac Catalina 10.15.4 

From "Cisco Webex Meetings -> Preferences -> Meeting join options -> Camera", only find "FaceTime HD Camera (Built-In)". All Virtual Camera gone, ie: OBS Camera, Snap Camera, CamTwist 

Similar issue on Skype for Business Mac, https://answers.microsoft.com/en-us/msoffice/forum/all/skype-for-business-no-longer-recognizes-virtual/67553f89-db9c-4935-aa9c-c09a775ddf15

Any workaround ?

**Comment by johnboiles** [comment]
Can you look through the Webex release notes to see if they officially announced removal of virtual cameras? Zoom did this recently (see discussion of Zoom in #4)

**Comment by budisangithub** [comment]
Unfortunately, there is no official announcement in the webex meetings release notes.

**Comment by johnboiles** [comment]
Can you pats the app's plist file?

**Comment by budisangithub** [comment]
plist file attached

<img width="800" alt="image" src="https://user-images.githubusercontent.com/64119588/80553619-17f6c180-89fd-11ea-827c-dae40b1c910a.png">

**Comment by gmdamato** [comment]
Same here... Virtual Cam shows up in any other program (skype, hangouts, etc) but not on webex.
Cisco Webex Meetings Version 40.4.4.14
Mac Catalina 10.15.4

**Comment by xjosh** [comment]
Unsurprisingly same with Webex Teams 3.0.15333.0 (and some versions before this one - have taken a few updates before I reported this). On 10.15.4.

**Comment by budisangithub** [comment]
xjosh. You still can access virtual cam with (a) Webex Teams 3.0.15333.0 (b) Webex Meetings Browser App (i use google chrome browser). 

For Webex Team, please make sure that you activated the OBS virtual camera first, then start your webex team. 

Found other thread, I have also confirmed that if I unsigned ~/Library/Application Support/WebEx Folder//Meeting Place.app/. Launching from /Application/Cisco Webex Meetings.app will change nothing, but launching from ~/Library/Application Support/WebEx Folder//Meeting Place.app/ will allow me to choose the virtual cameras. The problem is, it will only launch my last meeting only.

**Comment by johnboiles** [comment]
Could someone add a note to the https://github.com/johnboiles/obs-mac-virtualcam/blob/master/COMPATIBILITY.md file about how you got Webex running/?

**Comment by johnboiles** [comment]
Going to close this since it's a compatibility issue I don't think we can act on. We're now tracking compatibility in the [wiki](https://github.com/johnboiles/obs-mac-virtualcam/wiki/Compatibility)

**Comment by macbosse** [comment]
Same here... Virtual Cam shows up in any other program (MS Teams, Google Hangouts, etc) but not on webex.
Cisco Webex Meetings Version 40.2.18.5
Mac Catalina 10.15.4

**Comment by gxalpha** [comment]
See the wiki on how to fix this
