### ISSUE TITLE
OBS compile fails - libiconv

### ISSUE THREAD

**Issue by mkarliner** [johnboiles/obs-mac-virtualcam#50]
OS - Mojave.
build transcript

Undefined symbols for architecture x86_64:
  "_libiconv", referenced from:
      _sfnt_name_to_utf8 in find-font-iconv.c.o
  "_libiconv_close", referenced from:
      _sfnt_name_to_utf8 in find-font-iconv.c.o
  "_libiconv_open", referenced from:
      _sfnt_name_to_utf8 in find-font-iconv.c.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: *** [plugins/text-freetype2/text-freetype2.so] Error 1
make[1]: *** [plugins/text-freetype2/CMakeFiles/text-freetype2.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
[ 65%] Built target decklink-ouput-ui_autogen
[ 67%] Built target obs-vst
[ 68%] Built target obslua
[ 68%] Built target _obspython
[ 68%] Built target frontend-tools_autogen
[ 68%] Built target obs_autogen
/Users/mike/Src/obs-studio/plugins/mac-syphon/syphon.m:11:35: error: ARC forbids Objective-C objects in struct
        SYPHON_CLIENT_UNIQUE_CLASS_NAME *client;
                                         ^
1 error generated.

**Comment by gxalpha** [comment]
try https://github.com/johnboiles/obs-mac-virtualcam/issues/48#issuecomment-619617953

**Comment by mkarliner** [comment]
Thanks for the lightening fast reply.

I found the advice referenced and tried it multiple times, no luck.

**Comment by mkarliner** [comment]
This was caused by a mixup between the MacOS versions of libconv and the gnu version. Detailed instructions to fix it are here: https://stackoverflow.com/questions/57734434/libiconv-or-iconv-undefined-symbol-on-mac-osx .
I edited CMakeCache.txt, their are probably better ways.
