### ISSUE TITLE
Photo Booth

### ISSUE THREAD

**Issue by kam1092** [johnboiles/obs-mac-virtualcam#51]
So before testing it online i tried testing it on photo boo i see the OBS vitual camera option but it is not showing my video that i see on obs

**Comment by gxalpha** [comment]
It doesn't work with Photo Booth (See COMPATIBILITY.md).
Try `QuickTime Player -> File -> New Movie` instead

**Comment by kam1092** [comment]
oh okay it works on quicktimes
