### ISSUE TITLE
How to: expose over network

### ISSUE THREAD

**Issue by tam5** [johnboiles/obs-mac-virtualcam#54]
Indirectly related question:

Is there a way to expose the virtualcam output over the local network and then use it (in google hangouts for example) on another machine in the network?

**Comment by dodgepong** [comment]
I don't know of any generally accepted standard way to do this, and I sort of doubt it even exists. Your best bet would be to use something like NDI to output over the network into another instance of OBS, and then output virtualcam from OBS again on the remote computer. There may be a more focused way to do that, some sort of direct NDI-to-virtualcam program in existence.

**Comment by johnboiles** [comment]
thanks for chiming in @dodgepong!

@tam5 this would be a good thing to discuss in the OBS Discord.
