### ISSUE TITLE
Virtual camera makes OBS slow and stream only frozen images (Chrome and QuickTime)

### ISSUE THREAD

**Issue by caduqued** [johnboiles/obs-mac-virtualcam#55]
Hi there,
First thanks for your effort, I have been looking for this for a while. 

Problem: As soon as the "virtual camera plugin" is started, video in Preview becomes slow.  When I checked video seen by Google Chrome or QuickTime, image is completely frozen, and it just update image after a few minutes.

I am using macOS Catalina, and test uses as feed an external webcam (connected to macbook air by USB)

Thanks

Just in case it might help, here it is the output when plugin is stopped:
```
info: Output 'virtualcam_output': stopping
info: Output 'virtualcam_output': Total frames output: 151824
info: Output 'virtualcam_output': Total drawn frames: 153412 (168110 attempted)
info: Output 'virtualcam_output': Number of lagged frames due to rendering lag/stalls: 14698 (8.7%)
info: Video stopped, number of skipped frames due to encoding lag: 64645/151825 (42.6%)
```

**Comment by gxalpha** [comment]
Hi, what type of computer do you have (Specifications as exact as possible)?
It might not have the power to pull this off.

**Comment by caduqued** [comment]
It's a MacBook Air 2018
Processor: 1.6 GHz Dual-Core Intel Core i5
Memory: 8 GB 2133 MHz LPDDR3
Graphics: Intel UHD Graphics 617 1536 MB

**Comment by gxalpha** [comment]
Are you able to do regular recordings or livestreams with your Machines?

**Comment by mtnbrit** [comment]
Im getting the same issue on a 2017 MBP (quad i7 2.9GHz), so it should have enough cpu, right?

I tested if I could make a recording, it hung up when I clicked Stop recording, it says stopping recording... for ever.

**Comment by johnboiles** [comment]
Thanks for the report @mtnbrit. I would definitely expect a quadcore i7 to be up to the task. Do you also get any message in the OBS logs about `encoding lag` like @caduqued mentions?

**Comment by mtnbrit** [comment]
Yep, 

`info: Video stopped, number of skipped frames due to encoding lag: 33500/33551 (99.8%)`

**Comment by johnboiles** [comment]
Interesting. I'm not sure how my code could trigger this. Potentially this is a more broad OBS thing.

We either need to read the OBS code to understand what triggers this. OR we need to find someone who could tell us (maybe in the OBS Discourse). I bet someone with more knowledge of OBS would know off the top of their head what might cause this and know common remediations.

**Comment by mtnbrit** [comment]
I found that I had it set to color space 709. when I set it back to 601, it works normally.

**Comment by johnboiles** [comment]
@caduqued what is your color space set to?

**Comment by caduqued** [comment]
> @caduqued what is your color space set to?

It is set to 601 with Color Range "Partial" and color format NV12

**Comment by johnboiles** [comment]
@caduqued could you try it with the recent [release version 1.1.0](https://github.com/johnboiles/obs-mac-virtualcam/releases) and see if the issue persists? A lot of code changed in the last week.

**Comment by lebravo** [comment]
Im getting the same issue, I try  with the recent release version 1.1.0.  I had a GHz Intel Core i7 double nucleo

**Comment by caduqued** [comment]
@johnboiles  Happy customer here now!!!   Lol... Yes, I can confirm that now it is up and running pretty smooth (at least as far as two instances in google meet).  Yes, it definitively is running without problems... at least from my end!  Thanks a lot!

**Comment by johnboiles** [comment]
@lebravo you're probably using a nonstandard resolution I bet. I'm not sure why, but certain resolutions do that (see #135). I think some rendering systems are sensitive to resolutions that are not multiples of 16 (something about byte alignment or something). Please chime in on #135; I'll be interested to know what resolution you're running.

@caduqued glad to hear it!! Going to close this issue!
