### ISSUE TITLE
missing/different CoreMediaIO paths 

### ISSUE THREAD

**Issue by apolaine** [johnboiles/obs-mac-virtualcam#56]
When I ran the final set of commands to copy the plugins:

`build % sudo rm -rf /Library/CoreMediaIO/Plug-Ins/DAL/obs-mac-virtualcam.plugin && sudo cp -r src/dal-plugin/obs-mac-virtualcam.plugin /Library/CoreMediaIO/Plug-Ins/DAL`

I just get a whole set of `cp: /Library/CoreMediaIO/Plug-Ins/DAL/Contents: No such file or directory` errors. I'm running Catalina on my Macbook that's only about 2 months old. Does anyone else have this? I can only find CoreMediaIO here: `/System/Library/Frameworks/CoreMediaIO.framework/Resources`

The result is, I appear to have built the plug-in and I can toggle Start Virtual Camera in OBS, but the virtual camera never appears anywhere, even when I've set  Zoom entitlements. It doesn't appear in QuickTime to record from either.

**Comment by brinsche** [comment]
the first part of the command deletes the old version of the plugin if there is any, if it wasn't installed previously the first part seems to fail and it doesn't run the second part, just running 
`sudo cp -r src/dal-plugin/obs-mac-virtualcam.plugin /Library/CoreMediaIO/Plug-Ins/DAL` might fix it for the first install

manually moving the plugin to the correct directories with finder should also work

**Comment by apolaine** [comment]
Thanks, I'll give that a go. What about moving it into the frameworks folder or is that entirely the wrong place?

**Comment by gxalpha** [comment]
no, you need to put it into the normal plugins folder

**Comment by apolaine** [comment]
I'll have to make that folder. I have no normal plug-ins folder, which is what I'm also finding strange. I wonder if a CamTwist uninstall nuked it.

**Comment by gxalpha** [comment]
Are you sure? Are you using the right Library?
That really seems strange.

**Comment by apolaine** [comment]
Yes. Also searched everywhere else. Thought it might have been System Integrity Protection in Catalina hiding this, but no. The paths are to the root Library, right? Not System/Library or username/Library? In any case, none of them have CoreMediaIO or plug-in directories. Yet my built-in camera still works...

**Comment by apolaine** [comment]
Creating the directory and then copying into there with  `sudo cp -r src/dal-plugin/obs-mac-virtualcam.plugin /Library/CoreMediaIO/Plug-Ins/DAL` worked though. But I'm still weirded out by my lack of CoreMediaIO directory. Two possible thoughts I'll investigate are whether a CleanMyMacX uninstall of CamTwist deleted the entire thing or whether using Rogue Amoeba's Loopback, which installs the ACE Audio Capture Engine might have moved things around.

**Comment by johnboiles** [comment]
> the first part of the command deletes the old version of the plugin if there is any, if it wasn't installed previously the first part seems to fail and it doesn't run the second part

Are you sure? `rm -f` should succeed even if the file is missing.

**Comment by apolaine** [comment]
The whole /Library/CoreMediaIO directory and its children are missing for me (still no idea why – everything else is working fine), which is why it fails I think.

**Comment by brinsche** [comment]
@johnboiles you're right, I didn't read carefully enough the error message states that it's already at the `cp` step

**Comment by clemkn** [comment]
Same for me /Library/CoreMediaIO directory does not exist... (MacOS Catalina)

**Comment by apolaine** [comment]
So I just installed EpocCam to bring the camera feed from my iPhone into OBS on my Mac as a webcam (works well, by the way). It, too, installs a virtual camera plugin into `/Library/CoreMediaIO/Plug-Ins/DAL`.

So my guess here is that I’m a vanilla install of Catalina as on my new machine, this directory might not be there, but that everyone else trying Virtualcam may have installed CamTwist or similar and/or upgraded from older systems and it’s still there. I don’t really fancy installing a fresh system to check, but it might be worth putting a note in the documentation to create those directories if they’re not already there.

**Comment by clemkn** [comment]
@apolaine I installed and deleted some Virtualcam softwares (including CamTwist) before testing OBS so you are right!

I downloaded EpocCam and the path `/Library/CoreMediaIO/Plug-Ins/DAL` appeared. Then I retried the command ```sudo rm -rf /Library/CoreMediaIO/Plug-Ins/DAL/obs-mac-virtualcam.plugin && sudo cp -r src/dal-plugin/obs-mac-virtualcam.plugin /Library/CoreMediaIO/Plug-Ins/DAL``` and it works! OBS as a virtualcam seems to work now!

So thank you @apolaine :)

**Comment by johnboiles** [comment]
So probably we need to add a `sudo mkdir -p /Library/CoreMediaIO/Plug-Ins/DAL` to our install instructions right?

**Comment by apolaine** [comment]
I think so.

**Comment by johnboiles** [comment]
I think the new `.pkg` installer should create this automatically. Could you delete `/Library/CoreMediaIO/Plug-Ins/DAL` and give it a try?

**Comment by clemkn** [comment]
yes it works! Thank you @johnboiles

**Comment by apolaine** [comment]
Thanks, worked for me too.

**Comment by Raj123456788** [comment]
@johnboiles: @apolaine : Hey Guys, I am seeing weird behavior couple of months ago I built CMIOMinimalSample.plugin and copied to the /Library/CoreMediaIO/Plug-Ins/DAL and I was able to see all the plugins in skype/Teams. But now I don't see them neither in Teams or on Skype. All the plugins still exists under the/Library/CoreMediaIO/Plug-Ins/DAL. Can you please help me to understand why is this happening?

**Comment by Raj123456788** [comment]
Here is the answer: https://answers.microsoft.com/en-us/msteams/forum/all/microsoft-teams-mac-os-client-is-not-recognizing/d9e863be-d9a4-4d03-a4b8-1b5c7df58828?auth=1

**Comment by gxalpha** [comment]
@Raj123456788 see the documentation on https://github.com/johnboiles/obs-mac-virtualcam/wiki/Compatibility
Skype and Teams blocked virtual cameras, you need to do some resigning
