### ISSUE TITLE
Error: Unsupported Resolution

### ISSUE THREAD

**Issue by Setumadhava** [johnboiles/obs-mac-virtualcam#59]
Hi, thanks a lot for creating this. I followed the exact steps to install the virtual cam but when I click on the 'Start Virtual Cam' in tools, I'm getting the following error (screenshot attached):

**Unsupported Resolution
Your output resolution not supported. Please use one of the following:
640x360
720x480
720x486
720x576
1280x720
1920x1080**

I want to use my camera as a webcam for video calls and I've connected my Mac to an external monitor. The issue occurs on the Mac even when it's not connected to the external monitor.

Any suggestions?

![Screen Shot 2020-04-29 at 9 29 12 AM](https://user-images.githubusercontent.com/24946596/80621323-f8ab6480-89fb-11ea-8ab8-8a732ca17ab1.png)

**Comment by gxalpha** [comment]
Suggestion: Go to set the settings, click on the video tab, and use one the listed resolutions for the "scaled output".
It has nothing to do with which monitor you are using, and which camera.
Tip: It will tell you an aspect ratio on right. Make sure your "Base resolution" aspect ratio matches the aspect ratio of the "Scaled resolution" or else it will look ugly.

For further questions, please go to the OBS Discord server, ask your question under #plugins-and-tools and ping me (@gxalpha#3486).

**Comment by dodgepong** [comment]
This issue would be solved if this (https://github.com/johnboiles/obs-mac-virtualcam/issues/6) is implemented, right?

**Comment by gxalpha** [comment]
#6 was considered resolved when #11 was implemented, but yes, in a way it isn't.
I tried a full implementation of #6 in #47.

**Comment by Setumadhava** [comment]
It worked! Thanks for your help! 

However, I want to use this app for video calls on Amazon Chime and Chime doesn't recognize the OBS Virtual cam. Is this a Chime issue or something I can change within OBS? Google Meet recognizes the OBS Virtual Cam.

**Comment by gxalpha** [comment]
Hey,
thanks for reporting. This is probably a compatibility issue with Amazon Chime, check #4 for further information, many people ave experienced this problem with zoom in the past and unfortunately there is no real way to solve it (until the new DAL plugin is implemented).
I'll add it to COMPATIBILITY.md

**Comment by johnboiles** [comment]
We can close this now right?

**Comment by gxalpha** [comment]
Yes

**Comment by gxalpha** [comment]
Can be closed @johnboiles
