### ISSUE TITLE
Build stops at password prompt

### ISSUE THREAD

**Issue by pieter-r** [johnboiles/obs-mac-virtualcam#61]
```
# Remove any existing plugin and copy the DAL plugin to the right place
sudo rm -rf /Library/CoreMediaIO/Plug-Ins/DAL/obs-mac-virtualcam.plugin && sudo cp -r src/dal-plugin/obs-mac-virtualcam.plugin /Library/CoreMediaIO/Plug-Ins/DAL
Password:
Sorry, try again.
Password:
```
When it first prompts the password there is no option to fill in a password, it immediately returns "Sorry, try again."
On the second password prompt, i'm able to fill in my computer's password but it stops the compilation without getting to the Run OBS command
`# Run your build of OBS
cd $OBS_DIR/build/rundir/RelWithDebInfo/bin
./obs`

**Comment by gxalpha** [comment]
You have to type in your password there. It might be irritating that nothing moves, but that is alright and the default for typing in your password in the terminal. After you've typed it, press enter.

**Comment by gxalpha** [comment]
> On the second password prompt, i'm able to fill in my computer's password but it stops the compilation without getting to the Run OBS command
> 
> `# Run your build of OBS cd $OBS_DIR/build/rundir/RelWithDebInfo/bin ./obs`

Could you please specify what happens?

**Comment by pieter-r** [comment]
`# Remove any existing plugin and copy the DAL plugin to the right place
sudo rm -rf /Library/CoreMediaIO/Plug-Ins/DAL/obs-mac-virtualcam.plugin && sudo cp -r src/dal-plugin/obs-mac-virtualcam.plugin /Library/CoreMediaIO/Plug-Ins/DAL
Password:
Sorry, try again.`
Basically Terminal stops here with running the built.
Than the typical Terminal password prompts appears. Where I get to enter my password. 
Earlier when the password was asked I dont have the possibility to enter the password since it is part of the code running and immediatly returning "Sorry Try Again". Since I never entered a password before. It jumps immediately to "Sorry Try Again"

When I enter my password the second time nothing happens. And the built seem to have stopped instead of continuing to the next part in the code, being: `# Run your build of OBS cd $OBS_DIR/build/rundir/RelWithDebInfo/bin ./obs`

**Comment by johnboiles** [comment]
Yeah those instructions are not meant to be a script. But instead instructions you follow one by one.

**Comment by brinsche** [comment]
There seems to be enough demand non-programmers try to built the plugin for themselves, not that there's anything wrong with that, but it may be worth to point people to the nightlies with a giant disclaimer saying that they aren't really supported yet to try to reduce the support burden

**Comment by gxalpha** [comment]
It surely is, but isn't that obvious if you try to build something from github?
I mean, there would be some kind of pre-built--install-only-distribution.
Regarding the disclaimer: I'm with you there, but they are gonna try and ask anyways, so where's the point?

**Comment by brinsche** [comment]
I don't think we can assume any familiarity with github or programming, lots of people probably get linked to the rfc or directly here, see no download link and give up and some try to follow the build instructions and get stuck, it may be that offering a download link could even increase the number of issues with support questions for running instead of building. I just wanted to mention the idea of linking to the prebuilt artifacts.

**Comment by johnboiles** [comment]
> may be worth to point people to the nightlies with a giant disclaimer saying that they aren't really supported yet to try to reduce the support burden
We are now building artifacts but we need someone to write up and test a process for how to use them. See the discussion in #42. We'd really appreciate help with that if you're able.
