### ISSUE TITLE
OBS crashes on start with SIGILL

### ISSUE THREAD

**Issue by HelgeG** [johnboiles/obs-mac-virtualcam#65]
I have followed the build instructions, and on starting obs with the plugin installed, obs immediately crashes with an Illegal Instruction message.

`'./obs' terminated by signal SIGILL (Illegal instruction)`

If I remove the `obs-mac-virtualcam.so` file from the plugin directory, obs runs normally.

Is there anything I can do to troubleshoot better on my side? This is on a machine running High Sierra, and the obs version is OBS 25.0.7-87-g8a1429e2. 

The log doesn't provide many clues, but I enclose it all the same. [2020-05-04 11-25-11.txt](https://github.com/johnboiles/obs-mac-virtualcam/files/4575808/2020-05-04.11-25-11.txt)

**Comment by johnboiles** [comment]
Thanks for the report!

**Comment by HelgeG** [comment]
To test, I booted the same machine with Catalina, and I see the same behaviour there. Again not much info in the log.

[2020-05-06 08-22-14.txt](https://github.com/johnboiles/obs-mac-virtualcam/files/4585315/2020-05-06.08-22-14.txt)

Please let me know if there is anything I can do to help troubleshoot.

**Comment by HelgeG** [comment]
As usual, this was due to pilot error. I was using the brew installed llvm toolchain for the build. Switching to the XCode version of clang, it works. Sorry for raising the alarm.

**Comment by johnboiles** [comment]
Thanks for following up
