### ISSUE TITLE
Error 2

### ISSUE THREAD

**Issue by SGS01** [johnboiles/obs-mac-virtualcam#67]
Can somebody help me with this???

bo1853@iai-pia009 build % make .. & make -j
[1] 16913
[1]  + done       make ..
[  0%] Built target obspython_swig_compilation
[  1%] Built target glad
[  4%] Built target jansson
[  5%] Built target obs-ffmpeg-mux
[ 10%] Built target syphon-framework
[ 10%] Built target media-playback
[ 29%] Built target libobs
[ 29%] Built target mac-avcapture
[ 30%] Built target mac-vth264
[ 31%] Built target coreaudio-encoder
[ 31%] Automatic MOC for target obs-vst
[ 32%] Built target mac-syphon
[ 33%] Built target image-source
[ 34%] Built target obs-x264
[ 38%] Built target libobs-opengl
[ 40%] Built target mac-capture
[ 42%] Built target text-freetype2
[ 45%] Built target obs-transitions
[ 47%] Built target obs-ffmpeg
[ 47%] Built target obs-frontend-api
[ 49%] Built target file-updater
[ 52%] Built target obs-filters
[ 57%] Built target mac-decklink
[ 63%] Built target obs-outputs
[ 63%] Built target obs-vst_autogen
[ 63%] Automatic MOC for target obs
[ 63%] Automatic MOC for target decklink-ouput-ui
[ 65%] Built target rtmp-services
[ 67%] Built target obs-vst
[ 67%] Linking CXX shared library libobs-scripting.dylib
[ 67%] Built target decklink-ouput-ui_autogen
[ 67%] Built target obs_autogen
Undefined symbols for architecture x86_64:
  "_PyObject_CallFunction", referenced from:
      _SwigPyObject_dealloc in obs-scripting-python.c.o
     (maybe you meant: _Import_PyObject_CallFunctionObjArgs)
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: *** [deps/obs-scripting/libobs-scripting.dylib] Error 1
make[1]: *** [deps/obs-scripting/CMakeFiles/obs-scripting.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
[ 70%] Built target decklink-ouput-ui
[ 93%] Built target obs
make: *** [all] Error 2
bo1853@iai-pia009 build % make
[  1%] Built target glad
[  1%] Built target media-playback
[  4%] Built target jansson
[ 23%] Built target libobs
[ 23%] Built target file-updater
[ 23%] Built target obs-frontend-api
[ 23%] Linking CXX shared library libobs-scripting.dylib
Undefined symbols for architecture x86_64:
  "_PyObject_CallFunction", referenced from:
      _SwigPyObject_dealloc in obs-scripting-python.c.o
     (maybe you meant: _Import_PyObject_CallFunctionObjArgs)
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: *** [deps/obs-scripting/libobs-scripting.dylib] Error 1
make[1]: *** [deps/obs-scripting/CMakeFiles/obs-scripting.dir/all] Error 2
make: *** [all] Error 2
bo1853@iai-pia009 build %

**Comment by johnboiles** [comment]
Please go to the OBS Discord to get support on building OBS.
