### ISSUE TITLE
typo in build instructions

### ISSUE THREAD

**Issue by mtnbrit** [johnboiles/obs-mac-virtualcam#69]
There is minor typo in the build instructions I found when copy and pasting the commands, there needs to be a space before the .. at the end of the cmake line, otherwise it fails for me with 

`CMake Error: The source directory "/Users/foo/obs-mac-virtualcam/build" does not appear to contain CMakeLists.txt.`

**Comment by johnboiles** [comment]
Thanks for the report. Looks like it was introduced in #66. Fixed now!
