### ISSUE TITLE
Doesn't work with Facetime

### ISSUE THREAD

**Issue by mkarliner** [johnboiles/obs-mac-virtualcam#71]
Facetime on High Sierra.
Sees the OBS Virtual camera and can select it,
but appears stay connected to the built in  camera.

**Comment by gxalpha** [comment]
Thanks for reporting!
Added to Compatibility (#73)

**Comment by anilv** [comment]
Adding in another one. Catalina 10.15.4

Works great with Zoom, Hangouts, etc. but Facetime doesn't see the camera. 

![image](https://user-images.githubusercontent.com/680493/81619309-24383280-939e-11ea-8eb7-18eec2720d98.png)

**Comment by johnboiles** [comment]
Yah Facetime doesn't allow 3rd party DAL plugins as of either Mojave or Catalina. And I dont think we're going to be able to support High Sierra with this plugin (though if someone wants to take that on, I'd welcome the contribution!!)

**Comment by dodgepong** [comment]
What are the additional challenges of developing support for High Sierra for this plugin?

**Comment by johnboiles** [comment]
No idea! Probably you need to set some compiler flags to tell it to support older runtimes maybe, and you might also need some code changes to use different APIs at runtime. But I haven't done this before!

**Comment by johnboiles** [comment]
Repurposed #85 to track support for macOS < 10.15
