### ISSUE TITLE
installer got into endless loop - ? issue with Saffire

### ISSUE THREAD

**Issue by tommybananadrums** [johnboiles/obs-mac-virtualcam#72]
Hi when installing Homebrew got stuck showing this message in Terminal:

warning: [input_callback]:[device 'Saffire'] audio retrieval failed: -10876

NB Saffire is my sound card!

so had to terminate process. Tried to reinstall having disconnected  sound cards but still same outcome.

**Comment by johnboiles** [comment]
Sorry supporting homebrew is out of scope for this project. Maybe go talk to the homebrew people
