### ISSUE TITLE
Browser Source plug-in not installed

### ISSUE THREAD

**Issue by jburbs** [johnboiles/obs-mac-virtualcam#79]
Please forgive yet-another-naive question, but I've built OBS and virtual-cam works weil, but now I want to use a browser window as background. OBS says this should be an available source, but the build doesn't have it (tested with latest OBS direct download, OBS Studio 25.0.8, and it's there and functional). But the source isn't available in the version built from guide here.  It seems that it needs to be added during the build, but for the life of me I can't find out how.  Thanks in advance for your patience! Love the result.

**Comment by johnboiles** [comment]
Try out the brand new package distribution as it works with the directly downloaded OBS (see the updated README.md). Supporting the browser source plugin is out of scope for this repo.

**Comment by jburbs** [comment]
Works great! Thanks. Also sent you a $20 PayPal, awesome work.

**Comment by johnboiles** [comment]
Thank you @jburbs!!
