### ISSUE TITLE
OBS needs to be restarted after changing resolutions

### ISSUE THREAD

**Issue by johnboiles** [johnboiles/obs-mac-virtualcam#83]
This is a bug with v1.0.0. Not a huge deal since you have to stop/start the output anyways to change resolution, but I noticed you have to restart OBS if you change resolutions.

**Comment by jmcalalang** [comment]
Is there a list of supported resolutions? It looked like @gxalpha was making one in a branch that was maybe left behind. There are some hardcoded settings in the stream file, which I believe were also noted as not doing anything. I think if it was working up to 1080, I might run into that other blank screen issue. However, I still wanted to try.

![Properties_for__GoPro_Hero_6_](https://user-images.githubusercontent.com/20847865/81782122-34d7ce00-94ae-11ea-9aba-c5e24076dcfe.png)

**Comment by gxalpha** [comment]
Every output resolution should be supported.

**Comment by Jip-Hop** [comment]
When I set my OBS base and output resolution to 1024x576, restart OBS and start the Virtual Camera, then the virtual camera source outputs at 1280x720.

My Canon M50 camera outputs at 1024x576 via Syphon when using [Camera Live](https://github.com/v002/v002-Camera-Live). I can get it into OBS and want to use it as a webcam for streaming. For this reason I'd rather have the webcam at the exact max resolution output from the Canon camera, else the upscaling will add more (upload) overhead.

I've checked the reported resolution of the virtual camera with [this](https://webrtchacks.github.io/WebRTC-Camera-Resolution/) tool, and also by adding the virtual camera to OBS via Video Capture Device source.

Is it possible to get custom resolution output working?

Anyhow great work so far 👍 I'm so glad there's finally an OBS virtual webcam plugin for the Mac 😄

**Comment by gxalpha** [comment]
Huh, that's weird.

Is the resolution also 720 if you record a movie in QuickTime Player?

**Comment by Jip-Hop** [comment]
Well, that's interesting. QuickTime does record in 1024 x 576, albeit [only a couple of frames](https://github.com/johnboiles/obs-mac-virtualcam/issues/91). Maybe it's a browser specific thing... but like I said adding the virtual camera to the OBS scene (obviously this creates a feedback loop) via a Video Capture Device source also adds it at 720p (checked by right clicking the source and Edit Transform).

**Comment by jmcalalang** [comment]
I think @Jip-Hop and I might be talking about the same thing, I pump any input resolution into OBS, but coming out is hard set at 720. This is/should be expected? Quicktime, Zoom, Just OBS recording all show the same

**Comment by johnboiles** [comment]
I think I fixed this in #147. Could y'all test it out by downloading the latest `pkg` build [here](https://github.com/johnboiles/obs-mac-virtualcam/actions/runs/116484810). Start a new movie recording in quicktime, start/stop the virtualcam a few times, maybe change the resolution in between, and let me know if you get this error.

**Comment by Jip-Hop** [comment]
I can confirm that recording in QuickTime works with the latest `pkg` build. It records fin in my custom resolution of 1024x576.

But in the browser it still goes for 720p. Not sure if this is caused by `obs-mac-virtualcam`, but according to [the WebRTC Troubleshooter](https://test.webrtc.org/) the OBS Virtual Camera supports the following resolutions:

```
Check supported resolutions
[ OK ] Supported: 160x120
[ OK ] Supported: 160x120
[ OK ] Supported: 320x180
[ OK ] Supported: 320x240
[ OK ] Supported: 640x360
[ OK ] Supported: 640x480
[ OK ] Supported: 768x576
[ OK ] Supported: 1024x576
[ OK ] Supported: 1280x720
[ INFO ] 1280x768 not supported
[ INFO ] 1280x800 not supported
[ INFO ] 1920x1080 not supported
[ INFO ] 1920x1200 not supported
[ INFO ] 3840x2160 not supported
[ INFO ] 4096x2160 not supported
```

The surprise here is that it reports supporting 1280x720, even though the video resolution in OBS is set to 1024x576 (both base and output) and QuickTime records at 1024x576. I was hoping it would 'max out' at 1024x576 in this scenario.

For comparison these are the resolutions reported by my 1080p USB webcam:

```
Check supported resolutions
[ OK ] Supported: 160x120
[ OK ] Supported: 160x120
[ OK ] Supported: 320x180
[ OK ] Supported: 320x240
[ OK ] Supported: 640x360
[ OK ] Supported: 640x480
[ OK ] Supported: 768x576
[ OK ] Supported: 1024x576
[ OK ] Supported: 1280x720
[ OK ] Supported: 1280x768
[ OK ] Supported: 1280x800
[ OK ] Supported: 1920x1080
[ INFO ] 1920x1200 not supported
[ INFO ] 3840x2160 not supported
[ INFO ] 4096x2160 not supported
```

**Comment by johnboiles** [comment]
Interesting!! Could you post any Console.app OBSDAL logs when you run the troubleshooter?

**Comment by gxalpha** [comment]
Doesn't seem to change anything, still `bad scale conversion type`, doesn't show up
https://obsproject.com/logs/NS7Ab6-rgMcD0TE6

When string the camera for the first time, Console.app changed the regular logs from a repeating `OBSDAL: Server is not available` to 
```
OBSDAL: Attempting connection
OBSDAL: -[MachClient connectToServer]
OBSDAL: Initialized mach port 22027 for receiving
```
but then also a repeating 
```
OBSDAL: Attempting connection
OBSDAL: -[MachClient connectToServer]
```
For the sake of completeness: I am on [this](https://github.com/gxalpha/obs-mac-virtualcam/commits/master) version.

**Comment by johnboiles** [comment]
Oh huh so you're not able to start/stop the plugin at all? Did you do the whole restart thing?

**Comment by johnboiles** [comment]
@

**Comment by johnboiles** [comment]
Oops hit the wrong button :D

@gxalpha, upon second read I see you're using your development version. I don't think

**Comment by johnboiles** [comment]
Lol ok I need to stop being on the computer now.

**Comment by gxalpha** [comment]
Oh dangit, I was so used to not having to restart anything now (after I was building it myself all the time) that I forgot to do it, now it works. 🤦
