### ISSUE TITLE
Add version text to the test card

### ISSUE THREAD

**Issue by johnboiles** [johnboiles/obs-mac-virtualcam#84]
For debugging it would be nice to show the Git SHA of the built version in small text on the test card. This will help us verify which version of the plugin is running when we get bug reports.

Probably the tricky part of this is embedding the Git SHA into a header file during the build process (though I bet some googling would show plenty of examples). Once we do that, we should probably also spit out the Git SHA in the log for both the OBS and DAL plugins.

**Comment by gep13** [comment]
@johnboiles this is perhaps a noob question, but... how does one "see" the test card?

**Comment by gxalpha** [comment]
@gep13 The test card is what is shown as an output while the virtual camera is not active.

**Comment by gxalpha** [comment]
Done in #152
