### ISSUE TITLE
Support older versions of macOS (< 10.15)

### ISSUE THREAD

**Issue by colindean** [johnboiles/obs-mac-virtualcam#85]
Freshly installed OBS from official (25.0.8?), freshly installed obs-mac-virtualcam from releases page on this repo. 

Ran `rm -rf ~/Library/Application\ Support/obs-studio` for good measure, still crashes.

Logs from macOS crash window: https://gist.github.com/colindean/de0c14c151bd05b7b1ac0312f9606f63

I'm on mac OS 10.14. Going to 10.15 isn't an option for me at this time.

**Comment by gxalpha** [comment]
The error message says
```
Dyld Error Message:
  Symbol not found: _objc_alloc_init
  Referenced from: /Library/Application Support/obs-studio/*/obs-mac-virtualcam.so (which was built for Mac OS X 10.15)
  Expected in: /usr/lib/libobjc.A.dylib
```
so the OS version may indeed be the problem. We had some people try older versions of macOS, but as far as I know no-one actually did it. It'd be nice if users of older macOS versions could report.

**Comment by johnboiles** [comment]
Let's repurpose this issue to be about support for older macOS versions. I don't currently support anything before 10.15 (Catalina). But if someone wanted to put in the work to add support for older versions that'd be great (as long as it doesn't add _too_ much complexity to the codebase)

**Comment by jasongrout** [comment]
I'm on 10.14, also have the latest OBS 25.0.8, and installed the 1.0 release package of obs-mac-virtualcam. I don't have a crash, and I see the menu item for starting the virtual camera, but I don't see the camera in photobooth, chrome, or firefox after starting the virtual camera and restarting photobooth, chrome, etc. I'm happy to try to find error logs if they would be helpful, but don't know enough about OBS to know where to look.

**Comment by johnboiles** [comment]
Maybe try opening Console.app, then opening OBS, and then start a movie recording in QuickTime. Then see if you see anything in console about `obs-mac-virtualcam`

**Comment by ocirema** [comment]
Hi. 

> Maybe try opening Console.app, then opening OBS, and then start a movie recording in QuickTime. Then see if you see anything in console about `obs-mac-virtualcam`

I did it:

default	23:55:51.459641 +0100	QuickTime Player	Error loading /Library/CoreMediaIO/Plug-Ins/DAL/obs-mac-virtualcam.plugin/Contents/MacOS/obs-mac-virtualcam:  dlopen(/Library/CoreMediaIO/Plug-Ins/DAL/obs-mac-virtualcam.plugin/Contents/MacOS/obs-mac-virtualcam, 0x0106): symbol '_objc_opt_class' not found, expected in '/usr/lib/libobjc.A.dylib', needed by '/Library/CoreMediaIO/Plug-Ins/DAL/obs-mac-virtualcam.plugin/Contents/MacOS/obs-mac-virtualcam'
default	23:55:51.459743 +0100	QuickTime Player	Cannot find function pointer PlugInMain for factory <CFUUID 0x60000292ef00> 35FDFF29-BFCF-4644-AB77-B759DE932ABE in CFBundle/CFPlugIn 0x7fbd257243b0 </Library/CoreMediaIO/Plug-Ins/DAL/obs-mac-virtualcam.plugin> (bundle, not loaded)

**Comment by jasongrout** [comment]
Here's the portion of my logs that seem relevant. I started the virtual camera from the menu item, then launched quicktime and did not see it, then I stopped the virtual camera (which apparently generated a bit of logging as well)

<details>
<summary>Logs</summary>
```
warning: Failed to load 'en-US' text for module: 'decklink-ouput-ui.so'
error: os_dlopen(libpython3.7m.dylib->libpython3.7m.dylib): dlopen(libpython3.7m.dylib, 257): image not found

warning: [Python] Could not load library: libpython3.7m.dylib
2020-05-12 15:55:55.675 obs[17981:138190] Error loading /Library/CoreMediaIO/Plug-Ins/DAL/obs-mac-virtualcam.plugin/Contents/MacOS/obs-mac-virtualcam:  dlopen(/Library/CoreMediaIO/Plug-Ins/DAL/obs-mac-virtualcam.plugin/Contents/MacOS/obs-mac-virtualcam, 262): Symbol not found: _objc_opt_class
  Referenced from: /Library/CoreMediaIO/Plug-Ins/DAL/obs-mac-virtualcam.plugin/Contents/MacOS/obs-mac-virtualcam (which was built for Mac OS X 10.15)
  Expected in: /usr/lib/libobjc.A.dylib
 in /Library/CoreMediaIO/Plug-Ins/DAL/obs-mac-virtualcam.plugin/Contents/MacOS/obs-mac-virtualcam
2020-05-12 15:55:55.675 obs[17981:138190] Cannot find function pointer PlugInMain for factory 35FDFF29-BFCF-4644-AB77-B759DE932ABE in CFBundle/CFPlugIn 0x7fc1257aad60 </Library/CoreMediaIO/Plug-Ins/DAL/obs-mac-virtualcam.plugin> (bundle, not loaded)
warning: A DeckLink iterator could not be created.  The DeckLink drivers may not be installed
info: No blackmagic support
info: [VideoToolbox encoder]: Adding VideoToolbox H264 encoders
info: [obs-browser]: Version 2.8.6
info: VLC found, VLC video source enabled
warning: Failed to load 'en-US' text for module: 'obs-mac-virtualcam.so'
info: ---------------------------------
info:   Loaded Modules:
info:     obs-mac-virtualcam.so
info:     vlc-video.so
info:     text-freetype2.so
info:     rtmp-services.so
info:     obs-x264.so
info:     obs-vst.so
info:     obs-transitions.so
info:     obs-outputs.so
info:     obs-libfdk.so
info:     obs-filters.so
info:     obs-ffmpeg.so
info:     obs-browser.so
info:     mac-vth264.so
info:     mac-syphon.so
info:     mac-decklink.so
info:     mac-capture.so
info:     mac-avcapture.so
info:     linux-jack.so
info:     image-source.so
info:     frontend-tools.so
info:     decklink-ouput-ui.so
info:     coreaudio-encoder.so
info: ---------------------------------
error: os_dlopen(../obs-plugins/obs-browser->../obs-plugins/obs-browser.so): dlopen(../obs-plugins/obs-browser.so, 257): image not found

info: ==== Startup complete ===============================================
error: Service '' not found
info: All scene data cleared
info: ------------------------------------------------
info: coreaudio: device 'Built-in Microphone' initialized
info: [Loaded global audio device]: 'Mic/Aux'
warning: Out of space trying to render glyphs
info: Video Capture Device: Selected device 'FaceTime HD Camera'
info: Video Capture Device: Using preset 1280x720
error: jack-input: jack_client_open Error:Could not create JACK client! JACK Input Client
error: Failed to create source 'JACK Input Client'!
info: Switched to scene 'Scene 4'
info: ------------------------------------------------
info: Loaded scenes:
info: - scene 'Scene 2':
info:     - source: 'Display Capture 2' (display_capture)
info:     - source: 'Video Capture Device' (av_capture_input)
info: - scene 'Scene 4':
info:     - source: 'Scene 2' (scene)
info:     - source: 'Group' (group)
info:         - source: 'Window Capture' (window_capture)
info:         - source: 'JACK Input Client' (jack_output_capture)
info: - scene 'Scene 5':
info:     - source: 'Color Source 2' (color_source_v2)
info:     - source: 'Introducing' (text_ft2_source_v2)
info: ------------------------------------------------
info: Switched to Preview/Program mode
info: ------------------------------------------------
info: adding 46 milliseconds of audio buffering, total audio buffering is now 46 milliseconds (source: Mic/Aux)

info: Output 'virtualcam_output': stopping
info: Output 'virtualcam_output': Total frames output: 5208
info: Output 'virtualcam_output': Total drawn frames: 5206 (5209 attempted)
info: Output 'virtualcam_output': Number of lagged frames due to rendering lag/stalls: 3 (0.1%)
```
</details>

**Comment by johnboiles** [comment]
Thanks for the reports. Looks like all of the above have `Symbol not found: _objc_opt_class`. That's probably the place to start for supporting macOS < 10.15

**Comment by colindean** [comment]
So I followed the very convenient and straightforward build instructions (improved them a smidge in #89 and a little more in #90) and was able to build OBS and this plugin just fine, and it works: I was able to get an OBS Virtual Cam working in Firefox on https://meet.jit.si. It didn't work in Zoom but that's a known issue, IIRC.

I think the "trick" is going to be building the plugin on CI targeting an older version of macOS. 

It appears that Github Actions supports only building on 10.15 (see [`runs-on` docs](https://help.github.com/en/actions/reference/workflow-syntax-for-github-actions#jobsjob_idruns-on)) so maybe there's something to put into the build process to tell the compiler to target an older version of the macOS SDK.

I don't really know Xcode/CMake stuff, but I notice in `src/dal-plugin/Info.plist` that there's an `DTSDKName` key with a value of `macosx10.15`. Maybe that could be 10.14?

**Comment by jasongrout** [comment]
I don't really have experience with this either, but perhaps https://stackoverflow.com/a/58653850 is useful?

Thanks for noting that compiling the plugin works!

**Comment by jasongrout** [comment]
I compiled this plugin and obs on macos 10.14. It works! At least, I was able to see it in Chrome (using jitsi), and things seemed to work well. When I tried to use it from Quicktime, I saw the virtual camera, but I couldn't get it to show anything but the test card.

**Comment by johnboiles** [comment]
@colindean it's worth a try to change that I guess, but I _don't think_ the Info.plist affects compilation or linking (though I might be wrong).

**Comment by Mesihas** [comment]
Get this errors when trying to make:
`AleDesktops-iMac:build aledesktop$ make -j
Scanning dependencies of target obs-plugin
Scanning dependencies of target dal-plugin
[  7%] Building CXX object src/dal-plugin/CMakeFiles/dal-plugin.dir/MachClient.mm.o
[ 15%] Building CXX object src/dal-plugin/CMakeFiles/dal-plugin.dir/Device.mm.o
[ 23%] Building CXX object src/dal-plugin/CMakeFiles/dal-plugin.dir/PlugIn.mm.o
[ 53%] Building CXX object src/dal-plugin/CMakeFiles/dal-plugin.dir/PlugInMain.mm.o
[ 53%] Building CXX object src/dal-plugin/CMakeFiles/dal-plugin.dir/PlugInInterface.mm.o
[ 53%] Building CXX object src/dal-plugin/CMakeFiles/dal-plugin.dir/ObjectStore.mm.o
[ 53%] Building CXX object src/dal-plugin/CMakeFiles/dal-plugin.dir/Stream.mm.o
[ 61%] Building CXX object src/dal-plugin/CMakeFiles/dal-plugin.dir/CMSampleBufferUtils.mm.o
[ 69%] Building CXX object src/dal-plugin/CMakeFiles/dal-plugin.dir/TestCard.mm.o
[ 84%] Building CXX object src/obs-plugin/CMakeFiles/obs-plugin.dir/plugin-main.mm.o
[ 84%] Building CXX object src/obs-plugin/CMakeFiles/obs-plugin.dir/MachServer.mm.o
/Users/aledesktop/source/obs-mac-virtualcam/src/dal-plugin/ObjectStore.mm:89:14: error: use of undeclared identifier
      'kCMIODevicePropertyDeviceHasStreamingError'; did you mean 'kCMIODevicePropertyDeviceHasChanged'?
        case kCMIODevicePropertyDeviceHasStreamingError:
             ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
             kCMIODevicePropertyDeviceHasChanged
/Library/Developer/CommandLineTools/SDKs/MacOSX10.14.sdk/System/Library/Frameworks/CoreMediaIO.framework/Headers/CMIOHardwareDevice.h:475:5: note: 
      'kCMIODevicePropertyDeviceHasChanged' declared here
    kCMIODevicePropertyDeviceHasChanged                     = 'diff',
    ^
/Users/aledesktop/source/obs-mac-virtualcam/src/dal-plugin/ObjectStore.mm:89:14: error: duplicate case value 'kCMIODevicePropertyDeviceHasChanged'
        case kCMIODevicePropertyDeviceHasStreamingError:
             ^
/Users/aledesktop/source/obs-mac-virtualcam/src/dal-plugin/ObjectStore.mm:41:14: note: previous case defined here
        case kCMIODevicePropertyDeviceHasChanged:
             ^
2 errors generated.
make[2]: *** [src/dal-plugin/CMakeFiles/dal-plugin.dir/ObjectStore.mm.o] Error 1
make[2]: *** Waiting for unfinished jobs....
make[1]: *** [src/dal-plugin/CMakeFiles/dal-plugin.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
/Users/aledesktop/source/obs-mac-virtualcam/src/obs-plugin/plugin-main.mm:34:1: warning: control reaches end of non-void function [-Wreturn-type]
}
^
1 warning generated.
[ 92%] Linking CXX shared module obs-mac-virtualcam.so
[ 92%] Built target obs-plugin
make: *** [all] Error 2`

**Comment by jasongrout** [comment]
@Mesihas - what version of macOS are you on?

**Comment by mlalgjar** [comment]
I'd like to add a request for High Sierra (10.13.6) as it's the last OS X to support Syphon. Syphon is a great frame serve protocol that OBS uses (as well as MANY other audiovisual applications). Unfortunately the only way to get Syphon working on newer OS X versions is to disable system integrity protection.

And unfortunately for me, High Sierra is the last OS X version to support accelerated Nvidia drivers. Anything would be appreciated.

**Comment by johnboiles** [comment]
@OBS127 shared this video on building things from source also that might come in handy for folks trying to run this on old macOS https://www.youtube.com/watch?v=CIYeb2m5a0g

@jasongrout that looks like the right direction for sure.

**Comment by johnboiles** [comment]
@mlalgjar if you want to help make this happen, please post your logs from OBS and Console.app. We don't have any logs from 10.13 yet I don't think. The first step is to understand what doesn't work.

**Comment by Mesihas** [comment]
@jasongrout 10.14.6

**Comment by jasongrout** [comment]
More possibly relevant links for compiling on 10.15 for < 10.15.

* https://developer.apple.com/library/archive/documentation/DeveloperTools/Conceptual/XcodeProjectManagement/210-Building_Products/building.html#//apple_ref/doc/uid/TP40002693-SW38 (says it is outdated, but I can't find a corresponding section in the current documentation)
* https://developer.apple.com/library/archive/documentation/DeveloperTools/Conceptual/cross_development/Configuring/configuring.html
* https://stackoverflow.com/questions/25352389/what-is-the-difference-between-macosx-deployment-target-and-mmacosx-version-min indicates that we may be able to set an environment variable

**Comment by johnboiles** [comment]
@jasongrout figured this out in #94! Thanks @jasongrout!! For those of you on 10.14, go try it by downloading the pkg file in the artifacts [here](https://github.com/johnboiles/obs-mac-virtualcam/runs/672887718?check_suite_focus=true) and report back 

For those of you on 10.13, we can try that next. Hopefully it's just as simple.

**Comment by jasongrout** [comment]
I just tried compiling on 10.13.6. I got what looks like the same error that @Mesihas posted [above](https://github.com/johnboiles/obs-mac-virtualcam/issues/85#issuecomment-627807628):

```
/<snip>/obs-mac-virtualcam/src/dal-plugin/ObjectStore.mm:89:14: error: use of undeclared identifier 'kCMIODevicePropertyDeviceHasStreamingError'; did you
      mean 'kCMIODevicePropertyDeviceHasChanged'?
        case kCMIODevicePropertyDeviceHasStreamingError:
             ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
             kCMIODevicePropertyDeviceHasChanged
/System/Library/Frameworks/CoreMediaIO.framework/Headers/CMIOHardwareDevice.h:475:5: note: 'kCMIODevicePropertyDeviceHasChanged' declared here
    kCMIODevicePropertyDeviceHasChanged                     = 'diff',
    ^
/<snip>/obs-mac-virtualcam/src/dal-plugin/ObjectStore.mm:89:14: error: duplicate case value 'kCMIODevicePropertyDeviceHasChanged'
        case kCMIODevicePropertyDeviceHasStreamingError:
             ^
/<snip>/obs-mac-virtualcam/src/dal-plugin/ObjectStore.mm:41:14: note: previous case defined here
        case kCMIODevicePropertyDeviceHasChanged:
             ^
2 errors generated.
make[2]: *** [src/dal-plugin/CMakeFiles/dal-plugin.dir/ObjectStore.mm.o] Error 1
make[2]: INTERNAL: Exiting with 7 jobserver tokens available; should be 6!
make[1]: *** [src/dal-plugin/CMakeFiles/dal-plugin.dir/all] Error 2
make: *** [all] Error 2
```

**Comment by jasongrout** [comment]
@Mesihas - what version of xcode do you have? `xcodebuild -version`

**Comment by johnboiles** [comment]
@jasongrout are you testing with a 10.13 vm or do you have a 10.13 computer around also? I'm trying your simple fix for 10.13 as well https://github.com/johnboiles/obs-mac-virtualcam/pull/96

**Comment by jasongrout** [comment]
I have a 10.13 computer that I thought I'd try compiling on before doing the fix. I'll try what you have in #96.

**Comment by jasongrout** [comment]
Looks like xcode 10.2 requires Mojave, so if the error above came from having too old of an xcode, I can't change that.

**Comment by jasongrout** [comment]
#98 fixes the compile error on 10.13 for me.

**Comment by johnboiles** [comment]
10.13 should also be supported now in the pkg installer [here]. I'd love for a few people to confirm it works for them on 10.13 before I cut the release.

Thanks @jasongrout for all your help!

**Comment by Jip-Hop** [comment]
> @jasongrout figured this out in #94! Thanks @jasongrout!! For those of you on 10.14, go try it by downloading the pkg file in the artifacts [here](https://github.com/johnboiles/obs-mac-virtualcam/runs/672887718?check_suite_focus=true) and report back
> 
> For those of you on 10.13, we can try that next. Hopefully it's just as simple.

It's working for me now on 10.14 🥳

**Comment by speech-figure** [comment]
I'm really hoping someone could at least entertain the thought of making the plugin work within OS10.12, which requires using OBS 24.06 (higher versions of OBS don't work on 10.12). Is there an obvious hurdle to doing this, given the recent success with 10.13?
I'd love to help out by writing something myself but don't have the chops/experience/background/basic knowledge/tools/competence/etc. But it'd be great if anyone could say if that request is actually viable or not (I assume the OBS code base is changed significantly from v24 to 25). Apologies for the noise, but not sure where else to post this kind of a query.

**Comment by OBS127** [comment]
YES! YES! It Loaded in properly and appears to be doing what it's supposed
to, but I need time to work with it as all I see is the mirrored repeat
that is typical of these types of cameras (Am I explaining it right? LOL).I
need to get to bed and play with it tomorrow evening to understand it
better.

I feel like I'm a part of history in the making! I'll get back to you!

Thanks so much!
Frank

**Comment by OBS127** [comment]
Oops! Now it's totally black!  I might have been looking at a source that
was already on when I said it was mirroring. I'm sure it's something I need
to learn how to do, but if you have any steps to follow it would be
appreciated. It loaded in perfectly and the interface looks great! Thanks!

**Comment by OBS127** [comment]
Nope! It does work! I tried something and it showed me that it's working!
However, it is still repeatedly  mirroring. i understand it's a
normal function and will figure it out. You guys are AWESOME! Definitely
bedtime! LOL.

**Comment by jasongrout** [comment]
> When I tried to use it from Quicktime, I was able to select the virtual camera, but I couldn't get it to show anything but the test card.

This now works for me. I think it just needed a reboot.

**Comment by ashleyjamesbrown** [comment]
10.13.6 here. I installed OBS latest. Ran it and it works fine. 
I downloaded the latest pkg 5db91b4-v1.0.0 and installed it.
OBS will not open at all. Bounces and closes. 

Main error in the Apple log. 

```
Dyld Error Message:
  Symbol not found: _objc_alloc_init
  Referenced from: /Library/Application Support/obs-studio/*/obs-mac-virtualcam.so (which was built for Mac OS X 10.15)
  Expected in: /usr/lib/libobjc.A.dylib
```

**Comment by ashleyjamesbrown** [comment]
> 10.13 should also be supported now in the pkg installer [here]. I'd love for a few people to confirm it works for them on 10.13 before I cut the release.
> 
> Thanks @jasongrout for all your help!

unfortunately it doesnt work for me and OBS wont open at all anymore. I did remove the OBS folder/uninstall and then reboot and reinstall (but no package) and OBS will not open. Just bounces, and closes.

IS there anyway i can find all teh files the package installed in case for some reason its the older one and i cant overwrite it? Or is there another issue. Let me know what you need from me to support investigating.

**Comment by gxalpha** [comment]
Hey @ashleyjamesbrown,
this is not the newest installer. Try [this](https://github.com/johnboiles/obs-mac-virtualcam/actions/runs/104441750) one.
(The readme link is probably wrong, I'll double check)

**Comment by gxalpha** [comment]
> IS there anyway i can find all teh files the package installed in case for some reason its the older one and i cant overwrite it? Or is there another issue. Let me know what you need from me to support investigating.

See the uninstalling section in the wiki under Installation

**Comment by ashleyjamesbrown** [comment]
> Hey @ashleyjamesbrown,
> regarding your first comment:
> this is not the newest installer. Try [this](https://github.com/johnboiles/obs-mac-virtualcam/actions/runs/104441750) one.
> (The readme link is probably wrong, I'll double check)

legend. yes the readme/releases seems wrong. ill give that a go.

**Comment by gxalpha** [comment]
Ok I added a new release to the releases section and it should work if you (and everyone else) downloads it from there

**Comment by ashleyjamesbrown** [comment]
IT WORKS !!! Thanks so much. A quick install, reboot and Start Virtual Cam and it appeared in jit.si as a device to select. Yes its wierdly flipped everything but ill just transform everything in OBS. Nice one. My DnD can have a nice overlay now :-) Much appreciated

**Comment by gxalpha** [comment]
Don't worry about the flip, it is only the preview of Jitsi.
*Your partner will see what you see in OBS, so if you see everything correctly in the OBS preview, so will he.*

**Comment by cbfreeborn** [comment]
Just downloaded and installed the obs-mac-virtualcam-a5a1e9e-master.pkg on my High Sierra 10.13.6 system running OBS 25.0.8 and it seems to work great! Also connects fine to Zoom 4.6.10 and 5.0.2. So grateful for the work that's be done on this package!! :))

**Comment by ocirema** [comment]
I also used obs-mac-virtualcam-09a3abf-master.pks in Mojave 14.0.6 and it works fine with Zoom 5.0.2.
IT'S ALIVE!!!!! MUHAAAAAA!!!

Thanks guys!. Looking great!

**Comment by johnboiles** [comment]
Ok great! Thanks for all the reports y'all! And thanks especially to @jasongrout who drove this effort!

Just promoted the pre-release @gxalpha made to a full release with [v1.1.0](https://github.com/johnboiles/obs-mac-virtualcam/releases/tag/v1.1.0) :tada:

**Comment by OBS127** [comment]
I played with it a bit today and am not sure how to set it up to display
more than one window at a time if that is the intention. Do I try to layer
the sources together and it will display everything through quicktime or
wherever. Not sure what to do.

Also I was happy that it appeared in Facetime, but it stays at the logo. I
did call myself to see if it would activate it through a call, but it
didn't seem to.

Grateful that you did this. I'll figure it out.

Thanks!
Frank

**Comment by johnboiles** [comment]
I realized I forgot to actually change the version in the Info.plist in the plugin. I'm wondering if that was making it so that y'all had to reboot after installing the new plugin. I've replaced the 1.1.0 release with an updated version with the correct version numbers.

If you had to reboot to make the plugin work, would you mind re-downloading [1.1.0](https://github.com/johnboiles/obs-mac-virtualcam/releases/tag/v1.1.0), reinstalling it, then seeing if it works in QuickTime without a reboot? This will help inform me on whether more work is needed in #109. Thanks!!

**Comment by Mesihas** [comment]
When I installed the first release for Mojave I didn't have to reboot to make it work, it just worked strait away. But I can try 1.1.0 you want me to do it.

**Comment by johnboiles** [comment]
Yes please, I believe only people who have the plugin installed, and then install a new version, have had to restart

**Comment by Mesihas** [comment]
ok, I installed 1.1.0 on top of the first version, started OBS then Virtual cam and QuickTime sees the virtual cam.

**Comment by Mesihas** [comment]
In my case the plugin get installed on this path:
/Library/Application Support/obs-studio/plugins/obs-mac-virtualcam/bin/obs-mac-virtualcam.so

Is not showing the version number on finder (maybe will be useful) for future test

**Comment by johnboiles** [comment]
Yeah the version number is inside the Info.plist at `/Library/CoreMediaIO/Plug-Ins/DAL/obs-mac-virtualcam.plugin/Contents/Info.plist`

**Comment by OBS127** [comment]
Johnboiles, It works in quicktime FANTASTIC!  Wondering about Facetime.
That would be great! Thanks!

**Comment by gxalpha** [comment]
Regarding FaceTime see https://github.com/johnboiles/obs-mac-virtualcam/wiki/Compatibility#macOS-System-Apps-block-DAL-plugins, we can't really do anything about it

**Comment by OBS127** [comment]
GXALPHA, I understand. I'm grateful that you guys have made this available
for quicke and other apps. I have tried many different free apps that
aren't compatible with it either. Maybe it was a proprietary decision by
apple to do this?  It's to bad Facetime isn't a little more available to
write code for it. Thanks for your quick response! Frank
