### ISSUE TITLE
The virtual cam does not appears in Zoom

### ISSUE THREAD

**Issue by pascalandy** [johnboiles/obs-mac-virtualcam#86]
- OBS 25.0.8
- VirtualCam 1.0.0

![Screen Shot 2020-05-12 at 6 13 20 PM](https://user-images.githubusercontent.com/6694151/81750950-7c456680-947c-11ea-95b2-4266a4d5284a.jpg)

![Screen Shot 2020-05-12 at 6 13 24 PM](https://user-images.githubusercontent.com/6694151/81750958-7fd8ed80-947c-11ea-9bdd-9b6bf74caba2.jpg)

**Comment by gxalpha** [comment]
See https://github.com/johnboiles/obs-mac-virtualcam/wiki/Compatibility
