### ISSUE TITLE
[DAL]: Stream-/Camera creator is called "SampleVCam"

### ISSUE THREAD

**Issue by gxalpha** [johnboiles/obs-mac-virtualcam#87]
See the attached screenshot:
<img width="1153" alt="Bildschirmfoto 2020-05-13 um 00 33 40" src="https://user-images.githubusercontent.com/59806498/81752351-951c3f00-94b1-11ea-9721-47ad636e59f8.png">
I'd love to send a fix right now, but I need some sleep and just wanted to note the issue down.
It's more of a minor thing but it should be corrected at some point.

Also we may want to introduce a "low priority" label for stuff like this

**Comment by johnboiles** [comment]
Good catch. I see it here https://github.com/johnboiles/obs-mac-virtualcam/blob/338097cbee18758fda423e2ca41802f07a5f01d1/src/dal-plugin/Info.plist#L12

**Comment by johnboiles** [comment]
That change was pretty simple, and i can't imagine it not working. But just in case we can test by installing the pkg from the GitHub action artifacts when it's done. https://github.com/johnboiles/obs-mac-virtualcam/runs/668845622?check_suite_focus=true

**Comment by johnboiles** [comment]
Confirmed it is fixed and the plugin still works 😄 
![image](https://user-images.githubusercontent.com/218876/81756112-a93f4c80-946f-11ea-9c9a-94daee168f77.png)
