### ISSUE TITLE
QuickTime video recording only records a couple frames

### ISSUE THREAD

**Issue by johnboiles** [johnboiles/obs-mac-virtualcam#91]
Probably a timestamp issue similar to https://github.com/johnboiles/coremediaio-dal-minimal-example/pull/13

**Comment by Jip-Hop** [comment]
I tried installing `obs-mac-virtualcam-a70ec47-v1.1.2.pkg` but it didn't fix the QuickTime recording for me... Perhaps I did something wrong? But it does work now with the `obs-mac-virtualcam-38c1f27-master.pkg` downloaded from [here](https://github.com/johnboiles/obs-mac-virtualcam/suites/722453409/artifacts/7173196). I'm on Mojave with OBS 25.0.8.

**Comment by johnboiles** [comment]
Interesting. Glad it's working now. Did you restart QuickTime after installing 1.1.2? 

If you ever see something that should be working that's not working can you double check the version number?

`cat /Library/CoreMediaIO/Plug-Ins/DAL/obs-mac-virtualcam.plugin/Contents/Info.plist | grep -A3 CFBundleShortVersion`

We've been having some trouble with the installer not always overwriting the plugin. Not sure why.
