### ISSUE TITLE
Virtual Camera is started in OBS but the video output is still "OBS Virtual Cam is inactive"

### ISSUE THREAD

**Issue by clemkn** [johnboiles/obs-mac-virtualcam#92]
![download](https://user-images.githubusercontent.com/3251110/81862275-c1939200-9569-11ea-8ca0-fed7779befaa.png)

My video output is always the default image even if I stop and restart the virtual cam, restart QuickTime/Firefox InstaScan etc.

OBS-mac-virtualcam 1.0.0
OBS Studio 25.0.8
MacOS Catalina 10.15.2

**Comment by gxalpha** [comment]
Hey, could you please provide an OBS log with the problem? First reproduce it, then go to Help -> Log files -> Upload current log file and post the link)

**Comment by teacherguy2020** [comment]
Yesterday things were fine, but today I too only got the animated status screen. I restarted to no avail. I then deleted everything and reinstalled OBS and the latest .pkg for Virtual Cam. Now running as expected.

**Comment by clemkn** [comment]
here's my log file https://obsproject.com/logs/-YqBiV_ByWTklB5i

**Comment by gxalpha** [comment]
Did you reproduce the problem before uploading it? It is only 2 seconds long

**Comment by johnboiles** [comment]
@clemkn @teacherguy2020 can y'all open the Console.app, then try to create a recording in QuickTime and post any logs that mention `obs-mac-virtualcam`?

**Comment by Fray117** [comment]
![Screen Shot 2020-05-14 at 14 52 10](https://user-images.githubusercontent.com/39966763/81907783-7ec9cc80-95f2-11ea-87c6-cff16f1a2634.png)
it said server unavailable

**Comment by denwald** [comment]
@Fray117 Try rebooting. I had to reboot for the plugin to show live video in Quicktime. Haven't tested other applications yet.

**Comment by clemkn** [comment]
@denwald @johnboiles It's working after rebooting. Thanks!

**Comment by gxalpha** [comment]
@Fray117 does it work for you as well?

**Comment by johnboiles** [comment]
Baffling to me why some people need to reboot and not others 🤷‍♂️

**Comment by teacherguy2020** [comment]
Just a quick word about the new Messenger Rooms...if OBS is running before I open the "room" it results in an error. I think this is because OBS has control of my webcam and Chrome wants to use it. If I quit OBS, then open the Messenger Room, and THEN start OBS/turn on virtual camera, it works fine!

**Comment by johnboiles** [comment]
@teacherguy2020 add it to the wiki https://github.com/johnboiles/obs-mac-virtualcam/wiki/Compatibility

I think we're all solved here with a reboot right? @gxalpha added a note about rebooting to the recent release as well. I will add to the readme also.
