### ISSUE TITLE
OBS quits with Virtual Cam at startup. 

### ISSUE THREAD

**Issue by OBS127** [johnboiles/obs-mac-virtualcam#93]
Hi,
I just downloaded the virtual cam for the Mac OS High Sierra today 5.13.20. I am using the latest version of OBS  25.0.8. 64 bit. It installs correctly and when I start OBS it quits. I've installed and uninstalled several times thinking maybe it's the way I'm doing it, but OBS always quits at startup.....well if I install it while OBS is running OBS stays running, but the VWC doesn't appear anywhere. 

Is their something I can do to fix this? By the way, Thanks Johnboiles for leaving the info as to what files were installed where. I was able to quickly uninstall it so that OBS could run.  

Thank You for working on this for us mac users and I look forward to your response! 

Frank

**Comment by gxalpha** [comment]
Unfortunatly, High Sierra is not yet supported by this plugin.
See https://github.com/johnboiles/obs-mac-virtualcam/issues/85

**Comment by OBS127** [comment]
Thank You gxalpha.  Any timetable as to when? I'm hoping the older OS's will be supported as I am limited to using it. My high end music software Pro Tools dictates what OS I use. If I upgraded my OS I would have to pay a lot of money to upgrade P.T. Thanks again for your quick response.  Frank

**Comment by gxalpha** [comment]
Hey, since the main developer @johnboiles is not able to build / develop for older versions of macOS, I'm afraid I can't give you a timetable on when it will be done. Let's just hope that someone does it in the near future!
I would highly recommend you watch #85, maybe some hack will be posted there that won't / can't be integrated into the plugin immediately but will make it work, we've had some of those in the past with other topics

**Comment by OBS127** [comment]
Hi John, 
 I watched a tutorial that explains how to get into terminal to use it. It seems really straight forward, but I'm not comfortable with terminal to that extent. I may try this at some point though.  Thanks for looking into this for me gxalpha and Johnboiles. 
This is the link if it could help someone else: https://www.youtube.com/watch?v=CIYeb2m5a0g

**Comment by johnboiles** [comment]
Thanks for sharing that video @OBS127 I'll cross post that into #85

The biggest way you could help would be to post any logs from Console.app that mention obs-mac-virtualcam when you try to run OBS and stream the webcam to quicktime. I think I'm starting to understand what would need to be done for 10.14, but I don't have any logs for 10.13 yet.

**Comment by OBS127** [comment]
Thanks Johnboiles, I totally appreciate your willingness to help.  I will try the console app to give you the proper information. However, I will have to wait a few days as I have work responsibilities and will try posting the logs as soon as they are over.  Thanks

**Comment by OBS127** [comment]
I got excited when I got the notification that you figured it out for current OS's I had to see if I could quickly get my log files. LOL Is this what you need?  Thanks! 
[2020-05-13 15-09-32.txt](https://github.com/johnboiles/obs-mac-virtualcam/files/4625712/2020-05-13.15-09-32.txt)

Oops! I don't know how to upload crash reports or log files. LOL. I tried to grag them to this doc, but it don't work.

**Comment by gxalpha** [comment]
Hey @OBS127, 

it looks like High Sierra should work with the latest version. Could you try to downlowd the latest pkg and try again?

**Comment by OBS127** [comment]
This is exciting news! However, can you give me the direct link to download
it, please? I seem to only be able to find the first release and not your
recent update for some reason.  I am not a computer programmer and find it
a little challenging to find things on that site. Albeit I am super
grateful for all that you guys have made available when I can find it!

THANK YOU so much! I can see the future possibilities with the OBS Virtual
Cam for the Mac!

It's bedtime where I live and have a full day tomorrow. i can't wait to try
it which will be later in the evening!

Thanks,
Frank

**Comment by gxalpha** [comment]
Download the package from [here](https://github.com/johnboiles/obs-mac-virtualcam/actions/runs/104359074), then follow installation steps as usual.

**Comment by OBS127** [comment]
Hi,
OBS shows up in Facetime an it stays at the logo. I've tried a restart in OBS tools and a few other things, but it doesn't change. How do I fix this in OS High Sierra. The great thing is that the Virtual Camera appears everywhere. Thanks.

**Comment by gxalpha** [comment]
According to [Compatibility](https://github.com/johnboiles/obs-mac-virtualcam/wiki/Compatibility) FaceTime isn't supported, but thanks for telling us that it also doesn't work in High Sierra, I'll note it down in #104

**Comment by johnboiles** [comment]
@OBS127 any logs from Console.app that mention `obs-mac-virtualcam` would be useful.

**Comment by OBS127** [comment]
Hi John, 
I went to help - log files and found the following. Is this what you mean? I use Facetime for just about everything so I truly appreciate it. Thanks, Frank:
 
[2020-05-14 04-27-43.txt](https://github.com/johnboiles/obs-mac-virtualcam/files/4631548/2020-05-14.04-27-43.txt)

**Comment by OBS127** [comment]
default	23:32:59.383677 -0400	avconferenced	OBSDAL: Server is not available

**Comment by OBS127** [comment]
Hi Guys,

I am trying it in VLC Media player and it doesn't work also.  This is what
I got. Thanks for all you do!

OS High Sierra 10.13.6. OBS 25.0.8. 64 bit. VLC Media player 3.0.10




OBSDAL: Server is not available

15:15:23.384768 -0400 diagnostics_agent com.apple.message.domain:
com.apple.usage.app_activetime
com.apple.message.signature: obs
com.apple.message.signature2: com.obsproject.obs-studio ||| 25.0.8 (25.0.8)
com.apple.message.value: 4
com.apple.message.value2: 4
com.apple.message.value3: 4
com.apple.message.value4: 0
com.apple.message.value5: 4
com.apple.message.value6: 1
com.apple.message.value7: 4
com.apple.message.result: YES
com.apple.message.summarize: YES
SenderMachUUID: D1B5343C-D697-3D7E-B5BE-8554E23E77CA
