### ISSUE TITLE
CRASH - do not work

### ISSUE THREAD

**Issue by shamun** [johnboiles/obs-mac-virtualcam#99]
Does not work the latest .pkg.

Crash when OBS studio is started:
![image](https://user-images.githubusercontent.com/107349/81907499-28479880-95c8-11ea-95f3-ecf0850b6885.png)

![image](https://user-images.githubusercontent.com/107349/81907544-37c6e180-95c8-11ea-9285-1e3ad040d129.png)

**Comment by gxalpha** [comment]
Could you try [this](https://github.com/johnboiles/obs-mac-virtualcam/actions/runs/104359074) installer pkg?

**Comment by shamun** [comment]
Step 1. Tried this: https://github.com/johnboiles/obs-mac-virtualcam/actions/runs/104359074

![image](https://user-images.githubusercontent.com/107349/81910269-03552480-95cc-11ea-9218-14fef8384eb5.png)



Step 2. Restarted all applications

![image](https://user-images.githubusercontent.com/107349/81910101-d0129580-95cb-11ea-8c17-40977bf38305.png)

![image](https://user-images.githubusercontent.com/107349/81910167-e02a7500-95cb-11ea-9744-8f62fc90f7fe.png)



Step 3. Selected in Google chrome (latest). OBS camera.

![image](https://user-images.githubusercontent.com/107349/81909955-a0fc2400-95cb-11ea-8d29-63256df2ea5a.png)

Result fail: Camera view is showing as below:

![image](https://user-images.githubusercontent.com/107349/81909989-af4a4000-95cb-11ea-9764-6afcb917f9a8.png)
